### PR TITLE
[ENHANCEMENT] deprecate CLI command `validation-operator run`

### PR DESCRIPTION
**Pull request by Aylr**
Changes proposed in this pull request:
Deprecate the CLI command `validation-operator run` which has been slated for deprecation for a long time.

### CODE REVIEW

**Comment by alexsherstinsky** [comment]
@Aylr Let's agree (discuss first) that `https://github.com/superconductive/great_expectations/pull/343` should be merged first.  And then we can review/merge the subsequent PRs on top of this as appropriate.  Thanks.

**Review by spbail — COMMENTED** [review]
If I understand this correctly, this deprecates the command entirely from the CLI? We decided in the design spec that we're going to keep the old API CLI path as-is, and only print a warning of the type "This command is deprecated in the new API" for deprecated commands when the --new-api flag is used.

**Comment by Aylr** [comment]
@spbail this was already slated for deprecation ages ago and by removing it now will be one less thing to maintain.

**Comment by Aylr** [comment]
Closing for now after a discussion about being gentle to users.

**Pull request closed without merging**
