### PR TITLE
Documentation improvements and typos fix

### PR DESCRIPTION
**Pull request by mzjp2**
Fixing a few small things I noticed in the docs and error messages. Sorry for the tiny PR, I tried to gather everything I found in one. :)

### CODE REVIEW

**Review by Aylr — APPROVED** [review]
Great fixes! Thanks a lot!

**Comment by mzjp2** [comment]
@cla-bot check

**Comment by mzjp2** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by Aylr** [comment]
@cla-bot check

**Pull request merged**
