### PR TITLE
[FEATURE] Improve Trino types support

### PR DESCRIPTION
**Pull request by ms32035**
Changes proposed in this pull request:
- Improve support of Datatypes in the execution engine and expectations

### Definition of Done
Please delete options that are not relevant.

- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by kenwade4** [comment]
Hi @ms32035 thanks for the contribution.

While there aren't any failing tests (due to the pipeline not running tests against trino), the build_gallery process is showing `"module 'trino.sqlalchemy.dialect' has no attribute 'name'"` for several core Expectations that were not failing before. (expect_column_values_to_be_of_type expect_column_values_to_match_like_pattern expect_column_values_to_match_like_pattern_list expect_column_values_to_match_regex expect_column_values_to_match_regex_list expect_column_values_to_not_match_like_pattern expect_column_values_to_not_match_like_pattern_list expect_column_values_to_not_match_regex expect_column_values_to_not_match_regex_list)

**Comment by kenwade4** [comment]
After you pull latest from develop into this branch, you can run build_gallery locally against those specific Expectations on trino if you have docker

```
% cd assets/docker/trino

% docker-compose up
```

In another terminal, activate your virtual environment, then 

```
% cd assets/scripts

% python ./build_gallery.py --backends "trino" expect_column_values_to_be_of_type expect_column_values_to_match_like_pattern expect_column_values_to_match_like_pattern_list expect_column_values_to_match_regex expect_column_values_to_match_regex_list expect_column_values_to_not_match_like_pattern expect_column_values_to_not_match_like_pattern_list expect_column_values_to_not_match_regex expect_column_values_to_not_match_regex_list
```

**Review by kenwade4 — DISMISSED** [review]
See PR comments

**Comment by ms32035** [comment]
@kenwade4 patched this, but in general there's a problem here https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/expectations/metrics/map_metric_provider.py#L414 as in some cases a dialect is passed and in others a module

**Review by Shinnnyshinshin — APPROVED** [review]
Hi @ms32035 thank you for this contribution. It looks like the issues that @kenwade4 mentioned before have been resolved, as well as the formatting issue you mentioned on Dec 20. 

Ken is currently away on paternity leave, but we wanted to make sure your contribution got merged as soon as possible. I'm going to put an approval and we will merge on our end :) thank you again, we hope to work with you again soon.

**Pull request merged**
