### PR TITLE
[HACKATHON] 4 GeoSpatial Expectations ExpectColumnValuesGeometryToBe(Within/Near/Intersect/CentroidsWithin)Shape

### PR DESCRIPTION
**Pull request by pjdobson**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Added 4 Expectations to check whether column values submitted as geos geometries interact with a given reference shape (within, intersects, centroids within, or near - within a certain distance)
-
-

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by pjdobson** [comment]
@cla-bot check

**Review by austiezr — APPROVED** [review]
@pjdobson Thanks for your submissions! Be sure to link this PR in your [DevPost](https://greatexpectations.devpost.com/) submission as well. 🚀

**Comment by austiezr** [comment]
@cla-bot check

**Comment by austiezr** [comment]
@pjdobson Is this PR coming from a different source than your others? We're missing a signed CLA here but I know you've signed previously.

**Comment by pjdobson** [comment]
> @pjdobson Is this PR coming from a different source than your others? We're missing a signed CLA here but I know you've signed previously.

Hi @austiezr, I had some git config options that I missed so my email wasn't configured. I'm not sure how to change it here - I've tried --amend --author but it doesn't stick. Or I can close and resubmit. Please let me know.

I also reached out to @kyleaton on Slack, so hopefully we're OK to get this resolved and merged - as long as everything else you need is passing.

**Comment by pjdobson** [comment]
@cla-bot check

**Comment by pjdobson** [comment]
@cla-bot check

**Comment by austiezr** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by austiezr** [comment]
@cla-bot check

**Comment by pjdobson** [comment]
Hi @austiezr and @kyleaton. This was my fault on the config of my git on a new machine. I didn't have the email configured on the initial commit, so it's not a valid email address and I can't sign the form with the one that was pushed. I updated the rest of the commits with --amend --update-author, and that seems to work for all the edits, but not the original push. I can't find a clean way to change it without destroying the whole branch and overwriting subsequent changes. I'm reluctant to do that in something that's not my isolated repository, as I'm not confident enough in my git knowledge to do that.  I'm happy to resubmit a new PR, or I'm not sure if the bot can look at other subsequent commits or github handle or something. 

Let me know what works best.

**Comment by austiezr** [comment]
Hey @pjdobson ! I think the best path forward here is to have you submit a new PR for this work; your submission will still be valid and counted for the hackathon. Thanks for working with us on this! Ping me once you have the new PR up.

**Pull request closed without merging**
