### PR TITLE
PEP8 linting

### PR DESCRIPTION
**Pull request by elsander**
I accidentally PEP9-ified a file in a previous PR (my text editor runs a flake8 lint on save), and @jpcampb2 mentioned wanting to bring the code closer to PEP8. I figured the more standard and readable the code is, the easier it is to contribute, so I thought I'd run the codebase through my linter to make those changes and isolate them in one PR.

The linting changes include:
- standardizing the number of line breaks between imports and functions
- standardizing spacing in comments and variable assignment
- breaking up long lines
- removing unused imports (I did this by hand, and made sure it didn't affect the functionality)
- removing unused variable assignments (I removed a couple of stray variables from tests by hand)

None of these changes should affect the code functionality in any way. Of course, feel free to close the PR if this doesn't match the style you want for the codebase.

### CODE REVIEW

**Comment by jpcampb2** [comment]
@elsander Thank you so much for working on this, and sorry it's taking a long time to get this merged in. I'm trying to make sure that we can put in checks so that future PRs will respect the PEP8 conventions that you've brought to bear here, and so took a look at trying to add a PEP8 checker like flake8 to the travis process, but I'm still getting lots of errors even when looking at the post-PR version. Did you focus only on some specific changes and/or do you mind sharing the linter you used so I can replicate the results and get them put into our CI setup?

**Comment by elsander** [comment]
Sorry about the late response. I use the py-autopep8 package in emacs. Sorry to hear that it's not passing flake8 even with the changes... my guess would be that the emacs linter misses some things (I have noticed that it doesn't always fix line length issues and unnecessary imports). I can comb over it more thoroughly with flake8 if you want.

**Comment by jpcampb2** [comment]
I've gone forward with resolving the extant conflicts and merging this PR, figuring some linting is better than none and we wanted to get your PR in rather than lingering indefinitely. You've definitely gotten us onto a better track, but it looks to me like there are lots of outstanding linting changes that we should probably make. I think that'll be for additional PRs before we merge flake8 into the CI workflow.

**Comment by elsander** [comment]
Sorry about the long delay on this, I got wrapped up in some pre-holiday work stuff. Totally reasonable to merge it in as-is. You might be able to get more of the way there by running `autopep8 --aggressive` on the repo; I realized the reason my linter wasn't picking those up is that the standard python autolinter won't handle line length unless you pass the `aggressive` flag.

**Comment by jpcampb2** [comment]
Thanks for getting it all going--I've also been flooded and wanted to get these things in so we're closer to the right place. That's a good suggestion for getting us closer.

**Pull request merged**
