### PR TITLE
[DOCS] Organize metadata store sidebar category by type of store

### PR DESCRIPTION
**Pull request by NathanFarmer**
Changes proposed in this pull request:
- GREAT-404
- Organize the large number of docs under "Metadata Stores" by type of store

### Definition of Done
- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Review by anthonyburdi — APPROVED** [review]
Makes sense to me!

**Review by anthonyburdi — CHANGES_REQUESTED** [review]
Actually I think this requires a change to sitemap.xml - there should be instructions in the docs readme.

**Comment by NathanFarmer** [comment]
> Actually I think this requires a change to sitemap.xml - there should be instructions in the docs readme.

@anthonyburdi I updated `sitemap.xml`, but I'm not sure if it was necessary since the changes to `sidebars.js` did not include any changes to the underlying urls.

**Review by anthonyburdi — APPROVED** [review]
LGTM!

**Review by Shinnnyshinshin — APPROVED** [review]
Looks great to me as well 🙇🏼

**Review by donaldheppner — APPROVED** [review]

**Pull request merged**
