### PR TITLE
[FEATURE] [Draft] - Add S3SubdirReaderBatchKwargsGenerator

### LINKED ISSUE #2000: [Feature Request] - SubdirReader for S3
**Is your feature request related to a problem? Please describe.**

I found that it is hard to use different backend for GE. For example, when I started development, I use my local filesystem. Once I move to cloud storage(S3), I found that the migration is not simple. I have to change a lot of configuration. There are no sub-directory reader for S3 but only GlobReader.

The file path is coupled with very specific method, especially with checkpoint. Imagine if I started development in local, I would have all my checkpoint hard-coded to local path. If I need to move them to a cloud storage later, there are no easy way to do that. As a result, I always write code to dynamically construct these path instead of using the path.

**Describe the solution you'd like**
I think we can make use of `s3fs` to clean up the configuration. The ideal case is I can simple add some additional configurations to make it works from local to S3. (i.e. endpoint_url, key and secret).

### PR DESCRIPTION
**Pull request by noklam**
Fix: #2000 

Goal:
The object of this PR is to support moving from local -> S3 easily instead of using a whole new reader
Changes proposed in this pull request:
- Use s3fs to add support for SubdirReader for a S3 backend

It may worth combining `S3SubdirReaderBatchKwargsGenerator` and `SubdirReaderBatchKwargsGenerator`, but I want to start with a different file. I find s3fs comes in quite handy instead of using the boto3 client. I can almost directly replace `os.path.xx` with `fs.xx`

An example of my config, you can find how similar are they. I didn't use the Bucket and Prefix convention and using base_directory as it is more consistent with the local filesystem backend.
```
datasources:
  local_ci_v1:
    module_name: great_expectations.datasource
    data_asset_type:
      module_name: great_expectations.dataset
      class_name: PandasDataset
    batch_kwargs_generators:
      subdir_reader:
        class_name: SubdirReaderBatchKwargsGenerator
        base_directory: ..\data/ge-v1/ci-v1
    class_name: PandasDatasource

  s3_ci_v1:
    module_name: great_expectations.datasource
    data_asset_type:
      module_name: great_expectations.dataset
      class_name: PandasDataset
    batch_kwargs_generators:
      subdir_reader:
        boto3_options:
          endpoint_url: http://stp-dscoe27-w10:9000
#        class_name: SubdirReaderBatchKwargsGenerator
        class_name: S3SubdirReaderBatchKwargsGenerator
        base_directory: s3a://ge-v1/ci-v1
    class_name: PandasDatasource
```

### CODE REVIEW

**Review by eugmandel — CHANGES_REQUESTED** [review]
@noklam Could you please add tests for the new batch kwargs generator? Thank you!

**Comment by noklam** [comment]
@eugmandel could you guide me to some relevant tests? I cannot find test against a S3 backend before, not sure how should I set that up.

**Comment by noklam** [comment]
Notes:
Running tests on Window does not work, would fail `test_s3_generator.py` due to spark, I need to set up the environment in Linux machine for local 

> AttributeError: 'AWSResponse' object has no attribute 'raw_headers'

**Comment by noklam** [comment]
This seems due to `s3fs` using `aiobotocore` which does not play well with `moto`. It would be great if anyone have experience using mock with s3fs.
https://github.com/aio-libs/aiobotocore/issues/755

**Comment by eugmandel** [comment]
> @eugmandel could you guide me to some relevant tests? I cannot find test against a S3 backend before, not sure how should I set that up.

@noklam This test can be used as an example, including the mocking of S3: https://github.com/great-expectations/great_expectations/blob/develop/tests/datasource/batch_kwarg_generator/test_s3_generator.py

**Comment by eugmandel** [comment]
> Notes:
> Running tests on Window does not work, would fail `test_s3_generator.py` due to spark, I need to set up the environment in Linux machine for local
> 
> > AttributeError: 'AWSResponse' object has no attribute 'raw_headers'

@noklam Windows tests are currently marked as optional.

**Comment by noklam** [comment]
the cureent test for s3 does not work well with s3fs.

I figure out to use moto in server mode will make it work, it requires extra dependency like flask.

I should be able to write some test within this week.

**Comment by noklam** [comment]
@eugmandel I have added some tests.

**Comment by noklam** [comment]
@eugmandel With the test in place now, could you review the PR?

**Comment by eugmandel** [comment]
@noklam Sorry for the delay - will review by Monday.

**Review by eugmandel — APPROVED** [review]
Thank you, @noklam !

**Comment by noklam** [comment]
you are welcome!

**Pull request merged**
