### PR TITLE
[MAINTENANCE] Adds additional file extensions for Parquet assets

### PR DESCRIPTION
**Pull request by rdodev**
S3 stipulates that Parquet files can have `.parquet`, `.prq` or `.parq` file extensions. We have customers unable to load their data assets because we only support `.parquet` extensions. This PR remedies that. 

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Review by austiezr — APPROVED** [review]
🚀

**Review by talagluck — APPROVED** [review]
LGTM!

**Comment by rdodev** [comment]
@cla-bot verify

**Comment by kyleaton** [comment]
@cla-bot check

**Pull request merged**
