### PR TITLE
[DOCS] Add Cloud onboarding tutorial

### PR DESCRIPTION
**Pull request by elenajdanova**
Changes proposed in this pull request:
- Adds new category in GX docs for Cloud
- Adds Cloud onboarding tutorial

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in GitHub issues or Slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by elenajdanova** [comment]
@Shinnnyshinshin or @Rachel-Reverie the reqs changed a bit for me. Do I get it right that if this doc isn't mentioned in the `sidebars.js`, users won't be able to find it in the nav, but the path for it will still be created and doc hosted? So I can access it by typing path manually in the address bar. (This is what I need)

**Comment by Rachel-Reverie** [comment]
> @Shinnnyshinshin or @Rachel-Reverie the reqs changed a bit for me. Do I get it right that if this doc isn't mentioned in the sidebars.js, users won't be able to find it in the nav, but the path for it will still be created and doc hosted? So I can access it by typing path manually in the address bar. (This is what I need)

That is correct.  Additionally, it won't have the ToC as a left sidebar.  Users may still be able to pull it up with the Algolia search results, however.

**Comment by elenajdanova** [comment]
Thanks, @Rachel-Reverie! We don't have there anything secret so the search shouldn't be a concern

**Review by Shinnnyshinshin — APPROVED** [review]
Looks good on my end, but would it be ok to get one more check from @DrewHoo in case I'm missing any additional needed context?

**Comment by elenajdanova** [comment]
@Shinnnyshinshin he already gave me thumbs up. Before I was able to request a review from him in GitHub

**Pull request merged**
