### PR TITLE
[FEATURE] Add new expectation: expect column values to match powers of a base g…

### PR DESCRIPTION
**Pull request by rifatKomodoDragon**
…iven that the base is a positive Integer.

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by rdodev** [comment]
Hey @rifatKomodoDragon, thanks for PR.

@austiezr this LGTM, but if you have a chance, take a gander, pls.

**Review by austiezr — CHANGES_REQUESTED** [review]
Hey @rifatKomodoDragon ! Thanks for this submission; it looks like we need a linting pass with `black` and `isort`. Once that's done, we're good to go! 🚀

**Comment by austiezr** [comment]
Check out our [linting guidance here](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style#linting) for some more detail.

**Comment by rifatKomodoDragon** [comment]
> 

done sir!

**Comment by rdodev** [comment]
@rifatKomodoDragon thanks for this work.

**Review by austiezr — APPROVED** [review]
LGTM! Thanks @rifatKomodoDragon ! 🚀

**Pull request merged**
