### PR TITLE
[ENHANCEMENT] Data Docs now displays row and column count in the more info section of Validation Result pages

### PR DESCRIPTION
**Pull request by Aylr**
## Background

> Hey when I look at these nice shiny data docs pages I have no idea how big the data sets were that were validated! Was it a tiny sample file that got ingested, or was it the entire prod table?

## Changes proposed in this pull request:

[ENHANCEMENT] Data Docs now displays row count and column count in the more info section of Validation Result pages

## Previous Design Review notes:
- client request

## Screenshot
 
Data_documentation_compiled_by_Great_Expectations

### CODE REVIEW

**Comment by jcampbell** [comment]
I love the inclusion of this information in the data docs! I think we need to draw it from the EVRs, however (as with other data elements). That way the batch metadata doesn't presuppose the computation of specific metrics.

Instead of adding a property to the batch, what about populating the number of columns from the observed value of expect columns to match ordered list?

**Comment by Aylr** [comment]
The proposed solution relies on no specific expectations which for my use case are counter productive since data size varies so widely.

**Comment by Aylr** [comment]
Furthermore this implementation presupposes nothing about the expectations, and has precedent since it is metadata about the batch, just like batch_kwargs, parameters, markers, etc.

**Comment by spbail** [comment]
> I love the inclusion of this information in the data docs! I think we need to draw it from the EVRs, however (as with other data elements). That way the batch metadata doesn't presuppose the computation of specific metrics.
> 
> Instead of adding a property to the batch, what about populating the number of columns from the observed value of expect columns to match ordered list?

I actually think that since these are properties of the batch, they should come from the batch rather than pulling it from some expectation which may not even exist... the current implementation seems pretty clean to me?

**Comment by jcampbell** [comment]
I think we're just getting very into the weeds of what a batch is, so to clarify the intent, especially in the 0.13 conception:

```
A **Batch** is reference to a collection of data, an Execution Engine, and metadata. The Batch is a fundamental building block for accessing data using Great Expectations, but is not the data itself. Instantiating a Batch does not necessarily "fetch" the data by immediately running a query or pulling data into memory. Instead, think of a Batch as a cache that includes the information that you will need to fetch the right data when it’s time to validate.
```

While the `dataset` classes do provide `get_column_count` as pieces of metadata (because they inspect schemas) that will change in 0.13, because a batch does not have to be a single tabular structure like a dataset does -- it could have multiple tables (so you can compare row counts between tables, for example).

More to the point -- the "column_count" is ambiguous in spark, since the result of get_column_count does not include nested columns, even though they are accessible in other metrics (including column map/aggregate expectations).

With `get_row_count` it *is* a metric...it triggers a count query in sqlalchemy and spark (not in pandas because shape is indeed a native property of a pandas dataframe); that query is available from almost any EVR, hence my thinking that this should be populated in the EVR.

I think it's totally reasonable to expose this data, I'd just rather include it in the EVR (even in the meta section) instead of the batch definition, and draw from EVRs to populate it.

**Comment by Aylr** [comment]
Closing obsolete.

**Pull request closed without merging**
