### PR TITLE
[ENHANCEMENT] Enhance data doc to show data asset name in overview block

### PR DESCRIPTION
**Pull request by noklam**
Description: 
* To add data asset name in the "Overview" block, previously only available when click "show more info"
image

Related issue #1804

### CODE REVIEW

**Comment by noklam** [comment]
@cla_bot check

**Comment by noklam** [comment]
@ge-cla-bot check

**Comment by noklam** [comment]
@cla-bot check

**Review by eugmandel — APPROVED** [review]
@noklam Thank you for making this change! Displaying the data asset above the fold is much more helpful.

**Comment by noklam** [comment]
great. :)

**Comment by noklam** [comment]
@eugmandel I am participating in hacktoberfest. Could you add a #hacktoberfest-accepted label to this PR?

**Pull request merged**
