### PR TITLE
Don't install tests and examples as packages

### PR DESCRIPTION
**Pull request by tsanikgr**
## Changes proposed in this pull request:
- Fix the `exclude` argument of `find_packages` in `setup.py`, so that it properly excludes the `tests` and `examples` when installing `great_expectations` as a Python package.

### Before the change:

```
 /tmp ~ pip uninstall great_expectations
Found existing installation: great-expectations 0.10.4
Uninstalling great-expectations-0.10.4:
  Would remove:
    /Users/ntsaou/anaconda/envs/ge/bin/great_expectations
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/examples/integrations/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/great_expectations-0.10.4.dist-info/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/great_expectations/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/actions/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/cli/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/core/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/data_asset/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/data_context/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/dataset/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/datasource/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/integration/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/jupyter_ux/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/profile/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/render/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/test_dataset_implementations/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/test_definitions/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/tests/test_plugins/*
Proceed (y/n)?
```

### After the proposed change:
```
 /tmp/great_expectations ~ pip uninstall great_expectations
Found existing installation: great-expectations 0.10.4+17.gdaa2c9ff
Uninstalling great-expectations-0.10.4+17.gdaa2c9ff:
  Would remove:
    /Users/ntsaou/anaconda/envs/ge/bin/great_expectations
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/great_expectations-0.10.4+17.gdaa2c9ff.dist-info/*
    /Users/ntsaou/anaconda/envs/ge/lib/python3.7/site-packages/great_expectations/*
Proceed (y/n)?
```

### CODE REVIEW

**Comment by tsanikgr** [comment]
@cla-bot check

**Comment by tsanikgr** [comment]
@cla-bot check

**Comment by tsanikgr** [comment]
@kyleaton I did sign the CLA (twice), but still receiving this error. Could you please look into it? Thanks!

**Comment by tsanikgr** [comment]
@cla-bot check

**Comment by tsanikgr** [comment]
How can the coverage be less?? 🤔

**Review by jcampbell — APPROVED** [review]
Thank you!

**Pull request merged**
