### PR TITLE
Initial setup for Airflow plugin

### PR DESCRIPTION
**Pull request by bouke-nederstigt**
Mockup of airflow plugin. Definitely needs some works / comments

- Added new module containing airflow plugin - this should be copied into $AIRFLOW_HOME/plugins to use it in airflow
- Adds basic operator that takes a local or aws s3 csv dataset  as input, and validates it using a local expectations json file
- Add test to show how this would be used. Test is failing because it requires airflow to be setup

### CODE REVIEW

**Comment by jpcampb2** [comment]
Firstly--awesome! This is great to provide such a clear example for folks right in the repo.

I haven't gotten to read through this closely yet, but a quick thought on the currently-broken test: could you switch the addition of the airflow dependency from `requirements.txt` to `requirements-dev.txt`? The testing happens against those requirements, so you'll need it there (and not necessarily in requirements) to see whether the tests are working.

**Comment by jpcampb2** [comment]
It looks to me like the test (since it uses both the s3 hook and the mysqlhook) would need to have the mysql sub-dependency also installed (apache-airflow[s3,mysql] in requirements-dev). But that would then require mysql on travis too (which may be possible...) Is there a lighter-weight sql plugin for testing airflow (like sqllite in memory, which is how we're testing the sqlalchemy connector right now?)

**Comment by abegong** [comment]
This would be a great use case for docker. I plan to implement a similar pattern in Spark in the next ~2 weeks.

**Comment by bouke-nederstigt** [comment]
Yeah, I agree the test shouldn't use MySQL. However, as you can see from the file I marked the test to be skipped anyway. The reason being that in order to run the test requires the airflow database to set up (whether the operator actually uses MySQL or not). I don't think this should be implemented at all, I just added the test as a usage example. 

The problem as I currently see it is that in order for the hooks to be instantiated you need to specify the type of hook (The generic DbApiHook cannot be instantiated). I haven't come up with a way to change this at runtime (yet), but I'll think about it a bit more. For now it might be easiest to just remove the test altogether, and use this just as a usage example.

@abegong What do you mean with the Docker use case specifically?

**Comment by jpcampb2** [comment]
Understood, @bouke-nederstigt . @abegong was planning to set up a docker-based backend for mocking relevant services during testing (e.g. spark), which might be a good way to make the airflow db available during testing of the relevant portions of the integration code.

For now, what about moving the new code into examples/integrations/airflow instead of great_expectations_airflow, since the code in examples is not expected to be under test?

**Comment by jpcampb2** [comment]
Let's merge this in--I think it's a great resource, and once we refine the method for testing, we can move it into a live/supported "integrations" area of the repo with tests.

**Review by jpcampb2 — APPROVED** [review]

**Pull request merged**
