### PR TITLE
Fix datasource delete cli help text and refactor

### PR DESCRIPTION
**Pull request by mzjp2**
Changes proposed in this pull request:
- Refactor the `delete_datasource` command to make it simpler
- Fixed the help text for `-d directory` following https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1588687575382100
- Changed the way of specifying the datasource as an argument instead of option, which feels more natural to me: `great_expectations datasource delete my_datasource` instead of `-s my_datasource`, but happy to change it if you prefer. Can also trivially make it take as many datasource names as you want by making `nargs=-1` and using a for loop.

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For nontrivial changes, we will conduct both a design review and a code review. Please tag a core team member for code review, or leave blank and we will find someone for you!

- [ ] Design Review (@jcampbell)
- [x] Code Review

Thank you for submitting!

### CODE REVIEW

**Comment by mzjp2** [comment]
Tagging @jcampbell @Aylr for a review :)

**Review by Aylr — CHANGES_REQUESTED** [review]
Would you please add a single line in the changelog describing this change?

**Comment by mzjp2** [comment]
> Would you please add a single line in the changelog describing this change?

Updated the changelog with this change and the previous one I forgot to update, thank you! 😅

**Review by Aylr — APPROVED** [review]
Wonderful work!

**Pull request merged**
