### PR TITLE
[BUGFIX] fixed a bug where expectation metadata doesn't appear in edit template for table-level expectations

### PR DESCRIPTION
**Pull request by olechiw**
Addresses https://github.com/great-expectations/great_expectations/issues/2692

There was a slight variation in the changed file and this one https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/render/notebook_assets/suite_edit/column_expectation.py.j2 

I assume these are separate in the name of flexibility later? One might also make the case they should be the same template

Changes proposed in this pull request:
- Show table-level metadata in `great_expectations suite edit` notebook

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by olechiw** [comment]
@cla-bot check

**Comment by olechiw** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by talagluck** [comment]
Thanks for this contribution, @olechiw, and apologies for delays! We will review and be in touch in the next few days.

**Review by austiezr — APPROVED** [review]
LGTM! Thank you for contributing!

**Pull request merged**
