### PR TITLE
Fix docstring of `get_expectations_config`

### PR DESCRIPTION
**Pull request by sotte**
Docstring format of get_expectations_config was wrong.

image

Fixed now.

### CODE REVIEW

**Comment by sotte** [comment]
I don't think the build error is due to my changes.

**Review by jpcampb2 — APPROVED** [review]
LGTM

**Comment by jpcampb2** [comment]
You're right--it was one of the build jobs for a specific configuration that failed in travis (it randomly timed out--not a code test failure). I've just rebuilt and will merge the PR. Thank you!

**Comment by sotte** [comment]
Thank you!

**Pull request merged**
