### PR TITLE
Change intro.rst to be rebuilt using pypandoc (#256)

### PR DESCRIPTION
**Pull request by jpcampb2**

### CODE REVIEW

**Comment by abegong** [comment]
Is there a way to test this besides approving and merging?

Also, I noticed this morning that the links in Glossary are also broken...

**Comment by jpcampb2** [comment]
I tested it by setting this branch as active in readthedocs and viewing them there (and it works--double check!). (You should also be able to check by building locally)

Good to know re: glossary...I can do that later, but having to step away now...

**Review by abegong — APPROVED** [review]
Go, go, go!

**Review by abegong — APPROVED** [review]
:+1:

**Pull request merged**
