### PR TITLE
[DOCS] edit term(data_conext, checkpoints)-link in with airflow

### PR DESCRIPTION
**Pull request by jx2lee**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], or [CONTRIB]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- edit term's link in `with airflow` document

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Comment by jx2lee** [comment]
@cla-bot check

**Comment by jx2lee** [comment]
@cla-bot check

**Comment by jx2lee** [comment]
@anthonyburdi 🙏🏼

**Review by Shinnnyshinshin — APPROVED** [review]
LGTM. Thank you for the contribution @jx2lee

**Pull request merged**
