### PR TITLE
technical term data asset

### PR DESCRIPTION
**Pull request by Rachel-Reverie**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Updates the Data Asset technical term page that was created in abbreviated form for a community meetup demo, bringing it up to the standards for a full technical term page.

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

### Definition of Done
Please delete options that are not relevant.

- [X] I have made corresponding changes to the documentation

Thank you for submitting!

### CODE REVIEW

**Review by anthonyburdi — APPROVED** [review]
LGTM!

**Review by jcampbell — COMMENTED** [review]
@Rachel-Reverie I really like this. I'd like to include the specific verbiage of "Reference", "Event" and "Ticket" data in the section on versatility--that represents an update to the language currently there.

**Comment by Rachel-Reverie** [comment]
> 

@jcampbell Can you provide some further detail on that, or link me to somewhere where those terms are defined?  I didn't come across them when I was compiling this doc, and I'm not familiar with the conversations where they've been coming up.  Thanks!

**Comment by Rachel-Reverie** [comment]
@jcambell I've added a ticket to update the verbage and add images based on the lucid diagram you shared, but I'm going to go ahead and merge the current content now so that the whole universal-map-update branch can be prepped to merge into develop.

**Pull request merged**
