### PR TITLE
[BUGFIX] allow reader_options in the CLI so can read `.csv.gz` files

### LINKED ISSUE #2694: Bug: Creating suites from `.csv.gz` files on S3
**Describe the bug**
When creating a suite on S3 using `.csv.gz` files the `read_options` aren't passed to the `batch_kwargs`.  So the `datasource` doesn't know it should try to decompress the file.  This is using `v2` of the CLI.

**To Reproduce**
1. Have a `.csv.gz` on S3
2. Try to scaffold a suite on the CLI

Screenshot 2021-04-19 at 16 25 24

**Expected behavior**
Great Expectations to detect the read options needed, as it does in other contexts, and use these

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.17

**Additional context**
I'll submit a PR to fix this

### PR DESCRIPTION
**Pull request by luke321321**
Changes proposed in this pull request:
- Enable `reader_options` to be passed to the CLI (v012) when creating a new suite.  This allows `.csv.gz` files to be used when creating a new suite.  This was a bug for creating suites with compressed files on S3.

Closes #2694

### CODE REVIEW

**Comment by eugmandel** [comment]
@luke321321 Thank you for this enhancement - we will review and respond.

**Comment by luke321321** [comment]
@eugmandel I know you'll be super busy but is there a chance of getting this reviewed?  For my team a good chunk of our use case is `csv.gz` files and this is blocking rollout across our company.  We use the CLI to interact with GE more than python code as it's more stable & a good percentage of our data scientists are more comfortable in R than Python (😱 ).  Thanks

**Review by talagluck — APPROVED** [review]
Hi @luke321321 - I'm so sorry for the delay. We are starting to expand our DevRel team in earnest, so response times for PRs will be better moving forward.

Thank you so much for this contribution - this looks great! Would you mind just resolving conflicts with the changelog? Then we can get this merged in ASAP

Do you happen to know if this is an issue with the V3 API?

Thanks again!

**Comment by lukedyer-peak** [comment]
@talagluck I've fixed the doc merge conflict.
This issue only happens for v2 of the CLI as the v3 backend is vastly different here.

**Pull request merged**
