### PR TITLE
[ENHANCEMENT] expect_table_columns_to_match_set

### PR DESCRIPTION
**Pull request by anthonyburdi**
Changes proposed in this pull request:
- Add a new expectation called expect_table_columns_to_match_set. Closes issue #1890

### CODE REVIEW

**Review by abegong — CHANGES_REQUESTED** [review]
This also looks good.

One change:  It doesn't look like we test the logic for contents of the `result` object anywhere. I bet you can get there just by turning `exact_match=True` and then filling in `result` objects for a few examples in `tests/test_definitions/other_expectations/expect_table_columns_to_match_set_test_set.json`

**Comment by anthonyburdi** [comment]
> This also looks good.
> 
> One change: It doesn't look like we test the logic for contents of the `result` object anywhere. I bet you can get there just by turning `exact_match=True` and then filling in `result` objects for a few examples in `tests/test_definitions/other_expectations/expect_table_columns_to_match_set_test_set.json`

Thanks for the review @abegong! I added some additional tests, and fixed some of the failing tests. Ready for re-review if all CI tests pass 🤞  One concerning item is that items in the "details" key of the result do not affect whether the tests pass or not. I will add a separate issue for this.

For example this one should fail since there should be something in the "mismatched" dictionary:
```
{
      "title": "Negative test: column is missing, exact_match=True",
      "exact_match_out": true,
      "in":{
        "column_set": ["c1", "c2"],
        "exact_match": true
      },
      "out":{
        "success":false,
        "result": {
          "observed_value": ["c1", "c2", "c3"],
          "details": {"mismatched": {}}
        }
      }
    }
```

This test should also fail because the "mismatched" dict should be empty and isn't:
```
{
      "title": "Positive test: Columns are right, but ordering wrong, exact_match=True",
      "exact_match_out": true,
      "in":{
        "column_set": ["c3", "c2", "c1"],
      "exact_match": true
      },
      "out":{
        "success":true,
        "result": {
          "observed_value": ["c1", "c2", "c3"],
          "details": {
            "mismatched": {
              "unexpected": ["c1"]
            }
          }
        }
      }
    }
```

**Comment by anthonyburdi** [comment]
See also new issue #1919 related to my previous comment.

**Comment by abegong** [comment]
To clarify:
1. There are now some tests where `exact_match = True`.
2. These tests are all correct, and would provide good coverage of the Expectation.
3. ...Except they don't actually execute correctly, because of an execution bug around `exact_match`.

Is that right?

**Comment by anthonyburdi** [comment]
> To clarify:
> 
> 1. There are now some tests where `exact_match = True`.
> 2. These tests are all correct, and would provide good coverage of the Expectation.
> 3. ...Except they don't actually execute correctly, because of an execution bug around `exact_match`.
> 
> Is that right?

That is almost exactly right! (One minor pedantic correction: the execution bug is around `exact_match_out` - `exact_match` is a parameter of the new expectation) Thanks for clarifying. I was proposing we separate the workstreams - merge this PR and pick up the `exact_match_out` handling bug separately in issue #1919 so it can be triaged against other tasks in the queue.

**Comment by abegong** [comment]
Yes, agreed.

**Review by abegong — APPROVED** [review]

**Pull request merged**
