### PR TITLE
[Draft - Enhancement] - enable using Minio for S3 backend

### PR DESCRIPTION
**Pull request by noklam**
Minio is a S3 API Compatible storage, to use it, we need to add an endpoint_url instead of the default s3 URL. So far I am able to run a checkpoint by adding endpoint_url argument.

We probably need to have some test(not sure what is the easiest way to do that, would love to have some help)

Related issue #1692 
image
image

### CODE REVIEW

**Comment by noklam** [comment]
The boto3_options in `pandas_datasource` seems  redundant which store it own boto3_options. i cannot find a way to correctly pass the boto3_options to a PandasDataSource.

**Review by eugmandel — APPROVED** [review]
@noklam The changes look good to me. Our automated tests pass. I cannot test with Minio itself, but this is good to merge. Thank you!

**Comment by noklam** [comment]
```
docker run -p 9000:9000 -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" minio/minio server /data
```
This would be the easiest way to setup a minio server locally.

**Comment by abegong** [comment]
I you're interested, you could include the relevant Docker file in `assets/docker/` and then add some light tests of the integration.

**Comment by noklam** [comment]
@eugmandel I am partivipating in hacktoberfest. Could you add a #hacktoberfest-accepted label to this PR?

**Pull request merged**
