### PR TITLE
[DOCS] updated the channel name

### PR DESCRIPTION
**Pull request by jntushar**
`#contributors-contributing` channel does not exist on slack anymore or not public. Contributors may use `#introductions` channel for introduction.

### CODE REVIEW

**Comment by jntushar** [comment]
> @cla-bot check

@cla-bot check

**Review by kenwade4 — APPROVED** [review]

**Comment by austiezr** [comment]
Hey @jntushar! Thanks for raising this; I'm actually still seeing #contributors-contributing as an active public channel. Are you able to confirm that [this link](https://greatexpectationstalk.slack.com/archives/CV828B2UX) doesn't take you to the channel?

**Comment by jntushar** [comment]
> Hey @jntushar! Thanks for raising this; I'm actually still seeing #contributors-contributing as an active public channel. Are you able to confirm that [this link](https://greatexpectationstalk.slack.com/archives/CV828B2UX) doesn't take you to the channel?

Hi @austiezr! Thanks for sharing the link. I guess to join this channel we have to specifically search for it. That's why it has only 346 members.

**Comment by austiezr** [comment]
Got it! I'll make sure to call the channel out in our `how to slack with us` messaging. Closing this out for now; thanks @jntushar !

**Pull request closed without merging**
