### PR TITLE
Correct example code variable assignment

### PR DESCRIPTION
**Pull request by DanielOliver**

### CODE REVIEW

**Review by jcampbell — APPROVED** [review]
Thank you!

**Comment by jcampbell** [comment]
Thanks @DanielOliver! I'm very much hoping I will one day stop basic mistakes when writing documentation. ;)

Would you be willing to sign the CLA? It's a standard adaptation of the Apache version; there are two options depending on whether you're contributing as an individual or on behalf of an employer:

- [Individual Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSdA-aWKQ15yBzp8wKcFPpuxIyGwohGU1Hx-6Pa4hfaEbbb3fg/viewform?usp=sf_link)
- [Software Grant and Corporate Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSf3RZ_ZRWOdymT8OnTxRh5FeIadfANLWUrhaSHadg_E20zBAQ/viewform?usp=sf_link)

**Comment by DanielOliver** [comment]
I'm fairly sure I signed it right after cla-bot popped up there, but the check hasn't refreshed.  I would push another commit to try to force a refresh, but I haven't spotted anything else that'd fit the description of this PR.

**Comment by jcampbell** [comment]
@clabot check

**Comment by jcampbell** [comment]
@cla-bot check

**Comment by jcampbell** [comment]
Thank you! Verified and asked cla-bot to recheck!

**Pull request merged**
