### PR TITLE
[ENHANCEMENT] New Expectation: Expect value at index to be equal for each column element

### PR DESCRIPTION
**Pull request by YaosenLin**
expect_value_at_index_to_be_equal(column, value, index)

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

### CODE REVIEW

**Review by talagluck — APPROVED** [review]
This is awesome! I updated the metric function so that it will return False for non-strings instead of erroring. I also added a docstring for the metric, and a couple of additional test cases.

**Comment by talagluck** [comment]
@YaosenLin, it looks like we still need a CLA signature from you, and once you sign, we'll be able to merge this in.

**Comment by talagluck** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Pull request merged**
