### PR TITLE
[BUGFIX] Don't reset_index for conditional expectations

### LINKED ISSUE #3666: Wrong index returned because _apply_row_condition uses DataFrame.reset_index(drop=True)
**Describe the bug**
When an expectation uses row_condition with the pandas parser, the wrong index is included in the expectation results json because PandasDataset._apply_row_condition uses DataFrame.reset_index(drop=True).

**To Reproduce**
1. Run the below code
2. Note that the incorrect output is returned when using row_condition (as this causes reset_index to run)
3. Comment out the two lines that are mentioned
4. Note that the correct output is returned when not using row_condition (as this reset_index does not run)
5. UN-Comment the two lines that are mentioned
6. Comment out `.reset_index(drop=True)` in great_expectations/dataset/pandas_dataset.py:PandasDataset._apply_row_condition 
7. Note that the correct output is returned when not using row_condition (as this reset_index does not run)

**Expected behavior**
The correct index of the bad values is returned.

**Environment (please complete the following information):**
 - Operating System: Linux & MacOS
 - Great Expectations Version: [e.g. 0.13.41]

**Additional context**
I depend on using the unexpected_index_list to drop "unexpected" rows from the dataframe that do not meet critical expectations.
Note: I would be happy to make this change. I have setup my development environment and made this change locally but just need help in understanding where tests need to be updated.

```
import great_expectations as ge
from great_expectations.data_context.types.base import DataContextConfig, DatasourceConfig, FilesystemStoreBackendDefaults
from great_expectations.data_context import BaseDataContext
import numpy as np
import pandas as pd
import os

data = {'VARIABLE_NAME': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', ],
        'VALUE': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, ]}

df = pd.DataFrame(data)

abs_path = os.getcwd() + '/great_expectations'
domain_name = 'test'

data_context_config = DataContextConfig(
    datasources={
        "my_pandas_datasource": DatasourceConfig(
            class_name="PandasDatasource",
        )
    },
    store_backend_defaults=FilesystemStoreBackendDefaults(root_directory=abs_path),
)

context = BaseDataContext(project_config=data_context_config)

suite = context.create_expectation_suite(domain_name, overwrite_existing=True)

batch_kwargs = {
    "datasource": 'my_pandas_datasource',
    "dataset": df,
    "data_asset_name": domain_name,
}

batch = context.get_batch(batch_kwargs, "test")

print(batch)

batch.expect_column_values_to_be_between(
    column="VALUE", min_value=1, max_value=4,   # All values should fall outside this range
    row_condition='VARIABLE_NAME == "B"',       # All of B's value are > 5
    condition_parser='pandas',
    # Note that if we were to comment out the above two lines that trigger DataFrame.query
    # We would get the correct return set
    # This is because after we run query we run DataFrame.reset_index(drop=True)
    result_format={'result_format': 'COMPLETE'},
)
results = batch.validate()


index_list_unexpected = []
failed_results = [result for result in results['results'] if result['success'] is False]

for result in failed_results:
    rf = result['expectation_config']['kwargs'].get('result_format')
    if isinstance(rf, dict) and rf['result_format'] == "COMPLETE":
        unexpected_list = result['result'].get('unexpected_list')
        unexpected_index_list = result['result'].get('unexpected_index_list')
        index_list_unexpected += unexpected_index_list

print('index_list_unexpected:', index_list_unexpected)
print('unexpected_list:', unexpected_list)

print('This dataframe should have VARIABLE_NAME B rows 5-9 of values 5-9.')
print(df.loc[index_list_unexpected, :])
print('Instead it has VARIABLE_NAME A rows 0-4 of values 0-4... which were in our range.')


with open('validation_results.json', 'w') as f:
    f.write(str(results))
```

### PR DESCRIPTION
**Pull request by abekfenn**
Ticket Number: fixes #3666

Problem:

- When an expectation uses row_condition with the pandas parser, the wrong index is included in the expectation results json because PandasDataset._apply_row_condition uses DataFrame.reset_index(drop=True).

Solution:

- Stop running reset_index on the DataFrame

Notes: **_Please let me know where additional changes and/or new/updated tests are required_**

Changes proposed in this pull request:
- Stop using reset_index on DataFrames that are queried using DataFrame.query for conditional expectations

Alternative proposal: 
- reset_index is made an argument that one can pass when setting up an expectation

Previous Design Review notes:
- N/A

### Definition of Done
Please delete options that are not relevant.

- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Comment by talagluck** [comment]
Thanks so much for the contribution, @abekfenn! We're going to discuss internally and be in touch soon.

**Comment by talagluck** [comment]
Hi @abekfenn - we've spent some time debating this internally. The two sides are basically:
1. When you use `row_condition`, you are creating a new "domain" or a new slice of data, and so it makes sense to reset the index.
2. When you use `row_condition`, you are filtering an existing domain, and so it does not make sense to reset the index.

Could you tell us a bit more about your use-case here? Is it absolutely vital for you that we not reset the index here, or is it more about convenience?

**Comment by aidanfennessy** [comment]
Hi @talagluck thanks for getting back to me and for creating the space for feedback to help drive this decision.

For my use case, this functionality is essential. I am parsing unexpected_index_list from the validation results and using it to drop rows where expectations failed with a certain severity that I have encoded in the meta argument. 

Therefore, if unexpected_index_list does not represent the actual index of the values that failed to meet expectations, row_condition becomes useless to me and I lose a fair bit of power in writing my expectations. 

Ultimately, when using row_condition I care about filtering the dataframe/table to enable me to apply different expectations depending on the query criteria.
My dataset is "unpivoted" and so I need to adjust my expectations depending on the row value of another column in the dataframe. If it would help to provide an example, let me know.

While I agree that resetting the index of the data might make theoretical sense when slicing the data, is there a benefit to doing this? From my perspective, this approach is incongruent with the functionality of complete result_format/unexpected_index_list elsewhere in the API. In fact, this is the only place I see the use of Df.reset_index().

To me, there is a lot of value in having the index of unexpected values, and being able to use row-condition, and therefore, not having this functionality would reduce GE's usefulness significantly.

**Comment by talagluck** [comment]
Hi @aidanfennessy - thanks for this context. After some internal discussion, we agree that your use case makes sense. We just need to determine the right way to incorporate this to ensure that it is not a breaking change, so I will be in touch about that. In the meantime, I opened up a PR into your branch which mirrors your V2 functionality in V3, and resolves a few additional tests. Please take a look and let me know if you have any questions.

**Comment by abekfenn** [comment]
Glad to hear, thank you @talagluck. Reviewed your changes and they look good to me.

Happy to discuss how we can avoid this becoming a breaking change whenever you all are ready.

**Comment by talagluck** [comment]
Hi @abekfenn! OK - after some internal discussion, we've come to the determination that this isn't quite a breaking change, so should be good to merge given a descriptive changelog entry. Something like “ conditional expectations no longer use .reset_index so unexpected_index_list in the expectation results now reports the correct index”. Once you make that update, we should be all set to approve and merge. Thanks for your patience here!

**Comment by abekfenn** [comment]
Updates to the changelog made, thanks for the assist @talagluck!

**Review by talagluck — APPROVED** [review]
LGTM - thanks for the contribution, @abekfenn!

**Pull request merged**
