### PR TITLE
[BUGFIX] Ensure that Jupyter Notebook cells convert JSON strings to Python-compliant syntax

### PR DESCRIPTION
**Pull request by cdkini**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- https://github.com/great-expectations/great_expectations/issues/3894
- This fix aligns with our current solution but will need to be part of a larger conversation around serialization between JSON and Python (specifically in the context of notebooks)

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Review by talagluck — COMMENTED** [review]
This looks great! I just want to confirm, are we sure that `BaseNotebookRenderer` isn't publicly used? It's probably not super common, but I wouldn't be surprised if a few teams might use it for custom rendering, and so changing the definition might break things. If this is only being released as part of 0.14, it might be OK, but I figured I'd check.

**Comment by cdkini** [comment]
@talagluck great question! I already impacted that signature when I fixed the `null` problem (not realizing that this was something we considered part of our public API).

How should we progress here? We provide default values for the new args so I think they'd still work with old version (but probably not ideal).

**Comment by talagluck** [comment]
Ah I missed that last time! Maybe add back in the previous parameter (`sanitize_nulls`) with a Deprecation Warning if a non-default value is specified? Would that make sense?

**Comment by cdkini** [comment]
I'm not confident to be honest! I'll think it over and maybe we can quickly connect tomorrow to determine next steps

**Review by talagluck — APPROVED** [review]
LGTM! Based on discussion, and the fact that the signature has changed relatively recently, and that we aren't specifically aware of anyone using this as a public method, it's fine to change the signature at this time.

**Pull request merged**
