### PR TITLE
return a list for partial_exception_counts

### PR DESCRIPTION
**Pull request by mgasner**
addresses https://github.com/great-expectations/great_expectations/issues/181

### CODE REVIEW

**Comment by abegong** [comment]
I believe the problem is that the item ordering in `partial_exception_counts` isn't guaranteed across ties. Since "Downton" and "Seman" each occur once, they can show up in any order.

**Comment by jpcampb2** [comment]
@mgasner This makes sense, but because it triggers a change in the `partial_exception_count` we'll need to update the documentation around it as well. Since we're doing a significant rewrite on the output_format documentation, no need to comprehensively change that, but can you ensure any other relevant docs are updated, and add a simple note in the output_format documentation re: the change to the exception (soon to be "unexpected" counts)

**Comment by abegong** [comment]
@jpcampb2 , I can clean up the docs for this. I'd propose that we (1) merge this PR, and (2) open a new issue to fix the docs AFTER the other big doc change.

Then we can resolve the big doc change first and come back to any remaining edits for `partial_exception_count` later.

**Comment by jpcampb2** [comment]
Agreed, and sorry for the long delays. Considering your comment as a review, and merging.

**Pull request merged**
