### PR TITLE
[FEATURE] Add experimental expectations/metrics  for XML, EDTF, and language

### PR DESCRIPTION
**Pull request by mielvds**
Adds expectations and metrics that are common in a GLAM (Galleries, Libraries, Archives, Museums) context, but also beyond.

### CODE REVIEW

**Comment by spbail** [comment]
Thanks for the contribution, this is SUPER exciting! We'll review and merge asap.

**Comment by eugmandel** [comment]
@mielvds These expectations are amazing! As far as I know, you were the first community contributor who figured out how to use the new Modular Expectations API to author new Expectations, before we had documentation!

Recently we improved the process for submitting and releasing community-contributed Expectations:
1. We introduced a self-diagnostic tool that makes it faster to develop Expectations
2. We added an automated release process for Expectations in contrib directory
3. We added a how-to guide: 
https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_contribute_a_new_expectation_to_great_expectations.html

I have a few comments for taking advantage of these improvements:

* The expectations are in glam_expectations subdir. if you move them to great_expectations_experimental, they will be automatically released as part of a new pypi package https://pypi.org/project/great-expectations-experimental/
* Examples/tests should be included in the file that has the Expectation implementation (instead of separate JSON files) - see the guide
* Add library metadata - see the guide
* We encourage to put the MetricProvider implementations in the same file as the Expectations.

**Comment by mielvds** [comment]
> @mielvds These expectations are amazing! As far as I know, you were the first community contributor who figured out how to use the new Modular Expectations API to author new Expectations, before we had documentation!

To be fair, most of them were small deviations from existing implementations from your side ;) I'm not sure I fully understand, but I'm getting there. 

> We added a how-to guide:
https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_and_editing_expectations/how_to_contribute_a_new_expectation_to_great_expectations.html

Ok, didn't see that one. Much clearer! A suggestion: split of the contribution docs from the usage docs. The TOC is getting a bit bloated and it's hard to know where to look. Also, it is often not clear wether a page is about < 0.13 or 0.13+. 

>     * The expectations are in glam_expectations subdir. if you move them to great_expectations_experimental, they will be automatically released as part of a new pypi package https://pypi.org/project/great-expectations-experimental/

Ah this wasn't clear to me. I thought every folder in the contrib/experimental package would be released as a separate package (how else would you distinguish different implementations of the same expectation?)

TBH, this `/contrib`  approach feels a bit awkward. It would be much cleaner if I could manage my implementations in a separate repo as an independent package. Also, how do you deal with author attribution and IP? (not that this is a big concern to me, but I like clarity on these things). 
> 
>     * Examples/tests should be included in the file that has the Expectation implementation (instead of separate JSON files) - see the guide

Great! It wasn't clear in previous guides and I was hoping this PR would answer that. The tests are empty files anyway.

> 
>     * Add library metadata - see the guide

Ok, that answers my atrribution question. A github handle is quite limited though. Most of the contributions I do are indirectly funded by the organisation I work for, but I can't mention my affiliation.

> 
>     * We encourage to put the MetricProvider implementations in the same file as the Expectations.

Sure, np. But that contradicts your own folder structure, no?

**Comment by spbail** [comment]
Hi Miel,
thanks for making the changes and for the feedback on the guide! Some comments inline:

> To be fair, most of them were small deviations from existing implementations from your side ;) I'm not sure I fully understand, but I'm getting there.

For context, we recently ran a few community hackathons to contribute Expectations, and a lot of these changes came out of the need to simplify the structure a little so contributors didn't have to juggle too many different files, and could have a quick devloop of write/test.

> Ok, didn't see that one. Much clearer! A suggestion: split of the contribution docs from the usage docs. The TOC is getting a bit bloated and it's hard to know where to look. Also, it is often not clear wether a page is about < 0.13 or 0.13+.
> 

Yup, that's definitely on our to do list to split these up, we just need to make sure there aren't too many broken links. The <0.13/0.13+ distinction is a good point for pages that are only aimed at one of the two, the others have tabs for the different API versions. I'll see if there's a way we can distinguish them better. 

> Ah this wasn't clear to me. I thought every folder in the contrib/experimental package would be released as a separate package (how else would you distinguish different implementations of the same expectation?)

FWIW I'm actually surprised by that too, I think your suggestion makes sense.

> TBH, this `/contrib` approach feels a bit awkward. It would be much cleaner if I could manage my implementations in a separate repo as an independent package. Also, how do you deal with author attribution and IP? (not that this is a big concern to me, but I like clarity on these things).

Good point - I think this depends a little on the use case and user? I can see someone wanting to just contribute a simple expectation straight in the main repo and not worrying about releases and maintenance etc, whereas others might want to manage a separate package. For now, the contrib approach seemed the most accessible, but I agree that later on we might consider importing separate packages, like the Airflow provider model.


> Ok, that answers my atrribution question. A github handle is quite limited though. Most of the contributions I do are indirectly funded by the organisation I work for, but I can't mention my affiliation.

We could consider just adding another key for "organization" perhaps, I like the idea! I'll make a task for us internally and see what the team says!

> Sure, np. But that contradicts your own folder structure, no?
I'd say it's up to you! It might be easier to have both metrics and expectation in one module (see my comment above about juggling several files), but since we are providing the two folders in contrib, you can also keep them in separate modules.

**Review by spbail — APPROVED** [review]
I made some small tweaks to clean this up. We have two potential changes/enhancements we're discussing internally:
1. Add a new key for "organization" or "affiliation" - this is straightforward.
2. Allow other top-level packages under "experimental" - this might take a little while.
Until then, I'll accept and merge the PR, and we can make adjustments once the two changes above are functional.

**Comment by spbail** [comment]
Hi @mielvds - I just realized that expect_column_values_to_match_language.py uses polyglot, which in turn depends on PyICU, which requires the ICU C++ libraries. This is causing some issues with our builds - I've removed the expectation for now to get the builds to pass, but we'll work out a solution for that.
Alternatively, have you looked at the expectation in contrib that uses the langid Python package instead of polyglot? Would it be an option for you to use/modify that one?

**Comment by mielvds** [comment]
@spbail thanks for the merge! I'm ok with langid for now, it doesn't matter that much and the zero-dependency is nice. But I would start doubting its accuracy and speed: can we (eventually) merge both expectations and make the language detection library configurable?

**Comment by spbail** [comment]
@mielvds Absolutely, I think a merge would be great - we don't necessarily want duplicates of expectations. 

Feel free to submit a version of the current one you have using langid (I'm not familiar with them so might make more sense for you to implement and test). 

For the configurable libraries, a draft might be helpful, so we can discuss how we'd set up our build environment to install dependencies on the fly. It definitely seems like a really good use case, we're just still in fairly early stages for the contrib package!

**Comment by mielvds** [comment]
> @mielvds Absolutely, I think a merge would be great - we don't necessarily want duplicates of expectations.
> 
> Feel free to submit a version of the current one you have using langid (I'm not familiar with them so might make more sense for you to implement and test).

That wouldn't be worth the effort; they are more or less identical. I might just merge whatever I had in the other one and submit a PR.


> 
> For the configurable libraries, a draft might be helpful, so we can discuss how we'd set up our build environment to install dependencies on the fly. It definitely seems like a really good use case, we're just still in fairly early stages for the contrib package!

I'd have to think about a proposal on that as well. The limitation I see is when you want your expectations to be declarative and airtight (as in https://github.com/great-expectations/great_expectations/pull/2439), there's no way to do this dynamically because of library api differences. Is it an option to make the metric implementation of an expectation configurable?

**Pull request merged**
