### PR TITLE
[DOCS] Port over "How to run a Checkpoint in Airflow" from RTD to Docusaurus 

### PR DESCRIPTION
**Pull request by cdkini**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Port over `.rst` guide to `.md`
- https://superconductive.atlassian.net/browse/GDOC-192?atlOrigin=eyJpIjoiYmM0NWU4NTMyNzNkNDc4NzlhODdjZTI1N2RkMmYwYmYiLCJwIjoiaiJ9
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Review by Shinnnyshinshin — APPROVED** [review]
Thank you very much for this PR :) 

I dont have a super-strong opinion on this, but I'm wondering if there is a way to differentiate the 2 approaches (`BashOperator` vs `PythonOperator`) even more clearly. (adding something like `Option 1:` or `Option 2: ` to the title? Using tabs?)  I'd love to hear what you think. 

Approving PR since this is a non-blocking comment

**Comment by cdkini** [comment]
@Shinnnyshinshin thank you for taking a look :) 

I do like the point you're bringing up. RTD has that tab functionality that is really useful when laying out multiple approaches together on a single page; do we have an equivalent for Docusaurus?

I think a happy medium is probably being a bit more explicit and labeling the options in the manner you suggested. Should there be a table of contents at the top of such pages to clearly state what the possible options are?

**Comment by cdkini** [comment]
I added both a table of contents as well as `Option xyz` to the doc.

**Comment by Shinnnyshinshin** [comment]
Oh wow. This is great. Double-approve!

**Comment by Shinnnyshinshin** [comment]
Regarding your question about tabs, yes Docusaurus has an equivalent feature here: 

https://docusaurus.io/docs/markdown-features/tabs

You can find use cases in most of the `connecting to your data` docs, especially the section where we display the yaml and python configurations as separate tabs. In this case though, I do think your approach works best

**Comment by cdkini** [comment]
@Shinnnyshinshin I don't think the team has taken advantage of that tab functionality in other parts of the docs. I'll make a note to bring it up in one of our discussions as I believe we might need to do a bit of refactoring in some guides. Thanks!

**Pull request merged**
