### PR TITLE
[DOCS] Capital One DataProfiler Expectations README Update

### PR DESCRIPTION
**Pull request by stevensecreti**
Changes proposed in this pull request:
- Fixed two typos in DataProfiler Expectations README

### Definition of Done
- *[x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- *[x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- *[x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by stevensecreti** [comment]
@cla-bot check

**Review by AFineDayFor — APPROVED** [review]
Changes keep scheme with rest of script, LGTM

**Comment by stevensecreti** [comment]
@AFineDayFor do you know what is going on with the checks? It looks like `RunDockerComposeUp` is failing. It keeps retrying, making no progress. It seems to be stuck in a failing loop.

**Comment by taylorfturner** [comment]
@austiezr anything you can do to help move this along CC: @stevensecreti

**Pull request merged**
