### PR TITLE
[BUGFIX] Addresses Issue 2937.

### LINKED ISSUE #2937: Bug in expect_column_values_to_be_of_type for PyAthena SQL dialect
In combination with PyAthena, I am unable to use the "expect_column_values_to_be_of_type" expectation when checking whether a column is of STRINGTYPE.

**To Reproduce**
1. Construct a SqlAlchemyDataset where the dialect is "module 'pyathena.sqlalchemy_athena'". Ensure that at least one column is of String type.
2. Run expect_column_values_to_be_of_type(col_name, "STRINGTYPE").
3. Observe that the resulting error is "TypeError: issubclass() arg 2 must be a class or tuple of classes".

**Expected behavior**
I would expect the method to check against the String class, not an instance of String().

**Environment:**
 - Great Expectations Version 0.13.19
 - PyAthena 2.3.0

**Additional Information**
Running the following code indicates why the error is occurring.

```python
from pyathena import sqlalchemy_athena

inspect.isclass(sqlalchemy_athena.STRINGTYPE)

inspect.isclass(sqlalchemy_athena.BIGINT)
```

The first function call returns False whereas the second call returns True.  The end result is that in great_expectations/dataset/sqlalchemy_dataset.py line 1622 the getattr call return an instance if the type specified is STRINGTYPE.

```python
success = issubclass(col_type, getattr(type_module, type_))
```

**Potential fix**
Replace the else clause with the following:

```python
type_module = self._get_dialect_type_module()
potential_type = getattr(type_module, type_)
if not inspect.isclass(potential_type):
    real_type = type(potential_type)
else:
    real_type = potential_type
success = issubclass(col_type, real_type)
```

### PR DESCRIPTION
**Pull request by BenGale93**
Fixes #2937.

Changes proposed in this pull request:
- Altered the logic of expect_column_values_to_be_of_type so that a class is definitely passed to the issubclass check.
- Altered similar logic in expect_column_values_to_be_in_type_list method.

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Comment by talagluck** [comment]
Thanks so much for the contribution, @BenGale93 ! I will review in the next day or so and be in touch.

One thing to consider - it appears that your fix only applies to the V2 Batch Kwargs API. Do you know if this issue affect the V3 Batch Request API as well? If so, you want to consider amending that as well. Let me know what you think, and if you have any questions about this.

**Comment by BenGale93** [comment]
Hi @talagluck I don't know if V3 is impacted as I haven't been using them. If I get some more time I'll investigate and add to the pull request. Any particular areas in the codebase I should look at?

**Comment by talagluck** [comment]
Thanks, @BenGale93! In V3, each Expectation gets its own file, and often has a corresponding metric. You can take a look at `great_expectations/expectations/core/expect_column_values_to_be_of_type.py` for the Expectation, and `great_expectations/expectations/metrics/column_map_metrics/column_values_of_type.py` for the Metric. Happy to answer any questions you may have here.

**Review by talagluck — APPROVED** [review]
Thanks so much for this @BenGale93 - LGTM!

I'm going to approve for now, and I'll plan on merging tomorrow. If you find that this is an issue in V3 as well, please feel free to make the change, and if you'd like me to wait before merging just let me know.

Great work - thanks again!

**Comment by BenGale93** [comment]
Hi @talagluck it does appear to be an issue for V3 unfortunately. I plan to tackle it Saturday morning (UK time) so would you be able to hold off the merge until then? Thanks.

**Comment by BenGale93** [comment]
Hi @talagluck I've fixed the similar logic in the V3 API. I haven't added any tests, however, as I couldn't see a test file dedicated to these expectations. Is this something you'd also like me to add?

**Comment by talagluck** [comment]
Hi @BenGale93 - thank you so much for the follow-up! This looks great. Would you mind adding tests for V3? We actually don't have a great example, since we don't have a ton of backend-specific tests for expectations, but you can put these in `tests/expectations/core/test_expect_column_values_to_be_of_type.py` and `tests/expectations/core/test_expect_column_values_to_be_in_type_list.py`. Could you also include a quick note explaining that these tests are intended to cover the use case of Athena specifically?

As a side note, we are currently having some issues with our Azure pipelines, so don't fret if tests don't pass initially here.

**Comment by BenGale93** [comment]
Hi @talagluck, I've added some tests for V3 which are the same in structure as the V2 tests. Hopefully, the test names make it clear they are for the Pyathena dialect. Thanks so much for your input on this.

**Review by talagluck — APPROVED** [review]
Thanks so much for all of these updates! This looks great, I will merge it in as soon as I'm able.

Thank you again for your contribution - this was excellent!

**Pull request merged**
