### PR TITLE
[DOCS] How-to for running checkpoint in Airflow

### PR DESCRIPTION
**Pull request by spbail**
My go-to suggestion for this would be to use the bash operator, but this might be controversial. Happy to chat!

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Created new how-to doc
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

### CODE REVIEW

**Review by Aylr — COMMENTED** [review]
I'm all over simplicity and this is my go-to as well. However I might also consider adding either a section that describes yanking the output from `checkpoint script` and dropping it into a `PythonOperator` or linking to another howto that covers that material.

**Comment by spbail** [comment]
Aaah neat! I'll add that, yes.

**Review by Aylr — APPROVED** [review]
lgtm

**Comment by spbail** [comment]
Let's try that again, looks like tests pass now...

**Pull request merged**
