### PR TITLE
[MAINTENANCE] Install GitHub dependabot

### PR DESCRIPTION
**Pull request by Aylr**
Changes proposed in this pull request:
- github dependabot installed

Note that this may increase workload initially as it defaults to opening no more than 5 PRs daily, with a single PR per dependency update.
This can be completely configured or removed entirely if it does not suite our current team workflow.

### CODE REVIEW

**Comment by Shinnnyshinshin** [comment]
Love this, and love how simple it is to add it to the workflow. 

I had two questions : 

1)(noob question) Is the `daily` check going to cause a lot of additional overhead? Would there be an argument for `weekly` check that would (more-or-less) coincide with how often we put releases out? 

2)would dependabot help with the problem we had when the Snowflake python connector had an incompatibility with `requests` and our tests were failing?  ([link](https://github.com/great-expectations/great_expectations/pull/1623))

**Comment by Aylr** [comment]
1. If by overhead you mean computational/cost overhead, then no (it's run by GH). If you mean human overhead, then at first, definitely if we have lots of older dependencies. We can certainly play with the interval, but that will slow down the benefits, which is a tradeoff I have no strong opinions on.

2. I think it might have?

**Comment by Shinnnyshinshin** [comment]
Got it :)  thanks. I think this is great, but will defer to @jcampbell for approval

**Review by jcampbell — APPROVED** [review]
Interested to try this out

**Pull request merged**
