### PR TITLE
[DOCS] Fix broken links in  `how_to_instantiate_a_data_context_on_a_databricks_spark_cluster` documentation

### PR DESCRIPTION
**Pull request by Shinnnyshinshin**
Changes proposed in this pull request:
- fixed broken links in `Additional resources` section

### CODE REVIEW

**Comment by Shinnnyshinshin** [comment]
just saw this during the seminar. Fixed the two references at the end of the page. Please have a look

**Review by anthonyburdi — APPROVED** [review]
LGTM!

**Comment by anthonyburdi** [comment]
FYI @Shinnnyshinshin - Sam mentioned you might be able to just reference the doc in the :ref: e.g. how_to_configure_a_databricks_aws_datasource rather than the whole file path using double underscores. That way if the files move, the links don't break. Haven't tried it myself yet, just FYI.

**Comment by Shinnnyshinshin** [comment]
> FYI @Shinnnyshinshin - Sam mentioned you might be able to just reference the doc in the :ref: e.g. how_to_configure_a_databricks_aws_datasource rather than the whole file path using double underscores. That way if the files move, the links don't break. Haven't tried it myself yet, just FYI.

Very very good to know. Thank you :)

**Pull request merged**
