### PR TITLE
[BUGFIX] custom notebook templates

### PR DESCRIPTION
**Pull request by luke321321**
Changes proposed in this pull request:
- fix custom_templates_module allowed to be `None` as allowed in the class `__init__()` function.
 This is needed for the example in the docs "Overwriting the class" to work.
- Improved documentation by noting that `notebook_assets` needs to be a python package (`__init__.py` files are needed)
- Added tests for these cases

### CODE REVIEW

**Comment by eugmandel** [comment]
@luke321321 Thank you! Please allow a bit more time for the review - it is taking longer now because of an explosion of awesome community PRs lately.

**Comment by luke321321** [comment]
Yes it is relevant. Blocked by needing a review from GE team

**Comment by talagluck** [comment]
Hi @luke321321 - many apologies for delays. We're going back through outstanding PRs, and we would like to merge this in. It looks like we don't have the access to update from `develop` and resolve conflicts. Would you please do this? Then we'll take a look and get this merged ASAP.

**Comment by luke321321** [comment]
@talagluck I've merged `develop` in and added a line to the changelog

**Comment by luke321321** [comment]
@talagluck any chance of getting this merged in?  The CI is passing and should be all good to go.

**Review by talagluck — APPROVED** [review]
LGTM! Once tests pass, this should be set to merge.

**Pull request merged**
