### PR TITLE
[MAINTENANCE] Upgrade to the latest pre-commit hooks

### PR DESCRIPTION
**Pull request by Fokko**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
By running `pre-commit autoupdate` we get the latest version of the hooks. 

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

### CODE REVIEW

**Comment by Fokko** [comment]
@cla-bot check

**Comment by spbail** [comment]
@Fokko Thanks for the contribution! We've reviewed and aren't quite clear about the reason for the formatting changes. Might have been an auto-linter? We would prefer a minimal commit without the formatting changes, would you mind re-submitting? Thanks!

**Comment by Dandandan** [comment]
@spbail I think the newer version of black introduced some changes related to formatting docstrings and newlines in arguments.

@Fokko might be useful to split the isort/black updates and find out if you can disable one of the changes in black so the changes are not so big?

**Comment by spbail** [comment]
That would be great, thanks for the suggestion @Dandandan.

**Comment by spbail** [comment]
Just another ping @Fokko, do you want to continue working on this?

**Review by spbail — APPROVED** [review]
Better late than never haha. We had already made the black changes, so only upgrading isort. Ran pre-commit locally and it looks like there aren't any additional changes coming out of it. Thank you @Fokko !

**Pull request merged**
