### PR TITLE
[DOCS] Updating to reflect current Expectation dev state

### PR DESCRIPTION
**Pull request by spencerhardwick**
These changes reflect the current state of Expectation implementations in v3

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Updated the Expectation Implementations by Backend table on the v3 docs to reflect work completed by Superconductive Product Engineering last development cycle.

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] I have made corresponding changes to the documentation
- [x] I have made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Review by cdkini — APPROVED** [review]
Going off of the assumption that this view is indeed correct, I'm happy to sign off :)

Thanks for all the hard work with this and for making our docs that much nicer 🎉

**Comment by bhcastleton** [comment]
Do we want to say something like “Updated as of September 2, 2021” ?? If not, then I assume we'll keep it up-to-date until the gallery comes out.

**Comment by spencerhardwick** [comment]
> Going off of the assumption that this view is indeed correct, I'm happy to sign off :)
> 
> Thanks for all the hard work with this and for making our docs that much nicer 🎉

Thanks Chetan!

**Review by cdkini — APPROVED** [review]

**Comment by kyleaton** [comment]
@clabot check

**Comment by kyleaton** [comment]
@cla-bot check

**Pull request merged**
