### PR TITLE
Improve formatting, linking for implemented_expectations documentation.

### PR DESCRIPTION
**Pull request by jcampbell**

### CODE REVIEW

**Comment by abegong** [comment]
A screenshot for this would be really nice...

**Comment by jcampbell** [comment]
Before:

image

After:
Glossary:
image

Table:
image

Note that the overall width of the implemented_expectations page is now wider to accomodate the table, but it's only that one (so it's useful but not disruptive).

**Review by abegong — APPROVED** [review]
LGTM!

This also gives me ideas for styling the page to be more consistent with greatexpectations.io

**Comment by jcampbell** [comment]
Good call.

This'll be the last PR for this release. I'm going to do some final tests and then build the release.

**Pull request merged**
