### PR TITLE
[DOCS] Capital One Data Profiler README update

### PR DESCRIPTION
**Pull request by taylorfturner**
Very simple update to include `profile` statistic descriptions per Capital One Data Profiler's README

### CODE REVIEW

**Comment by taylorfturner** [comment]
FYI @stevensecreti

**Review by AFineDayFor — APPROVED** [review]
Howdy @taylorfturner :wave: LGTM, thank you much. :bow:

**Comment by taylorfturner** [comment]
@AFineDayFor seeing some errors on checks, but just merged in `develop` 🤞

**Comment by taylorfturner** [comment]
@AFineDayFor @austiezr bump ... looks like partner integrations failing? How can we resolve this?

**Pull request merged**
