### PR TITLE
[MAINTENANCE] Exclude docs-only changes from PR builds

### PR DESCRIPTION
**Pull request by jcampbell**
Changes proposed in this pull request:
- Do not trigger CI builds on docs-only PRs

### CODE REVIEW

**Comment by spbail** [comment]
Oh em gee. I had that in the back of my mind but forgot to ask if that's possible.

**Review by spbail — APPROVED** [review]
I'm just going to approve it because YAY.

**Review by Aylr — COMMENTED** [review]
❤️ ❤️

**Comment by spbail** [comment]
We did it! 🎉

**Pull request merged**
