### PR TITLE
[FEATURE] SQL Alchemy Oracle Support

### PR DESCRIPTION
**Pull request by NathanFarmer**
Oracle is the most popular RDBMS in the world. Including Oracle support would greatly extend the user base for Great Expectations.

I opened this PR following the discussion in this thread with @eugmandel and @Patechoc regarding Oracle support:
[https://discuss.greatexpectations.io/t/getting-started-with-oracle-data/681](https://discuss.greatexpectations.io/t/getting-started-with-oracle-data/681)

Changes proposed in this pull request:
- Clauses added to sqlalchemy datasource and database for handling Oracle-specific errors when creating temporary tables
- Clauses added to sqlalchemy datasource and database for handling Oracle-specific errors due to lack of LIMIT keyword

Please let me know if there is anything else I can do to move this effort forward!

### CODE REVIEW

**Comment by NathanFarmer** [comment]
@cla-bot check

**Comment by NathanFarmer** [comment]
@cla-bot check

**Comment by eugmandel** [comment]
@NathanFarmer Thank you - a PR enabling Oracle is so promising! We will review it shortly.

**Review by Shinnnyshinshin — COMMENTED** [review]
Hi @NathanFarmer thank you for submitting this PR. We're very excited to add Oracle support for GE. I'd like to learn a bit more about how this functionality can be effectively tested, either locally and/or through Pytest.  I'm working on getting an instance on Amazon RDS

**Comment by NathanFarmer** [comment]
Hi @Shinnnyshinshin if you have no Oracle server to test with you can use the official [Oracle Docker Images](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance) to stand up a database. I assume the pytests will be similar to the other SQL Alchemy connection types, but I do not have a lot of experience with pytest.

**Comment by Shinnnyshinshin** [comment]
Hi @NathanFarmer Thank you again for your work with this. The PR looks great :) 

I only have one small ask: that the `CREATE GLOBAL TEMPORARY TABLE` logic be added to the `_create_temporary_table()` function in the file : `execution_engine/sqlalchemy_batch_data.py`. It is how the equivalent functionality is handled in the V3 API, and this way we can have all the changes be part of one PR.

**Review by Shinnnyshinshin — APPROVED** [review]
Thank you for the quick response @NathanFarmer :) LGTM

**Comment by iftachsc** [comment]
Hi. thanks for this important feature. i am with the latest version of GE and cannot see Oracle as an option. is there any doc how to utilize this feature and work with Oracle? Thanks in advanced.

**Comment by NathanFarmer** [comment]
@iftachsc sorry for the slow response. Oracle is implemented through SQL Alchemy. When you run `great_expectations datasource new` you will select "2. Relational database (SQL)" then "6. other - Do you have a working SQLAlchemy connection string?" You can then use an Oracle connection string.

**Pull request merged**
