### PR TITLE
Bug/sphinxcontrib lastupdate

### LINKED ISSUE #1160: Docs fail to build, with `Could not import extension sphinxcontrib.lastupdate`
Trying to build docs locally, it fails as follows:

```
$ make html
Running Sphinx v2.3.1

Extension error:
Could not import extension sphinxcontrib.lastupdate (exception: No module named 'sphinxcontrib.lastupdate')
make: *** [html] Error 2
```

### PR DESCRIPTION
**Pull request by abegong**
Should resolve #1160 .

We might want to implement #1162 to test this.

### CODE REVIEW

**Comment by abegong** [comment]
Note that the base branch is `master`, not `develop`. Is that the correct process now?

**Comment by Aylr** [comment]
I changed the base branch and it looks like it needs a rebase from you since it picked up some old commits

**Review by Aylr — CHANGES_REQUESTED** [review]
Please add a bugfix line to the changelog as well.

**Comment by jcampbell** [comment]
This PR should not merge -- the relevant include is in `docs/requirements.txt`. Perhaps a better fix is to update the contributor docs?

**Pull request closed without merging**
