### PR TITLE
* major CLI change - noun --> verb (suite new, suite edit), etc.

### PR DESCRIPTION
**Pull request by Aylr**
**This PR looks much bigger than the changes actually are due to factoring down of the giant `cli.py` module into smaller noun modules**.

## What's Here

* Changed commands in docs
* minor cleanup in CLI messages
* fixed a few broken cli tests, marked a lot as skipped for now
* broke out giant cli module into modules for each sub command

## What it looks like

demo_public_data_test_—_-bash_—_153×109_and_Profiling_Reference_—_great_expectations_documentation

## Known Issues

- There are still tons of broken CLI tests.
- I'm not totally happy with some of the nesting. Feedback and or hatred is welcome.

### CODE REVIEW

**Review by abegong — COMMENTED** [review]
* This is great. I'm totally on board with CRUD-ifying all the nouns in our system.
* Splitting up that monster cli.py file also feels great.

### Nouns
So it looks like the currently supported nouns are:
	* datasource
	* docs
	* init -> Isn't this the special case of `project new`?
	* project
	* suite -> I'd vote for `expectations` or `expectation_suite` over
	* `suite`. 
	* validation

* What about `generators`? Are they nested under `datasources`?
* Are we making any attempt to track data assets or batches? I suspect that being able to list batches will be a game changer for lots of data workflows.
* Other potential nouns: `plugins`, `profilers`, `actions`, `operators`, `custom_expectations`, `custom_renderers`…?
* As long as we’re talking about renaming, I think we should brainstorm alternatives to `docs`. That word is very generic and conflated with many other things.
* For reference, the top-level items in our yml file are:
	* datasources
	* config_variables_file_path
	* plugins_directory
	* validation_operators
	* stores
	* expectations_store_name
	* validations_store_name
	* evaluation_parameter_store_name
	* data_docs_sites
* These are kinda close to the nouns in the new CLI. I’d strongly advocate for consistency across the CLI, YML files, and actual class and method names.

### Verbs
* I’d love to have some kind of guidance like:
```
Most commands to the Great Expectations CLI follow this format:
	great_expectations [noun] [verb]

The nouns are {...}

Each noun accepts the following verbs:
* new
* list
* edit
* delete

In addition, the CLI supports the following special commands:
* great_expectations init : same as `project new`
* great_expectations datasource profile : profile a datasource
* great_expectations docs build : compile documentation from expectations
* great_expectations validate ... : 
```

* How about “verify” as a shorter version of “check-config”? “check” could also work. Alternatively, would it work for “list” to automatically check config correctness for the relevant object? Then we have four core verbs that map perfectly onto CRUD.
* IMO, the ergonomics around `validate` are important enough to justify a special verb outside the normal CRUD operations.
* `validation csv` seems weird to me. If we're going to use `validation` over `validate`, then I'd definitely stay consistent with `validation new csv` over `validation csv`. Alternatively, if this 
* Riffing on something that I think I saw in your notes earlier: what if we included “share” as a fifth verb, with the specific goal of encouraging people to share community plugins.  `great_expectations [object] share: creates a github gist containing the relevant config and/or code and submits it for consideration into the great_expectations public gallery.`

**Review by jcampbell — COMMENTED** [review]
I really like these changes. Haven't looked at code yet, but thinking at the design level and working through scenarios, I've identified some thoughts:

0. There is some ambiguity between whether "noun" here means a 'thing' that GE operates on or a 'thing' that is a subcomponent of overall ge functionality. For example, a "project" seems pretty clearly to be a single thing, but "docs" is an area of functionality.

1. Some concrete rename proposals:
a. `docs` -> `data_docs_site` (consistency; addresses 0. by making it operate on *one* site)
b. `suite` -> `expectation_suite`, with `es` as a synonym (consistency and clarity)

2. After writing a longer aside (which I'll keep below so I don't feel like I wasted my time :)), I think the issue on validation is that there are two different nouns that need to be addressed: `validation_operator` and `expectation_validation_result`. I think we should have both, with synonms `vo` and `evr`, so:
`great_expectations vo --name my_operator validate` and `great_expectations evr delete`, for example.

The original aside:
> is I think there's some confusion coming from the fact that in general, one operates on the noun using the verb, but in some cases there are multiple nouns present. I think that's what's causing confusion in the `validation csv` case. I think the principle is that the *input* noun is the relevant one. So:

>`great_expectations es validate` (where es is a synonym for expectation_suite, the still-usable full name) would be the command instead of `great_expectations validation` (since the validation is the *output*) would be my preference.

>**but** even then, there's going to be confusion -- the next parameter should be data description in the above case...where I see a few options:

>a. `great_expectations es validate --batch <batch_kwargs_ref_somehow>`
>b. `great_expectations data validate --es <expectation_suite_name>`
>c. `great_expectations validation_operator (vo) run --es <expectation_suite_name> --batch <batch_kwargs_ref>`

3. As implied in 2 above, I think there's a need for validation_operator as a top-level noun

**Comment by eugmandel** [comment]
I love the direction! Both the commands (I checked out the branch and ran through most commands in the terminal) and the refactoring of the cli module feel good to me.

While "CRUD-ifying" the CLI is a good direction, it is OK for some commands to *not* follow the CRUD/noun-first style. 

After reading Abe's and James' comments, I want to integrate them into my comment and create two lists: 1.  a small list of change requests that can be implemented now for the PR to be merged, and 2. a list of changes/improvements to be considered later (not as part of present PR).

**Change requests for this PR:**

1. Rename `suite` to `expectation_suite`
2. Deprecate the validate csv command. I agree both with Abe's comment on having "validate" outside of CRUD and with James' comment on adding a command for running a validation operator. Validate a CSV file is a special case of validating a batch and should be addressed in a way that works for all supported datasources - to be done later.
3. Add two-letter synonyms to all nouns (James) ("es" for expectation_suite, etc.)


**Changes to consider later:**

1. Abe's proposal for additional nouns (plugins, profilers, etc).
2. James' proposal of adding a command for running a validation operator
3. Adding a command for validating a batch

**Comment by Aylr** [comment]
Ok. Thanks a lot for the great ideas here! While I agree that consistency is good, typing long commands is absolutely brutal for users, so I'm likely going to stick with as short noun names as possible, like `docs` and `suite`.

**Pull request merged**
