### PR TITLE
Feature/161

### PR DESCRIPTION
**Pull request by abegong**
Implements #161

### CODE REVIEW

**Comment by abegong** [comment]
Oi. Improving test coverage on net-negative PRs is hard.

**Comment by jpcampb2** [comment]
Core changes look good to me. 
Small nit: looks like some print statements are still in there

Given your other PR, I'm thinking I didn't follow where you wanted to go with testing...I'll read through the approach more closely.

**Comment by abegong** [comment]
+1

The unit tests are an experiment. The print statements and JSON-ified tests are both part of it.

The JSON-ified unit tests include a new field called `notes`. They give us a place to give these micro tests informative names:
`"notes": "Test error handling for non-int max_value"`

The print statements are a simple way to see if a JSON-ified test fails. They work very nicely in the output from `py.test`

Also, I've added a field called `error`, which can do some pattern matching against error messages as long as `catch_exceptions=True`.

These changes make me much more bullish on JSONified tests. Small proof: I've this dev loop is quick enough that I've been able to get to 100% coverage for many of the expectations.

I'll open an issue to document this pattern for discussion in just a sec.

In the meantime, I'd propose that we merge this PR.

**Comment by jpcampb2** [comment]
I commented on the issue you created re: tests, and I agree we can merge this PR while we figure out what we want to do with tests. I don't want to have GE drift too far into experiments with unit testing frameworks, but it's  fun along the way. :)

**Review by jpcampb2 — APPROVED** [review]

**Pull request merged**
