### PR TITLE
[CONTRIB] Feature/expect column values to match thai

### PR DESCRIPTION
**Pull request by swittchawa**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], or [CONTRIB]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- Added regex based column expectation that detect Thai langauge
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in GitHub issues or Slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Review by anthonyburdi — APPROVED** [review]
Very cool! Thank you for this contribution.

**Comment by anthonyburdi** [comment]
@swittchawa I approved but before we can merge you'll just need to fix the linter errors. It looks like there are just a few unused imports:
```
ruff .
contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py:7:20: F401 [*] `typing.Dict` imported but unused
contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py:7:26: F401 [*] `typing.Optional` imported but unused
contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py:9:63: F401 [*] `great_expectations.core.expectation_configuration.ExpectationConfiguration` imported but unused
contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py:11:5: F401 [*] `great_expectations.exceptions.exceptions.InvalidExpectationConfigurationError` imported but unused
contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py:15:5: F401 [*] `great_expectations.expectations.regex_based_column_map_expectation.RegexColumnMapMetricProvider` imported but unused
Found 5 errors.
[*] 5 potentially fixable with the --fix option.
```

**Review by anthonyburdi — CHANGES_REQUESTED** [review]
Apologies @swittchawa, would you mind removing the unused imports? Thank you! 🙇

**Comment by swittchawa** [comment]
> Apologies @swittchawa, would you mind removing the unused imports? Thank you! 🙇

Can you please check if this is ok or not? Let me know if you need any more edit from me! And also how could I contribute to make it goes to production?

**Comment by anthonyburdi** [comment]
> > Apologies @swittchawa, would you mind removing the unused imports? Thank you! 🙇
> 
> Can you please check if this is ok or not? Let me know if you need any more edit from me! And also how could I contribute to make it goes to production?

Almost there! I see one more issue:
`contrib/experimental/great_expectations_experimental/expectations/expect_column_values_to_match_thai.py:16:1: W293 [*] Blank line contains whitespace`
I'm looking at the results of the checks, specifically the `contrib (contrib lint)` stage: 
image
https://dev.azure.com/great-expectations/great_expectations/_build/results?buildId=209010&view=logs&j=eca830a7-e027-5c16-85fb-144337d17bc8&t=0fd6b91e-dc3f-5154-ed9f-0aea14fe2f7b&l=86

**Review by anthonyburdi — APPROVED** [review]
Thank you! This will get merged into our `develop` branch and be included in the next release :)

**Pull request merged**
