### PR TITLE
Refactor dataset

### PR DESCRIPTION
**Pull request by cselig**
In this branch, I've started to separate out expectation logic from logic that is specific to different types of datasets. For example, previously expectation logic for `expect_column_to_exist` was duplicated between dataset implementations. In this branch that expectation logic is moved to `Dataset`, and the implementation-specific logic of actually getting a dataset's columns is delegated to a method `_get_table_columns`, which is implemented by each child of `Dataset` (e.g. `self.spark_df.columns`). This unlocks a few things:
* Logical separation of expectation logic and dataset-type-specific logic, which would make it easier to implement new dataset types.
* Caching: implementation specific pieces are currently implemented as attributes of Dataset and are cached. For example: when computing a long list of expectations on a spark dataset, total row count must only be computed once.
* Standardized dataset interface: users can query row count, columns, column means, etc. through properties like `.row_count`, `.table_columns`, etc. in a standardized way between different dataset types.

Callouts/notes:
* I'm not super familiar with the internals of every dataset type, so it's unclear if this approach would block implementation-specific optimizations that are being done.
* The different dataset structures (subclassing vs not subclassing) could make this difficult.

I think all of these points should be up for discussion on how this fits in to library's current state, what's worth tackling, and so on.

### CODE REVIEW

**Comment by jcampbell** [comment]
I'm glad you're pushing to think about caching. 

I think caching the core count values (rows, nonnulls, etc) makes a lot of sense. It would also open the door to a much more explicit treatment of what exactly a "null" is, which is sometimes user-configurable.

I assume the refactored dataset file is an artifact here, is that right? I'd also recommend you merge in the develop branch soon so that you can deal with the major refactor there that moved a lot of formerly "dataset" logic into "data_asset"

I'd recommend we hold this particular merge until those two things just so I don't inadvertently not pick up those changes.

Last thought (not relevant for pulling in this PR): we should convert sparkdfdataset to use the json-based expectation tests asap so that you don't spend time writing individual expectation tests that are spark-specific. Happy to talk through that on slack if you want; the key thing is to implement a new hook in get_dataset for the new dataset type. Should be pretty straightforward following patterns in the file for sql.

**Comment by cselig** [comment]
"I assume the refactored dataset file is an artifact here, is that right?" Correct, I'll get rid of this.

"I'd also recommend you merge in the develop branch soon" I think these changes have already been incorporated in this branch.

To me, the most important advantage of the approach in this branch is deduplicating and centralizing expectation logic into `Dataset`; I wanted to check that there's alignment here (before I start going too far down this road)?

Looked a little into incorporating the spark datatset into the current testing structure and I think it'll require enforcing schemas in the test data sets. Looks like this is being done in #427, so I was wondering if it would make sense to merge that branch into this one so I can get testing all set up?

**Comment by jcampbell** [comment]
👍I just missed the updates from develop when I looked at the commit history, so thanks for confirming that's done.

What other logic are you thinking to merge into core dataset from the platform-specific implementations? I'm certainly open to the idea of moving more in, but am not sure what specifically you're thinking would move well.

Yes, I think merging in #427 to get the updated test harness and pattern is as good idea.

**Comment by cselig** [comment]
I guess I'd need to give some more thought on what would make sense to move up to Dataset. I think the ideal situation would be that all expectation logic is in Dataset, but I think practically some things will probably be not feasible to extract from the various implementations. So my thoughts here are a little fuzzy at the moment, but I'm leaning towards moving as much as makes sense into Dataset.

I'll take integrating the testing changes as a next step and think a little more about these points. I also don't think this specific PR needs to be merged immediately, but did want to start the conversation here.

**Comment by jcampbell** [comment]
@cselig: this looks good to me, and I'd suggest we go ahead and merge it into feature/spark to keep that branch moving along as a work in progress; if you say so, I'll do the merge.

**Comment by cselig** [comment]
Sounds good, let's merge and I'll keep pushing `feature/spark` along. I think in the near future it could make sense to resync with you me and Gabe on the progress so far, so I'll keep in touch about that.

**Pull request merged**
