### PR TITLE
Feature/eval parameters

### PR DESCRIPTION
**Pull request by jcampbell**

### CODE REVIEW

**Review by ayirplm — COMMENTED** [review]
This pyparsing version<3 is for py2.7, right?

**Review by ayirplm — COMMENTED** [review]
Indentation line 87, tests/data_asset/test_parameter_substitution.py

**Review by ayirplm — COMMENTED** [review]
Nice BNF use, https://github.com/pyparsing/pyparsing/blob/master/examples/fourFn.py

**Comment by jcampbell** [comment]
@ayirplm : thank you for the review notes!

1. I pinned <3 *not* to support py2, but just on general principle that we should guard against major API changes by pinning major semantic versions prior.

2. Indentation is intentional in this case -- the pytest context manager makes the exception info object available on exit (https://docs.pytest.org/en/latest/assert.html#assertions-about-expected-exceptions)

3. Thank you!! Some slight modifications for our case, but I'm much happier with this than some sort of eval option.

**Review by eugmandel — APPROVED** [review]

**Pull request merged**
