### PR TITLE
Alexsherstinsky/post 0.13 release cleanup 12 02 2020 3

### PR DESCRIPTION
**Pull request by alexsherstinsky**
### Scope
* Remove the unused method `DataContext.get_batch_list_from_new_style_datasource()` -- the correct methods are `DataContextV3.get_batch()` and `DataContextV3.get_batch_list()`.
* Update tests accordingly.

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

### CODE REVIEW

**Review by abegong — COMMENTED** [review]
@alexsherstinsky , counterproposal: Move this method to `DataContextV3` and rename it `get_batch_list`, keeping all the tests. There should be a top-level method allowing users to fetch a list of Batches.

**Comment by alexsherstinsky** [comment]
> @alexsherstinsky , counterproposal: Move this method to `DataContextV3` and rename it `get_batch_list`, keeping all the tests. There should be a top-level method allowing users to fetch a list of Batches.

Investigating...  Thanks.

**Comment by abegong** [comment]
@alexsherstinsky , I don't see a `DataContextV3.get_batch_list` method.

**Review by abegong — CHANGES_REQUESTED** [review]
This looks like it's probably functionally correct, but it's very hard to tell.

Adding `process_batch_request` as a method to handle the logic for both `get_batch` and `get_batch_list` makes things much more opaque than it needs to be.

Also, I strongly disagree with the stylistic choice to use `get_currently_executing_function_call_arguments` as a magic way of passing routine arguments from one method to another. Explicit is better than implicit. This implementation is at the extreme extreme of "implicit."


Functionally, both `get_batch` and `get_batch_list` do two things. First, validate and convert a bunch of arguments into a valid BatchRequest. Second, pass that BatchRequest through to the appropriate Datasource. Beyond those two steps, `get_batch` adds a smidge of extra logic to verify that only a single Batch was fetched.

Please simplify and reimplement.

One alternative would be to factor out the validation and type conversion logic into a separate function, shared by both `get_batch` and `get_batch_list`. Something like `validate_and_convert_arguments_to_batch_request.` This feels a bit heavyweight, but better than combining *all* the logic like we currently see in `process_batch_request`.

Another alternative would be to have `get_batch` simply call `get_batch_list`, then add the check to verify that a single Batch was fetched. My intuition is that this will be the simplest, most readable, and most maintainable version of these functions.

**Comment by alexsherstinsky** [comment]
> This looks like it's probably functionally correct, but it's very hard to tell.
> 
> Adding `process_batch_request` as a method to handle the logic for both `get_batch` and `get_batch_list` makes things much more opaque than it needs to be.
> 
> Also, I strongly disagree with the stylistic choice to use `get_currently_executing_function_call_arguments` as a magic way of passing routine arguments from one method to another. Explicit is better than implicit. This implementation is at the extreme extreme of "implicit."
> 
> Functionally, both `get_batch` and `get_batch_list` do two things. First, validate and convert a bunch of arguments into a valid BatchRequest. Second, pass that BatchRequest through to the appropriate Datasource. Beyond those two steps, `get_batch` adds a smidge of extra logic to verify that only a single Batch was fetched.
> 
> Please simplify and reimplement.
> 
> One alternative would be to factor out the validation and type conversion logic into a separate function, shared by both `get_batch` and `get_batch_list`. Something like `validate_and_convert_arguments_to_batch_request.` This feels a bit heavyweight, but better than combining _all_ the logic like we currently see in `process_batch_request`.
> 
> Another alternative would be to have `get_batch` simply call `get_batch_list`, then add the check to verify that a single Batch was fetched. My intuition is that this will be the simplest, most readable, and most maintainable version of these functions.

@abegong I also agree that the second approach is the way to go.  Fixing now.

**Review by abegong — APPROVED** [review]
Thanks for making these changes!

**Pull request merged**
