### PR TITLE
[ENHANCEMENT] Edtf with support levels

### PR DESCRIPTION
**Pull request by mielvds**
EDTF dates have [a level system](https://www.loc.gov/standards/datetime/) of supported features. This PR add a level parameter to  `expect_column_values_to_be_edtf_parseable`. It also adds support for spark.

One issue though with the tests: why do all value sets need to be the same length? This is a strange requirement and also hard to do.

### CODE REVIEW

**Review by eugmandel — CHANGES_REQUESTED** [review]
@mielvds Looks good. The only thing I see the linter complains - could you please run black and isort to make sure? Thank you!

**Comment by mielvds** [comment]
@eugmandel I ran black and isort, but also switched the dependency to a more maintained package,  which also shortens the code. The linter seems to be ok now! 
Some questions though:
- in the `library_metadata`, when specifying  `"requirements": ["edtf_validate"],`: can I use a mininum version number or perhaps the requirements.txt syntax?
- Regarding my previous issue: I see now that all test data from `{"data": {}}` is parsedinto a single pandas dataframe, so I had to split up my test data in different examples. That issue is ok now. However, the diagnostics complain about `"error_message": "No definition found for column_values.edtf_parsable.unexpected_count",`. Any idea where to define this?

**Comment by mielvds** [comment]
@eugmandel any chance you or anybody else of the team could have a look at my questions?

**Comment by talagluck** [comment]
Hi @mielvds! Apologies for the delay - we've had a bit of a backlog of contributions, but are starting to build out our devrel team, so response times will be improving!

In response to your questions:
- Yes, you can specify a minimum version a la the `requirements.txt` syntax. You can see an example of this in `expect_column_values_to_be_us_zipcode_within_radius_of_given_zipcode.py`. As far as I'm aware, this is just used for documentation, and should not have an impact on dependency installation.
- For the `unexpected_count` issue, I believe this is a function of one of the methods that we use to test expectations, which takes only a limited subset of possible keys. If you remove `"unexpected_count"` from `"out"`, does this work? (As an aside, I believe that the Expectation itself will still automatically have the `column_values.edtf_parsable.unexpected_count` due to its metric being a ColumnMapMetric, you just may not be able to use this for this specific `run_diagnostics` checker. ) 

Does that make sense? Please let me know if you have any additional questions. Thank you so much for your contribution! I'll keep an eye out for additional correspondence.

**Comment by talagluck** [comment]
Hi @mielvds - I wanted to follow up here. Is this something which you are still interested in merging?

**Comment by mielvds** [comment]
@talagluck absolutely! And thanks for answering my questions. I just have to find a bit of time to fix things based on your answers, rebase and it should be good to go.


>     * Yes, you can specify a minimum version a la the `requirements.txt` syntax. You can see an example of this in `expect_column_values_to_be_us_zipcode_within_radius_of_given_zipcode.py`. As far as I'm aware, this is just used for documentation, and should not have an impact on dependency installation.

Does it make sense that this is documentation only? This particular expectation, for instance, does not work with `edtf-validate < 2.0` That's important to indicate for every expectation that uses external dependencies, no?

> 
>     * For the `unexpected_count` issue, I believe this is a function of one of the methods that we use to test expectations, which takes only a limited subset of possible keys. If you remove `"unexpected_count"` from `"out"`, does this work? (As an aside, I believe that the Expectation itself will still automatically have the `column_values.edtf_parsable.unexpected_count` due to its metric being a ColumnMapMetric, you just may not be able to use this for this specific `run_diagnostics` checker. )
> 

I'll let you know!

**Comment by talagluck** [comment]
Hi @mielvds! 

> Does it make sense that this is documentation only? This particular expectation, for instance, does not work with edtf-validate < 2.0 That's important to indicate for every expectation that uses external dependencies, no?

This is a great point, but it doesn't quite apply here since this expectation is in the contrib directory, and thus considered experimental. For these expectations, at least for the moment, we ensure that they are documented and have some testing (at least one passing and one failing condition), but otherwise don't enforce too much about them. In cases like this, we are OK with these requirements being documentation-only. If the expectation were part of the core library, then that would not be the case.

Does that make sense? Let me know what you think.

**Comment by mielvds** [comment]
> Hi @mielvds!
> 
> > Does it make sense that this is documentation only? This particular expectation, for instance, does not work with edtf-validate < 2.0 That's important to indicate for every expectation that uses external dependencies, no?
> 
> This is a great point, but it doesn't quite apply here since this expectation is in the contrib directory, and thus considered experimental. For these expectations, at least for the moment, we ensure that they are documented and have some testing (at least one passing and one failing condition), but otherwise don't enforce too much about them. In cases like this, we are OK with these requirements being documentation-only. If the expectation were part of the core library, then that would not be the case.
> 
> Does that make sense? Let me know what you think.

I think it's a good approach to not enforce too much on contrib packages. However, as a contributor, if I would like to add a version constraint to my dependencies, how would I do it? 

Does this also mean that any requirements declared in `library_metadata` are not automatically installed when installing the `great-expectations-experimental` package?

**Comment by mielvds** [comment]
@talagluck the rebase turned a bit weird with all the commits, but it's ok I guess. I switched to a non-draft PR; I think @eugmandel's requested changes have been addressed.

>     * For the `unexpected_count` issue, I believe this is a function of one of the methods that we use to test expectations, which takes only a limited subset of possible keys. If you remove `"unexpected_count"` from `"out"`, does this work? (As an aside, I believe that the Expectation itself will still automatically have the `column_values.edtf_parsable.unexpected_count` due to its metric being a ColumnMapMetric, you just may not be able to use this for this specific `run_diagnostics` checker. )
> 

Removing `"unexpected_count"` from `"out"` doesn't make a difference; probably the `run_diagnostics` thing. I don't see any other problems (but I can't test)

**Comment by talagluck** [comment]
Thanks, @mielvds ! 

You can see how we use the metadata in [`build_gallery.py`](https://github.com/great-expectations/great_expectations/blob/develop/assets/scripts/build_gallery.py). We don't currently enforce the contents of metadata, since that could drastically increase external dependencies. For the moment, we just trust that users using an expectation in contrib review the documentation and determine which dependencies they will need to install. If you wanted to add a version dependency, the current best way would be to do in the `library_metadata` dictionary. If you have any additional ways of improving this experience or better managing requirements here, please let us know!

It appears that all tests are passing, so I think your tests are working as well. It does look like the rebase turned out a bit messy. Would you mind rebasing again to fix the commit history with this? Once you do that, I believe we'll be ready to approve and merge! Thanks for all of your updates!

**Comment by mielvds** [comment]
@talagluck seems ok now. Thanks!

**Review by talagluck — APPROVED** [review]
LGTM!

**Review by eugmandel — APPROVED** [review]
LGTM!

**Pull request merged**
