### PR TITLE
[ENHANCEMENT] Athena expect column quantile values to be between

### PR DESCRIPTION
**Pull request by RicardoPedrotti**
[ENHANCEMENT]

Changes proposed in this pull request:
The proposal of this pull request is to use the approx_percentile function to calculate the quantiles when using Athena as the backend. Also, a minor refactor on the ProgrammingError exception, removing repeated code.

image
Presto (Athena's engine) documentation for percentiles [https://prestodb.io/docs/current/functions/aggregate.html](https://prestodb.io/docs/current/functions/aggregate.html)

### CODE REVIEW

**Comment by eugmandel** [comment]
@RicardoPedrotti This is awesome - I am so happy to see you guys improving Athena support! We will take the PR up for review, please allow a few days, as we are dealing with the queue (a good problem to have :slightly_smiling_face: ).

**Comment by eugmandel** [comment]
@RicardoPedrotti We triaged today and @jcampbell will review it. Looking forward for merging! :)

**Comment by RicardoPedrotti** [comment]
Hey @eugmandel any news? We really want to start using it in our environment.

**Review by jcampbell — APPROVED** [review]

**Comment by jcampbell** [comment]
Apologies that I missed this one earlier!

**Comment by jcampbell** [comment]
@RicardoPedrotti I appear not to be able to push to the remote from which this PR is created; it'll merge as soon as the conflict is resolved (just need to bring in the latest changelog). I've done that already via rebase on a new branch athena_expect_column_quantile_values_to_be_between on origin, but want to leave this as the definitive PR if possible.

**Comment by RicardoPedrotti** [comment]
@jcampbell Done. Thanks for your message.

**Comment by RicardoPedrotti** [comment]
@jcampbell Please merge if everything is fine :)

**Comment by jcampbell** [comment]
Thank you! Sorry for the delay.

**Pull request merged**
