### PR TITLE
[CONTRIB] Multicolumns sum equal to single column

### PR DESCRIPTION
**Pull request by asafla**
### Expectation Name
expect_multicolumn_sum_values_to_be_equal_to_single_column

### Expectation Description

This expectation gets a list of n columns, in which we expect the sum of the first n-1th columns to be equal to the nth column.

This means that if one wants to compare between the sum of n-1 columns and the nth column, it needs to put the nth column at the end of the list.

### Definition of Done
Please delete options that are not relevant.

 * My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
 * I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
 * I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by asafla** [comment]
@cla-bot check

**Comment by asafla** [comment]
@cla-bot check

**Comment by anthonyburdi** [comment]
Thanks for this contribution @asafla! This is on my radar to review shortly.

**Review by anthonyburdi — APPROVED** [review]
LGTM! Thanks for this contribution. If you want to clean up some of the extraneous comments that might help with readability, but I won't block merge for that.

**Comment by asafla** [comment]
> LGTM! Thanks for this contribution. If you want to clean up some of the extraneous comments that might help with readability, but I won't block merge for that.

Oh, sorry about that, would do that on the next ones, thanks a lot !

**Pull request merged**
