### PR TITLE
[ENHANCEMENT] Removed the logic that prints the "This configuration object was built using version..." warning

### LINKED ISSUE #2333: Could "great_expectations project upgrade" update the "great_expectations_version" field?
After upgrading great_expectations to a new version, I get a lot of warnings like:
```
UserWarning: WARNING: This configuration object was built using version 0.13.4 of great_expectations, but is currently being validated by version 0.13.7.
```

When your project contains a lot of expectation suites, it is rather annoying to run `great_expectations suite edit`,  execute the notebooks and save all the expectations again.

Would it be possible for the `great_expectations project upgrade` command to also update the `great_expectations_version`-field of all expectation suites (the .json-files)? At least in situations when there has been no breaking changes (wrt. the format of the .json-files) between the two versions in question.

### PR DESCRIPTION
**Pull request by eugmandel**
### Changes proposed in this pull request:
Removed the logic that prints the "This configuration object was built using version..." warning when current version of GE is not the same as the one used to build the suite. 

This is not very helpful and annoying in the CLI. 

The problem that it was attempting to solve is still very valid: "Do the expectations in the suite still mean what they used to mean at the time the suite was created", but this is not the solution.

Prompted by this GH issue: https://github.com/great-expectations/great_expectations/issues/2333

### Previous Design Review notes:
- N/A
-
-

### CODE REVIEW

**Review by spbail — APPROVED** [review]
Discussed via Slack that we would want to address the problem of entirely missing config versions in a smarter way than this warning. Works for me.

**Comment by spbail** [comment]
Closing this PR temporarily to prevent triggering pipeline builds while debugging.

**Comment by spbail** [comment]
Builds are working again, reopening this.

**Comment by spbail** [comment]
yay, we got actual test failures - looks like some tests expect those warnings:
https://dev.azure.com/great-expectations/bedaf2c2-4c4a-4b37-87b0-3877190e71f5/_apis/build/builds/3507/logs/60


2021-02-02T13:12:45.4757380Z FAILED [None] tests.test_ge_utils/test_validate_using_data_context[PandasDataset]
2021-02-02T13:12:45.4757828Z FAILED [None] tests.test_ge_utils/test_validate_using_data_context_path[PandasDataset]
2021-02-02T13:12:45.4758448Z FAILED [None] tests.test_ge_utils/test_validate_using_data_context[sqlite] - ...
2021-02-02T13:12:45.4758873Z FAILED [None] tests.test_ge_utils/test_validate_using_data_context_path[sqlite]
2021-02-02T13:12:45.4759474Z FAILED [None] tests.test_ge_utils/test_validate_using_data_context[mysql] - F...
2021-02-02T13:12:45.4759921Z FAILED [None] tests.test_ge_utils/test_validate_using_data_context_path[mysql]

**Comment by jcampbell** [comment]
I think we need to at least consider adding the expectation-level version information before dropping this warning...

**Comment by jcampbell** [comment]
Updating my comment -- I think @eugmandel and @spbail were right--it's better to remove this noisy and useless warning even without yet adding version to the ExpectationConfiguration object (though we do want to do that!!)

**Review by jcampbell — APPROVED** [review]
pending only updating tests to be aware of the new behavior

**Pull request merged**
