### PR TITLE
[BUGFIX] [DOCS] New how-to guide: How to instantiate a Data Context on an EMR Spark cluster + Fixed broken documentation links in the project config template

### PR DESCRIPTION
**Pull request by eugmandel**
Changes proposed in this pull request:
- New how-to guide: How to instantiate a Data Context on an EMR Spark cluster. Once we release Alex's work, the process of running GE on EMR Spark will be much smoother. Still, having this how-to guide is an improvement on no documentation of that use case at all :). I verified that this procedure and the code snippet works on our EMR Spark cluster.
- Fixed broken documentation links in the project config template 
-

Previous Design Review notes:
- A sync conversation with @jcampbell and @alexsherstinsky 
-
-

### CODE REVIEW

**Review by jcampbell — CHANGES_REQUESTED** [review]
I think we should slim down the snippet so that the included config is more likely to be what someone who has already used GE would put into their notebook -- i.e. many of the "first time user" comments are removed.

I also think we should avoid importing ruamel and related specific machinery, keeping the recommended snippet to only the GE codebase.

Finally, I'd like to change the language at the beginning to avoid saying that the "default method" is CLI and making this sound like a workaround. Instead, I think this guide should be more matter-of-fact: to instantiate a data context without a full data context configuration *directory*, this is the recommended path.

**Comment by eugmandel** [comment]
> I think we should slim down the snippet so that the included config is more likely to be what someone who has already used GE would put into their notebook -- i.e. many of the "first time user" comments are removed.
> 
- Agree - will slim the snippet down.

> I also think we should avoid importing ruamel and related specific machinery, keeping the recommended snippet to only the GE codebase.
> 

- If we don't include the ruamel import, this will break the rule of our how-to guides that the code that we put there must work. We could switch away from having the yml version of the config in the snippet in favor of dictionaries - is this what you are advocating?

> Finally, I'd like to change the language at the beginning to avoid saying that the "default method" is CLI and making this sound like a workaround. Instead, I think this guide should be more matter-of-fact: to instantiate a data context without a full data context configuration _directory_, this is the recommended path.

-- Agreed - will update.

**Comment by eugmandel** [comment]
@jcampbell Re your comment 2 (not showing the yml machinery in the code snippet): after removing the comments from the yml, I see that the the justification for showing the yml version of the config no longer holds. 
I'll switch to passing the parts of the configuration as dictionaries to the c'tor of DataContextConfig.

**Comment by alexsherstinsky** [comment]
LGTM

**Comment by eugmandel** [comment]
@jcampbell Switched away from yml, removed all the "new user" comments, changed the intro language so that this guide does not sound like a workaround - please re-review.

**Review by jcampbell — APPROVED** [review]

**Pull request merged**
