### PR TITLE
Expect column values to be between

### PR DESCRIPTION
**Pull request by abegong**
Implements #109

### CODE REVIEW

**Comment by abegong** [comment]
Here's the commit history so far on this branch:

* 82e8100f : Change the output_format for the CLI to SUMMARY. Update unit tests to match.
* c70bbdef : Start updating `expect_column_values_to_be_between`. Bring some unit tests up to speed. WIP.
* 4b6982fb : Debugging + Merge from `develop`
* 07687553 : Bring all unit tests up to speed.
* 56e63e5d : Minor fixes
* a83075ae : Minor fixes
* 0f4a0074 : Minor fixes

Work still needed:
* Make sure `expect_column_values_to_be_between` matches the intended spec.
* Resolve the python 3 bug that's currently crashing

**Comment by abegong** [comment]
Okay, this now matches the intended spec.

The problem is type checking in python 3. The expectation includes lots of statements like this: `type(val) in [str, unicode]`

Since all strings are unicode in python 3, `unicode` isn't a thing. So we get a pile of NameErrors:
`NameError: name 'unicode' is not defined`

Working on a solution...

**Comment by abegong** [comment]
`from __future__ import unicode_literals`?

**Comment by jcampbell** [comment]
Sorry not to have commented here earlier. Two thoughts:
- It seems to me we should move the type-checking logic outside of the `is_between` function so it's not done on each row (rather, once when the expectation is run to validate the arguments).
- What about just checking that `type(min_value) == type(max_value)`

**Comment by jpcampb2** [comment]
Sorry not to have commented here earlier. Two thoughts:

It seems to me we should move the type-checking logic outside of the is_between function so it's not done on each row (rather, once when the expectation is run to validate the arguments).
What about just checking that `type(min_value) == type(max_value)`

**Review by jpcampb2 — APPROVED** [review]
LGTM!

**Pull request merged**
