### PR TITLE
[DOCS] Note about creating backup of Checkpoints

### PR DESCRIPTION
**Pull request by Shinnnyshinshin**
Changes proposed in this pull request:
- Added note about recommendation to create backup of V2 Checkpoints
- GREAT-437

### Definition of Done
Please delete options that are not relevant.
- [x] I have made corresponding changes to the documentation

Thank you for submitting!

### CODE REVIEW

**Review by NathanFarmer — COMMENTED** [review]
Do they know where the checkpoints are stored? What files specifically do they backup?

**Review by alexsherstinsky — APPROVED** [review]
LGTM (subject to responding to @NathanFarmer 's question).  Thanks!

**Comment by Shinnnyshinshin** [comment]
Thank you for the catch @NathanFarmer and @alexsherstinsky please have a look at the most recent commit

**Review by NathanFarmer — APPROVED** [review]
LGTM!

**Pull request merged**
