### PR TITLE
[BUGFIX] Fix black conflict, upgrade black, make import optional

### LINKED ISSUE #2028: [BUG] pip install -r requirements-dev.txt failure
**Describe the bug**
When I set up a contribution environment according to the [documentation](https://docs.greatexpectations.io/en/latest/contributing/setting_up_your_dev_environment.html#contributing-setting-up-your-dev-environment), I run into the issue below when I run `pip install -r requirements-dev.txt.`

```ERROR: Double requirement given: black==19.10b0 (from -r requirements-dev-test.txt (line 6)) (already in black>=19.10b0 (from -r requirements.txt (line 7)), name='black')```

**To Reproduce**
1. Set up new environment using python3 venv
2. `pip install -r requirements-dev.txt.` after forking repo and following other steps in setting up development environment [documentation](https://docs.greatexpectations.io/en/latest/contributing/setting_up_your_dev_environment.html#contributing-setting-up-your-dev-environment)

**Expected behavior**
When I run `pip install -r requirements-dev.txt.` in a fresh environment it should run install all necessary dependencies.

**Environment (please complete the following information):**
 - iOS

### PR DESCRIPTION
**Pull request by anthonyburdi**
# Core issue
There is a conflict with our package requirements and dev environment requirements. This closes #2028, #1999 among others.

Black is used both to lint/format code in our pre-commit hooks and CI pipeline and also as a formatter in a handful of places in the core GE codebase.

Note: see also #2052 

# Possible solutions
1. Remove black from `lint_code()` and requirements.txt, replace with suitable alternative (yapf, autopep8)
	1. I don't think this is desirable since then we will have to maintain two separate linting/formatting dependencies and potentially two different formats.
2. **THIS PR** Pin updated `20.8.b1` version of black in requirements.txt, remove from requirements-dev-test.txt
	1. Remove `black` from requirements-dev-test.txt since if someone is installing `requirements-dev.txt` they will also get `requirements.txt`. They will only not get black if they install JUST `requirements-dev-test.txt` which I don't believe will be useful on it's own anyway. In fact in all environments in our CI that install `requirements-dev-test.txt` also install `requirements.txt`.
3. Pin black in both requirements.txt and `requirements-dev-test.txt`, update black to latest version `20.8.b1`
	1. See above rationale for removing `black` from `requirements-dev-test.txt`
4. Remove formatting capability from GE
	1. Non-starter, we could remove the checkpoint functionality since `checkpoint_script_template.py` is already linted - but formatting is needed for notebook rendering.
5. Solution 2 but without upgrading to the latest version
	1. The version we are currently on `19.10b0` is over a year old, and the latest version supports Python 3.8 code and fixes many issues. It's never fun to bonk our git blame with a full codebase lint but we don't want to fall too far behind.

## Where is black used?
- `great_expectations.util.lint_code(code)`
	- Lints code passed as a string using black
- `great_expectations.cli.checkpoint._write_checkpoint_script_to_disk()`
	- This takes a file in our repo `checkpoint_script_template.py` and reads it as a string, adds the context_directory and checkpoint_name then formats it using `lint_code()`
- `great_expectations.render.renderer.suite_edit_notebook_renderer.SuiteEditNotebookRenderer.add_code_cell()`
	- `lint_code()` when adding a code cell in notebook renderer

### CODE REVIEW

**Comment by jcampbell** [comment]
I think upgrading black in our repo is good. No concern there.

I would prefer to slim down our dependencies, and go with something like "1.5" in the options you put out there. Specifically, we could make linting autogenerated notebooks optional, by wrapping the import and linting action in a try block.

I'm generally opposed to pinning versions in our *requirements* because then we are more likely to be incompatible with other libraries (admittedly, pinned black is (somewhat?) more rare).

No concern on the pain of linting; we can just run the new black against the PR branches. We may want to offer to do that for contributors.

**Comment by anthonyburdi** [comment]
> I think upgrading black in our repo is good. No concern there.
> 
> I would prefer to slim down our dependencies, and go with something like "1.5" in the options you put out there. Specifically, we could make linting autogenerated notebooks optional, by wrapping the import and linting action in a try block.
> 
> I'm generally opposed to pinning versions in our _requirements_ because then we are more likely to be incompatible with other libraries (admittedly, pinned black is (somewhat?) more rare).
> 
> No concern on the pain of linting; we can just run the new black against the PR branches. We may want to offer to do that for contributors.

Thanks for the review @jcampbell!!
So just to clarify, to make the linting optional we would:
1. remove `black` from requirements.txt, 
2. wrap `black` imports (probably in `lint_code()`) in a try block (). 
3. ~~remove the lint step for the checkpoint template (at some point this can be slimmed down and reconfigured to use BaseDataContext.run_checkpoint())~~
4. Add `black` (upgraded) to our `requirements-dev-test.txt` to handle testing the `lint_code()` method with the optional dependency installed.

`black` would then be removed from requirements.txt and only exist in our CI and local test environment (`requirements-dev-test.txt`), pre-commit hooks and CI lint step. If someone wanted to use linting in autogenerated notebooks they would have to install `black` separately.

Does that sound right?

**Comment by Shinnnyshinshin** [comment]
Looks wonderful :) I just wanted to organize my understanding: 

black was 
1. upgraded in `pre-commit-config.yaml`
2. upgraded in `azure-pipelines.yml`
3. upgraded and marked as required in `requirements-dev-test.txt`
4. upgraded and but commented out in `requirements.txt`

5. upgraded in `/docs/requirements.txt`

- my question had to do with # 5. Does this include all requirements in both the `requirements.txt` and `requirements-dev*.txt`? And is that why it was included?

- PS. and please let me know if I'm missing something from here

**Comment by anthonyburdi** [comment]
> Looks wonderful :) I just wanted to organize my understanding:
> 
> black was
> 
>     1. upgraded in `pre-commit-config.yaml`
> 
>     2. upgraded in `azure-pipelines.yml`
> 
>     3. upgraded and marked as required in `requirements-dev-test.txt`
> 
>     4. upgraded and but commented out in `requirements.txt`
> 
>     5. upgraded in `/docs/requirements.txt`
> 
> 
>     * my question had to do with # 5. Does this include all requirements in both the `requirements.txt` and `requirements-dev*.txt`? And is that why it was included?
> 
>     * PS. and please let me know if I'm missing something from here

Correct!
Great question! Regarding your question about number 5, `/docs/requirements.txt` is used when someone wishes to build documentation locally, see the [If you want to build documentation locally:](https://docs.greatexpectations.io/en/latest/contributing/setting_up_your_dev_environment.html#optional-configure-resources-for-testing-and-documentation) section of our "Setting up your dev environment" page. I'm not 100% certain exactly why `black` is included in the `docs/requirements.txt` but I think it is because during the docs build process GE is imported, and thus any dependencies also need to be installed in the build environment. Now that black is an optional requirement this may be fine to comment out. I'm going to test locally and report back.

**Comment by Shinnnyshinshin** [comment]
> > Looks wonderful :) I just wanted to organize my understanding:
> > black was
> > ```
> > 1. upgraded in `pre-commit-config.yaml`
> > 
> > 2. upgraded in `azure-pipelines.yml`
> > 
> > 3. upgraded and marked as required in `requirements-dev-test.txt`
> > 
> > 4. upgraded and but commented out in `requirements.txt`
> > 
> > 5. upgraded in `/docs/requirements.txt`
> > 
> > 
> > * my question had to do with # 5. Does this include all requirements in both the `requirements.txt` and `requirements-dev*.txt`? And is that why it was included?
> > 
> > * PS. and please let me know if I'm missing something from here
> > ```
> 
> Correct!
> Great question! Regarding your question about number 5, `/docs/requirements.txt` is used when someone wishes to build documentation locally, see the [If you want to build documentation locally:](https://docs.greatexpectations.io/en/latest/contributing/setting_up_your_dev_environment.html#optional-configure-resources-for-testing-and-documentation) section of our "Setting up your dev environment" page. I'm not 100% certain exactly why this is included in the docs but I think it is because during the docs build process GE is imported, and thus any dependencies also need to be installed in the build environment. Now that black is an optional requirement this may be fine to comment out. I'm going to test locally and report back.

Ah ok. Thanks for the clarification :) Once we have an answer (which ever it is) I'd be more than happy to click approve. Please let me know

**Comment by anthonyburdi** [comment]
> > > Looks wonderful :) I just wanted to organize my understanding:
> > > black was
> > > ```
> > > 1. upgraded in `pre-commit-config.yaml`
> > > 
> > > 2. upgraded in `azure-pipelines.yml`
> > > 
> > > 3. upgraded and marked as required in `requirements-dev-test.txt`
> > > 
> > > 4. upgraded and but commented out in `requirements.txt`
> > > 
> > > 5. upgraded in `/docs/requirements.txt`
> > > 
> > > 
> > > * my question had to do with # 5. Does this include all requirements in both the `requirements.txt` and `requirements-dev*.txt`? And is that why it was included?
> > > 
> > > * PS. and please let me know if I'm missing something from here
> > > ```
> > 
> > 
> > Correct!
> > Great question! Regarding your question about number 5, `/docs/requirements.txt` is used when someone wishes to build documentation locally, see the [If you want to build documentation locally:](https://docs.greatexpectations.io/en/latest/contributing/setting_up_your_dev_environment.html#optional-configure-resources-for-testing-and-documentation) section of our "Setting up your dev environment" page. I'm not 100% certain exactly why this is included in the docs but I think it is because during the docs build process GE is imported, and thus any dependencies also need to be installed in the build environment. Now that black is an optional requirement this may be fine to comment out. I'm going to test locally and report back.
> 
> Ah ok. Thanks for the clarification :) Once we have an answer (which ever it is) I'd be more than happy to click approve. Please let me know

Happy to report that removing `black` from docs/requirements.txt still allowed me to build docs (in a fresh environment only installing `docs/requirements.txt`)! I just pushed a commit removing it. Great catch!

**Comment by Shinnnyshinshin** [comment]
approved!

**Review by Shinnnyshinshin — APPROVED** [review]

**Pull request merged**
