### PR TITLE
Display table in cramers phi expectation result

### PR DESCRIPTION
**Pull request by mlondschien**
With help by @jcampbell.

This PR adds the crosstab table used to compute the cramers phi value for the `expect_column_pair_cramers_phi_to_be_less_than` expectation to the data docs.

### CODE REVIEW

**Comment by mlondschien** [comment]
Screenshot of the crosstab displayed in DataDocs here:
Screenshot from 2020-09-20 14-29-39

**Comment by mlondschien** [comment]
The rows are not ordered. Improving the spacing in the table would be nice though.

**Comment by jcampbell** [comment]
@mlondschien -> would you like to update this to sort rows and/or adjust spacing? I think it's also okay to merge.

**Comment by mlondschien** [comment]
Thanks @jcampbell. Using categoricals the ordering is fixed, I forgot to update the screenshot. If we can fix the spacing that would be great. If not, we could also tackle that in a different PR.

**Review by jcampbell — APPROVED** [review]

**Pull request merged**
