### PR TITLE
[BUGFIX] Use correct schema to fetch table and column metadata

### PR DESCRIPTION
**Pull request by armaandhull**
Changes proposed in this pull request:
- Use schema provided via the prompt in `great_expectations suite` creation flow to get metadata about table and columns

### CODE REVIEW

**Comment by Shinnnyshinshin** [comment]
Thank you very much for catching this @armaandhull

**Review by Shinnnyshinshin — APPROVED** [review]
approved

**Comment by Shinnnyshinshin** [comment]
We should have a release that includes these changes by tomorrow (1/21/21) @armaandhull

**Comment by armaandhull** [comment]
sounds good, thanks @Shinnnyshinshin :)

**Comment by Shinnnyshinshin** [comment]
Hi @armaandhull wanted to follow up. GE 0.13.6 has been released on PyPi. You should be able to download it at the following link :

https://pypi.org/project/great-expectations/0.13.6/

Thanks again for your help with this bug

**Comment by armaandhull** [comment]
oh awesome, glad to have contributed! :)

**Comment by alessandrolacorte** [comment]
@armaandhull Hello. Please when renaming variables, use the editors `replace` functionality. A bug was introduced because you manually changed variable names. My suggestion, use an editor (i.e. Pycharm) which replaces the variable for you and prevents this kind of issues
FYI @Shinnnyshinshin 
PR to fix it: https://github.com/great-expectations/great_expectations/pull/2302

**Pull request merged**
