### PR TITLE
DOC: fix broken link referencing remove_expectation method

### PR DESCRIPTION
**Pull request by NimaVaziri**

### CODE REVIEW

**Comment by eugmandel** [comment]
@NimaVaziri Thank you for submitting this PE - we will review this week!

**Review by eugmandel — APPROVED** [review]
Thank you for catching this!

**Comment by NimaVaziri** [comment]
Hey @eugmandel as this change set is only on documentation, I'm not sure how the CI failures are relevant?

Is there something I'm overlooking that I need to fix?

**Comment by eugmandel** [comment]
> Hey @eugmandel as this change set is only on documentation, I'm not sure how the CI failures are relevant?
> 
> Is there something I'm overlooking that I need to fix?

I believe the CI error was unrelated to your change :).

**Comment by spbail** [comment]
Looks like those were actual test failures that contained the old URL, I just updated them too.

**Comment by spbail** [comment]
We did it 👍

**Comment by NimaVaziri** [comment]
Ah ok, thanks @spbail!

**Pull request merged**
