### PR TITLE
[DOCS] Updates Custom Expectation docs w/ code snippets

### PR DESCRIPTION
**Pull request by austiezr**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- Fixes several broken code refs in custom expectation docs
- Introduces & expands snippet tags in custom expectation docs

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Review by alexsherstinsky — APPROVED** [review]
LGTM

**Review by rdodev — APPROVED** [review]
Approving for now, but this screams we need to find a more sustainable way to do this than line number reference.

**Review by talagluck — CHANGES_REQUESTED** [review]
I believe we have a different way of referencing code snippets nowadays that should be more robust. You can see an example in #6362

**Review by Rachel-Reverie — APPROVED** [review]
The netlify preview looks good!

One minor thing on the code side: I noticed in your snippets you go back and forth between including the file path as part of the snippet name.  I don't believe that we've made it an official piece of style guidance, but I prefer the convention of including the file path in the snippet name since it makes it easier to reference when doing edits, and ensures there is no accidental name collision if two files have snippets for a similar bit of code.  If it wouldn't be a major lift to update these, I'd appreciate it -- but I don't think it's a blocking thing, either. (I know there are a few other docs from when we first introduced named snippets that don't include the file paths, so I intend to have a PR for adding those in as a bulk task.)

**Comment by austiezr** [comment]
No that's a fair point! I initially named the template snippets thinking they would be more user-facing, and the filepath felt overwhelming in that context; now that they're re-orged, totally agree on keeping to the filepath pattern. Will update!

**Review by talagluck — APPROVED** [review]
I haven't gone through in detail, but approving since my previous request has been satisfied, and because this has a few other approvals already.

**Pull request merged**
