### PR TITLE
[MAINTENANCE]:  fix path for url in template

### PR DESCRIPTION
**Pull request by gauthamzz**
fixed the path to the docs.

### CODE REVIEW

**Comment by gauthamzz** [comment]
@cla-bot check

**Comment by gauthamzz** [comment]
@cla-bot check

**Review by eugmandel — APPROVED** [review]
Thank you, @gauthamzz !

**Comment by gauthamzz** [comment]
@cla-bot check

**Comment by eugmandel** [comment]
@gauthamzz Looks like the bot does not see the CLA agreement yet?

**Comment by gauthamzz** [comment]
@cla-bot check

**Comment by gauthamzz** [comment]
> @gauthamzz Looks like the bot does not see the CLA agreement yet? 

I filled it 3-4 times already. Something is wrong I guess.

**Comment by gauthamzz** [comment]
It worked 🙈

I thought I had filled it. Something must have gone wrong.

**Comment by eugmandel** [comment]
> It worked 🙈
> 
> I thought I had filled it. Something must have gone wrong.

Must have been a bot hiccup - works now.

**Pull request merged**
