### PR TITLE
[BUGFIX] Fix spark configuration not getting passed to the SparkSession builder

### LINKED ISSUE #2104: spark_context yaml key does not pass configuration to spark
**Describe the bug**
The [spark_context](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources/how_to_configure_a_self_managed_spark_datasource.html?highlight=spark_context#additional-notes) option for a spark datasource in the .yml config file does not work. Configuration options passed through it will not take effect on the resulting SparkContext object. 

This is problematic for a number of spark usecases, eg: if you want to read files from S3 you need to have spark install hadoop-aws libraries. Typically this is done through `SparkSession.builder.config`, which is what `spark_context` should be passing its arguments to.

**To Reproduce**
1. Create a spark datasource with non-default `spark_context` arguments eg:
```
  spark_dataframe:
    data_asset_type:
      class_name: SparkDFDataset
      module_name: great_expectations.dataset
    class_name: SparkDFDatasource
    module_name: great_expectations.datasource
    spark_config:
      spark.jars.packages: 'org.apache.hadoop:hadoop-aws:2.7.3'
      spark.hadoop.fs.s3a.impl: 'org.apache.hadoop.fs.s3a.S3AFileSystem'
      spark.hadoop.fs.s3.impl: 'org.apache.hadoop.fs.s3a.S3AFileSystem'
```
2. Start a great expectations action in the CLI that uses the spark datasource eg: `great_expectations suite new`
3. Select the spark datasource you configured and hit enter. This will start the spark server locally.
4. Visit the spark UI (typically at localhost:4040) and go to the `Environment` tab
5. Search for spark.jars.packages, it will not be found.

**Expected behavior**
spark.jars.packages to exist in the spark.properties section in the environment tab and be populated with the argument  `org.apache.hadoop:hadoop-aws:2.7.3`

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - GE Version: 0.12.9
 - Spark Version 2.4.5

### PR DESCRIPTION
**Pull request by EricSteg**
**Changes proposed in this pull request:**
- Changed `DatasourceConfigSchema` attribute `spark_context` to `spark_config` which matches the attribute name expected by `SparkDFDatasource`. ([example](https://github.com/great-expectations/great_expectations/blob/6cd804579baed5906513245520bf6e5c0b23c5b9/great_expectations/datasource/sparkdf_datasource.py#L140))
- Updated documentation to reflect the above change.
- Added a non-default spark configuration example to the documentation.

**Notes:**
- Closes #2104 

Since both `spark_context` and `spark_config` were referenced in code and documentation a choice needed to be made which one was kept. Sticking with `spark_config` meant less code changes and also in my opinion, is a more exact name for what the attribute represents; config options to be set on the SparkSession builder. "SparkContext" is a different concept in the Spark framework.

### CODE REVIEW

**Comment by EricSteg** [comment]
@cla-bot check

**Comment by alexsherstinsky** [comment]
@EricSteg Your changes make a lot of sense.  However, I just got a PR in, which would require for you to make updates.  Once you do this, I think that this would be a perfect fix -- I was just thinking the same with another user here: [https://github.com/great-expectations/great_expectations/pull/2125](url).  Could you please add me as a reviewer once you update the files?  Thank you very much!

**Comment by alexsherstinsky** [comment]
@EricSteg thank you for making the changes.  Please let me know if you are not sure how to handle the Lint errors -- I can help you with that.  Regarding the other error, please take a look, and if this is something that you would need assistance with, please let me know as well.  Thank you!

**Comment by EricSteg** [comment]
Thanks @alexsherstinsky. The gear button to add reviewers seems to be missing for me, but it's passed all the tests now.

**Comment by alexsherstinsky** [comment]
> Thanks @alexsherstinsky. The gear button to add reviewers seems to be missing for me, but it's passed all the tests now.

Thank you @EricSteg -- it appears that you already added me as a reviewer -- if that is what you wanted, then it worked!  Thanks!

**Review by alexsherstinsky — APPROVED** [review]
This is great!  LGTM!  Thank you so much, @EricSteg !

**Review by eugmandel — APPROVED** [review]
@EricSteg Thank you so much for jumping on this so quickly!

**Comment by EricSteg** [comment]
No problem, thanks for the quick reviews!

**Pull request merged**
