### PR TITLE
feat: remove accidental new line in .ge_store_backend_id

### PR DESCRIPTION
**Pull request by dnz-bdeboer**
Changes proposed in this pull request:
- `.ge_store_backend_id` looks like a text file with key value pairs, but isn't really.
- it's value is read directly, and if it has a new line, you get the very odd error: 
```
ValueError:
badly formed hexadecimal UUID string

...

data_context_id must be a valid uuid
```
- I had a perfect working setup on my machine, but after checking it into git and running it on another, it failed wit this error.
- What happened? After many hours of debugging I figured out that my `pre-commit` hook had added a new line to `.ge_store_backend_id`, as I had the end-of-file-fixer hook enabled.
- This took my hours of debugging, as I had no clue what was going on. 
- If I had known this was a thing I would obviously have excluded this file in `.pre-commit-config.yaml`.

But by removing newlines hopefully nobody will ever see this error again.

### CODE REVIEW

**Comment by dnz-bdeboer** [comment]
@cla-bot check

**Comment by dnz-bdeboer** [comment]
@cla-bot check

**Comment by Shinnnyshinshin** [comment]
Hi @dnz-bdeboer  I saw that the `docusaurus_tests` stage in the pipeline was failing. This is due to a recent change to Azure on our end. Please merge the most recent changes from `/develop` and you should be good to go :)

**Comment by dnz-bdeboer** [comment]
And indeed, all working now!

> I saw that the docusaurus_tests stage in the pipeline was failing. This is due to a recent change to Azure on our end. Please merge the most recent changes from /develop and you should be good to go :)

**Comment by jcampbell** [comment]
Thank you so much for digging into that!! This makes me also wonder whether we should improve the handling when parsing that file...what do you think @anthonyburdi ?

**Review by jcampbell — APPROVED** [review]
Thank you!

**Comment by anthonyburdi** [comment]
> Thank you so much for digging into that!! This makes me also wonder whether we should improve the handling when parsing that file...what do you think @anthonyburdi ?

@jcampbell - is this along the lines of what you were thinking? https://github.com/great-expectations/great_expectations/pull/2952

**Pull request merged**
