### PR TITLE
add option to suppress a test for a specified dataset types (e.g., Pa…

### PR DESCRIPTION
**Pull request by ccnobbli**
…ndas, SQLalchemy). Sister test to make sure this option works.

This is in response to different expected behavior for #352 in SQLAlchemy and Pandas.

This is an optional Test Parameter where you list the Dataset types to ignore, i.e., the test is not run for that Dataset type.

### CODE REVIEW

**Comment by ccnobbli** [comment]
Wait, I just realized that the test isn't being performed - let me fix that before review

**Comment by jpcampb2** [comment]
LMK when this is good to review!

**Comment by ccnobbli** [comment]
should be gtg

**Comment by jpcampb2** [comment]
Should this PR now also remove the previous mechanism for doing this (listing it in the tests to skip section)?

**Comment by jpcampb2** [comment]
Since this targets individual test conditions instead of entire expectations, makes sense to leave both in here!

**Comment by ccnobbli** [comment]
minor detail here: would y'all prefer to suppress tests in this format: 
`"suppress_test_for": ["SQLAlchemy"] `
 or like
`"suppress_test_for": ["SQLAlchemyDataset"]` 

I prefer the first for brevity/clarity but the latter is actually consistent with the actual dataset types.

Not a big deal, but I could see this being a potential pain point later on if it's not addressed now.

**Review by jpcampb2 — APPROVED** [review]
LGTM

**Pull request merged**
