### PR TITLE
[FEATURE] Add new result_format to include unexpected_row_list

### LINKED ISSUE #3195: Support to include ID/PK in validation result for each row that failed an expectations
**Is your feature request related to a problem? Please describe.**
When an expectation is run the output includes a “partial_unexpected_list” property of values that were unexpected. While this is useful, in most cases, it doesn't allow teams to identify, resolve, or divert data with poor quality.

It would be great if a sample list or a complete list (result_format SUMMARY, COMPLETE) of ID's for each row that failed an expectation was included in the validation result.

**Describe the solution you'd like**
One could include a column name as an argument in the expectation that they would like to be included in the "partial_unexpected_list" (or a new property).

**Describe alternatives you've considered**
One could try infer the PK for a table but this is not possible for all engine types E.g. Spark. 

**Additional context**
Enabling teams to not only bring light to data quality issues but identify all rows allows them to address poor data quality in real-time instead of requiring manual intervention.

### PR DESCRIPTION
**Pull request by talagluck**
Changes proposed in this pull request:
- This draft PR links up the logic to return the full unexpected row list when validation results format is COMPLETE
- It is possible that adding this to the `COMPLETE` `result_format` runs the risk of returning really large objects (since it would return the entire row), and so we may want to add a new result_format type that does this instead.

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.

Thank you for submitting!

### CODE REVIEW

**Comment by KentonParton** [comment]
@talagluck This was a quick turnaround, nice work!

**1. Returning each row that fails a validation VS returning a primary key/composite keys**

As you mentioned above, this runs the risk of returning a large dataset. The worst case scenario would be if all validations failed for all rows in the dataset. This would result in a result set of `table_size * num_failing_validations`. A way to reduce this would be to return an aggregated result set. For example, if a row failed validation for expectation A and expectation B, the row would only be returned once. This wouldn't suite the existing structure of `result_format` so it would likely have to be at the validation suite level instead. This would reduce the result set to `table_size * 1`

Returning the entire row seems like the simpler solution but not scalable especially in non Airflow/Spark pipelines.

If we were to go the route of allowing a list of columns denoting the columns to be included in the result_format, this would support primary and composite keys and likely reduce the result set significantly. Having this option in the expectation kwargs seems like the best place to put it as you may not want it on all expectations. Maybe we only want to exclude data that fails expectation A but not B.



**2. How would the result set be used downstream and are there benefits to having the entire row vs pk/ck**

Once we get this data there has to be a downstream process to do something with it. If it were in an Airflow/Spark pipeline, you could filter the original batch data on the ID's of the rows that failed. Then you would have two DF's, one containing data that passed validation and one that failed. Not quite sure how this would scale. The same logic could apply in a non pipeline environment but some task would be triggered to do some processing.

To achieve the above I don't believe having the entire row helps. If anything it makes it more challenging because you still need to store the column name/s of the pk/ck's somewhere while the other approach you have the list of pk's/ck's in GE expectation kwargs.

Having the entire row could be useful if someone is going to manually look through the failing rows to review it.

**Comment by talagluck** [comment]
Thanks so much for this feedback, @KentonParton ! I commented on the issue as well, but your points are well-taken. We are currently looking at adding a new `result_format` option, which would return all of the rows, but would need to be explicitly set by users, so this should mitigate the risk of users accidentally return an entire tables worth of data with every failed validation :) We are also looking at implementing the original request whereby a user could specify a list of columns to return in the event of `unexpected_rows`. This seems doable, but goes pretty deep in our architecture since it would affect every `map_expectation`, and so will take some more time to implement.

**Comment by abekfenn** [comment]
@talagluck should https://github.com/great-expectations/great_expectations/issues/3225 be re-opened to reflect this open PR?

Also, I was taking a look at the associated commits and didn't notice that unexpected_index_list was expected in tests/expectations/metrics/test_map_metric.py :`test_pandas_unexpected_rows_complete_result_format` 

Am I misunderstanding something? I would expect that unexpected_index_list should be returned given the working definition of result_format COMPLETE. This would also be sure to fix my use case in #3225

P.S. Let me know if I can help update documentation to get this into the next build

**Comment by talagluck** [comment]
Hi @abekfenn - thanks for taking a look here!

Responding to each of your points:

> @talagluck should #3225 be re-opened to reflect this open PR?

This PR is adding a new feature (the addition of the entire row of data for each unexpected value), and so is not linked to that PR, other than that they both pertain to `result_format`.

> Also, I was taking a look at the associated commits and didn't notice that unexpected_index_list was expected in tests/expectations/metrics/test_map_metric.py :test_pandas_unexpected_rows_complete_result_format

This PR is very much a WIP and so I just converted it to Draft to make that more explicit.

> Am I misunderstanding something? I would expect that unexpected_index_list should be returned given the working definition of result_format COMPLETE. This would also be sure to fix my use case in #3225

I just revisited your comment in that PR. Apologies, I think I zoomed in on a couple of details which seemed related to existing (but separate) bugs, and missed the main point you were making. I believe the issue here is the difference between the output of each function `validator.expect_...` compared with the `__repr__` method. I believe that if you run `print(validator.expect_...)` instead of just `validator.expect_...`, you should see the entirety of the results. Please confirm that this works for you. If you feel that this design is different than what you would expect, please feel free to open an issue! Then I can use that to begin an internal conversation.

Thanks!

**Review by alexsherstinsky — APPROVED** [review]
LGTM

**Pull request merged**
