### PR TITLE
[FEATURE] SqlAlchemy engine support for column.most_common_value metric

### PR DESCRIPTION
**Pull request by shpolina**
Changes proposed in this pull request:
 * This PR adds SqlAlchemy engine support for column.most_common_value metric 

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by talagluck** [comment]
Hi @shpolina, this is awesome - thank you so much for your contribution! I will take a look in the next day or two and will reach out with any follow-ups.

**Review by talagluck — CHANGES_REQUESTED** [review]
Hi @shpolina - this is awesome!

One request - could you update the tests for this expectation to also test for sqlalchemy? Some background: 
We use json test fixtures to test our expectations. You can see these in 
`tests/test_definitions.` Currently, this expectation is only being tested for pandas.
To test this file for sqlalchemy, you need to do two things:
1. Turn on the testing of this file by going to `great_expectations/self_check/util.py` and in the function `candidate_test_is_on_temporary_notimplemented_list_cfe`, comment out this expectation in the if statement for sqlite, etc. (~L1237).
2. Add schemas for sqlite and postgresql to the json test file: `tests/test_definitions/column_aggregate_expectations/expect_column_most_common_value_to_be_in_set.json`.  You can see examples of such schemas in the json test file for `expect_column_min_to_be_between`.

Once you do this, that should turn on testing for this expectation, and when you run `tests/test_definitions/test_expectations_cfe.py` you should see that this expectation is run with that test_runner rather than being skipped. Does that make sense? Please feel free to reach out if you have any questions or issues!

**Comment by shpolina** [comment]
@talagluck thank you for the detailed explanation. I believe I enabled the tests, please let me know if anything else is needed.

**Review by talagluck — APPROVED** [review]
Thanks so much for the quick update, @shpolina ! This looks awesome. I'm approving and will merge as soon as it's ready. Thank you again for your contibution!

**Pull request merged**
