### PR TITLE
[ENHANCEMENT] BigQuery integration should use a view instead of a table

### PR DESCRIPTION
**Pull request by alessandrolacorte**
Changes proposed in this pull request:

The BigQuery Integration should use a view instead of a table, for cost reasons. With the current implementation, it creates a temporary table, which could be a copy of the original table. In BigQuery, you pay for the amount of data scanned, so in the case of tables with TBs of data, it can become very expensive. The alternative is to use a view, which incurs in no cost of duplicating the source table.

### CODE REVIEW

**Comment by eugmandel** [comment]
@alessandrolacorte Thank you for submitting this PR! We will review it this week.

**Comment by eugmandel** [comment]
@alessandrolacorte GE stores the results of a query in a table to make it faster to run queries against it (during validation). Do you know if using a view instead of a table will preserve the execution speed?

**Comment by alessandrolacorte** [comment]
> @alessandrolacorte GE stores the results of a query in a table to make it faster to run queries against it (during validation). Do you know if using a view instead of a table will preserve the execution speed?

Hello! I can guarantee that the view will preserve the execution speed. We can go into the details of how BigQuery works and how Dremel (the BigQuery engine) generates the execution plan, but that might be of an overkill.
In essence, views in BigQuery are not materialized and they have zero execution penalty, it is as fast as querying the underlying table.

**Comment by eugmandel** [comment]
@alessandrolacorte Awesome - will merge and it will go out with today's release.

**Review by alexsherstinsky — APPROVED** [review]
LGTM

**Pull request merged**
