### PR TITLE
Drop ge_on_teams

### PR DESCRIPTION
**Pull request by abegong**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Drop "Using Great Expectations on teams"

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
- Discussed offline with @spbail 
- My reasoning: This doc is almost entirely redundant with the structure of the Getting Started tutorial. I don't think we want to maintain multiple versions of that info.
- He response: "There's value in having a "how to use GE collaboratively" workflow doc, but this ain't it."

Thank you for submitting!

### CODE REVIEW

**Review by spbail — CHANGES_REQUESTED** [review]
You'll also need to remove the link from the workflows_patterns.rst landing page (and one day we'll switch to looping over child pages instead of explicitly listing them ;) )

**Comment by jcampbell** [comment]
@spbail  -> please merge when your issue is addressed!

@abegong -> what is "He response, ..."

**Comment by abegong** [comment]
*Her response

**Comment by abegong** [comment]
@spbail Good catch.

Fixed and ready to merge.

**Review by spbail — APPROVED** [review]
👍

**Pull request merged**
