### PR TITLE
implement SQA `expect_column_value_lengths_to_equal` as well as tests

### PR DESCRIPTION
**Pull request by ccnobbli**
Added new json-ified tests because there didn't seem to be any for this expectation type

### CODE REVIEW

**Review by abegong — APPROVED** [review]
This looks good.

It raises a new question: what's the expected error state if an expectation is called on a bad data type (e.g. a float). Will that be consistent between pandas, SQL, and other execution contexts? Should it?

I vote we merge this, and start a discussion on errors and typing in the issues.

**Comment by jpcampb2** [comment]
Random here, but any idea why we're back in the regime of coverage decreasing? @ccnobbli could you dive through the coverage report to figure out what's going on and note whether this is good or bad or indifferent?

**Comment by abegong** [comment]
Going ahead with the merge...

**Comment by nobbyhawk** [comment]
@jpcampb2 I think I found it: somewhere the `expect_column_value_lengths_to_be_between` SQA expectation lost it's decorator. I misinterpreted the failing tests for that expectation to signify that the code for that expectation hadn't been merged into `develop`, so I just re-added it to the temporary unimplemented list. To solve those issues I threw in the decorator and took it off the unimplemented list!

Quick fix - it just needed some fresh eyes!

**Comment by ccnobbli** [comment]
@jpcampb2 I think I found it: somewhere the expect_column_value_lengths_to_be_between SQA expectation lost it's decorator. I misinterpreted the failing tests for that expectation to signify that the code for that expectation hadn't been merged into develop, so I just re-added it to the temporary unimplemented list. To solve those issues I threw in the decorator and took it off the unimplemented list!

Quick fix - it just needed some fresh eyes!

**Comment by jpcampb2** [comment]
Awesome, thanks for figuring out why there was a problem--looks like coverage actually helped us!

**Pull request merged**
