### PR TITLE
[DOCS] Fixed erroneous/broken link to Discourse

### PR DESCRIPTION
**Pull request by AntoineRondelet**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- As per the title, this PR fixes the link to GE's Discourse to remove the erroneous underscore. Note, not sure how the reStructuredText files are generated. There are occurrences of the erroneous URL there as well (see: https://github.com/great-expectations/great_expectations/blob/develop/docs_rtd/guides/how_to_guides/creating_and_editing_expectations/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters.rst)

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done

- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code

Thank you for submitting!

### CODE REVIEW

**Comment by Rachel-Reverie** [comment]
Hello @AntoineRondelet! We've looked over these changes, and they look good.  If you'll sign one of the contributor license agreements mentioned in the earlier comment by @ge-cla-bot, we'll be able to approve this update and merge it in.  Thanks!

**Comment by austiezr** [comment]
@cla-bot check

**Comment by Rachel-Reverie** [comment]
Hello @AntoineRondelet! This is a follow-up to request that you sign one of the contributor license agreements mentioned in the earlier comment by @ge-cla-bot.  We aren't able to merge your changes unless you do. Thanks!

**Comment by Rachel-Reverie** [comment]
I'm going to close this for now.  Please feel free to re-open it if you sign the CLI.

**Pull request closed without merging**
