### PR TITLE
[BUGFIX] Added kwargs to functions signatures

### PR DESCRIPTION
**Pull request by flavsdotpy**
Added `**kwargs` to `_set` function signature on both S3 and GCS stores, so when `ExpectationsStore` call them passing `allow_update=True` (line 54 of expectations_store.py), it does not fail of `_set() got an unexpected keyword argument 'allow_update'`.

### CODE REVIEW

**Comment by flavsdotpy** [comment]
@cla-bot check

**Comment by flavsdotpy** [comment]
I really don't know how to fix linting, I doesn't seem it's something with my changes...

**Comment by jcampbell** [comment]
@ap3xx -> thank you so much for this PR and for finding the issue! We just did a quick review of this and realized that there are some deeper changes we'd like to make to ensure this bug is fixed and also that the code is more maintainable. Will you check out #1683?  (cc @eugmandel )

**Comment by flavsdotpy** [comment]
@jcampbell ty bro! yeah, I just changed what would stop the errors, but I'm really happy to see the improvements! Have a nice weekend!

**Pull request closed without merging**
