### PR TITLE
[DOCS] Change the selectable to a list

### PR DESCRIPTION
**Pull request by itaise**
Hi,
Changes proposed in this pull request:
- The Sqlalchemy select expects a list or other iterable, so the example failed on sql alchemy error: 
"columns argument to select() must be a Python list or other iterable".
Therefore, I converted the column to a list containing the column in order to fix the example.

### CODE REVIEW

**Review by austiezr — APPROVED** [review]
Thanks @itaise for this fix to extend support for this expectation to SQLAlchemy < 1.4! 🚀

**Comment by austiezr** [comment]
@cla-bot check

**Comment by austiezr** [comment]
@itaise Once we've got a signed CLA we can move forward with this contribution!

**Comment by itaise** [comment]
> @itaise Once we've got a signed CLA we can move forward with this contribution!

Thank you! checking which one is relevant for me

**Comment by itaise** [comment]
> @itaise Once we've got a signed CLA we can move forward with this contribution!

@austiezr CLA Done

**Comment by austiezr** [comment]
@cla-bot check

**Pull request merged**
