### PR TITLE
[ENHANCEMENT] Stop using Click to check if the user provided file exists - this will help supporting S3 and GCS 

### PR DESCRIPTION
**Pull request by eugmandel**
see https://github.com/great-expectations/great_expectations/issues/2006

### CODE REVIEW

**Review by Aylr — APPROVED** [review]
This works great, and I have a minor nitpick. Can we change the prompt to say something that indicates a user can *also* add an `s3://` or `gs://` path?

ge_—_great_expectations_suite_new_—_Python_◂_great_expectations_suite_new_—_112×83

**Comment by eugmandel** [comment]
Addresses https://github.com/great-expectations/great_expectations/issues/2006

**Comment by eugmandel** [comment]
> `s3://` or `gs://` path?

Excellent idea - updated the prompt!

**Comment by eugmandel** [comment]
> This works great, and I have a minor nitpick. Can we change the prompt to say something that indicates a user can _also_ add an `s3://` or `gs://` path?
> 
> ge_—_great_expectations_suite_new_—_Python_◂_great_expectations_suite_new_—_112×83

Excellent idea - updated the prompt!

**Pull request merged**
