### PR TITLE
[DOCS] broken links, how_to_configure_a_validation_result_store_in_gcs.md

### PR DESCRIPTION
**Pull request by plain-jane-gray**
fixed broken “authentication for the Google Cloud API” and “Documentation for Google Cloud” links

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- fixed broken “authentication for the Google Cloud API” and “Documentation for Google Cloud” links 
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

Thank you for submitting!

### CODE REVIEW

**Review by talagluck — APPROVED** [review]
Thanks so much for this contribution, @plain-jane-gray - LGTM! Out of curiosity, are you using a tool to check for broken links, or is this manual?

**Comment by plain-jane-gray** [comment]
I thought about using a tool, but these PRs were a manual check. I was going through the documentation to see if the documentation made sense and made notes of where there were broken links or links that didn't make sense as I was going through.

**Comment by talagluck** [comment]
Thanks so much for doing that! We've looked into using a tool before, so I was wondering if you had landed on anything that you thought might be a good fit. Manual testing is always optimal though, so we really appreciate it!

**Comment by plain-jane-gray** [comment]
Yep, no problem.

**Pull request merged**
