### PR TITLE
Create ge.read_json function; factor out _convert_to_dataset_class

### PR DESCRIPTION
**Pull request by abegong**
Implements #195

### CODE REVIEW

**Comment by rjurney** [comment]
@abegong, this looks good to me! I'll try it out...

**Comment by rjurney** [comment]
@abegong I can't figure out what repo superconductive is, and I don't have that branch name when I check out the code and fetch latest... so I'm confused. How do I get that branch?

**Review by jpcampb2 — APPROVED** [review]
This looks good to me. The tests in TestIO don't seem to test anything except that no exception is raised, so recommend revisiting, but given request for this now, recommend we just offer it.

**Comment by abegong** [comment]
Agreed. I've added an issue: https://github.com/great-expectations/great_expectations/issues/205

Merging now.

**Comment by rjurney** [comment]
Thanks!

**Pull request merged**
