### PR TITLE
[DOCS] Update ToC with category links

### PR DESCRIPTION
**Pull request by Rachel-Reverie**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- Updates the ToC to remove one layer of nesting and have overview pages be linked to the category items instead.
- Adds overview pages for Reference Architectures and Reference Documents to maintain consistency.

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [X] I have made corresponding changes to the documentation

Thank you for submitting!

### CODE REVIEW

**Review by donaldheppner — APPROVED** [review]

**Review by rdodev — APPROVED** [review]
The less layers, the better. LGTM.

**Review by abegong — CHANGES_REQUESTED** [review]
This change makes sense to me.

Shouldn't we set up link forwarding for pages that won't exist anymore?

**Comment by Rachel-Reverie** [comment]
> This change makes sense to me.
> 
> Shouldn't we set up link forwarding for pages that won't exist anymore?

@abegong 

If the urls for the pages had changed, we would.  However: the urls for Docusaurus are based off of the file tree in the `docs` folder and the ids associated with the files, not the location of the page in the ToC.  Since I didn't change any of the locations, names, or ids of the files in the `docs` folder we don't need to set up forwarding pages: the pages all exist at the same location as before, this just restructures the way those links are displayed in the ToC.

**Review by abegong — APPROVED** [review]
:+1:

**Pull request merged**
