### PR TITLE
[FEATURE] Add result_format as optional argument to validation_operators

### PR DESCRIPTION
**Pull request by cwerner**
This PR simply makes the result_format configurable by the user (follow up on discussion on slack with Alex Sherstinsky): 

I wanted to use the result_format=COMPLETE for validation_operators since I plan to parse the `unexpected_index_list` to flag individual column values as problematic. This PR simply enables the specification of result_format in the great_expectation.yml file (section: validation_operators):

Example:  
``` 
validation_operators:
  run_warning_and_failure_expectation_suites:
    class_name: WarningAndFailureExpectationSuitesValidationOperator
    result_format: COMPLETE
    action_list:
      - name: store_validation_result
      ...
```

Note, I did not add a test since I am a bit lost in the extensive test suite of GE and wouldn't know where/ how to start. Pointers welcome...

Changes proposed in this pull request:
- add an optional argument result_format for validation_operators (default is still SUMMARY)

### CODE REVIEW

**Review by jcampbell — CHANGES_REQUESTED** [review]
This looks great!

Two requests:

1. Could you add support for the dictionary-style result format, by using the `parse_result_format` method in `great_expectations.data_asset.util`
2. Could you ensure that the `run_validation_operator` method is updated to accept and pass on this parameter?

**Comment by cwerner** [comment]
@jcampbell Will do... I just committed the first requested change. Not sure if the default argument that I provide is what you'd use? 

Regarding the second point: I'm not clear what this entails/ where to look. Could you clarify a bit and point me to the right spot?

**Comment by jcampbell** [comment]
Awesome! 

For the second change, I meant to update the run_validation_operator signature in BaseDataContext (line 842 of data_context) so that it is possible to pass it in there.

Small tweak on the first: can you keep the parsed result format to store in `self.result_format` instead of extracting just the string?

**Comment by cwerner** [comment]
I think I took care of the second request now. But to be honest, I'm not 100% sure I know what I am doing there. Could you check that this is actually sensible?

**Comment by cwerner** [comment]
@jcampbell Just a ping... not sure if you get notified with each new commit of mine?

**Review by jcampbell — APPROVED** [review]

**Comment by jcampbell** [comment]
Thanks for the ping -- yes, this looks great!

**Pull request merged**
