### PR TITLE
[DOCS] WIP: docs updates for Checkpoints

### PR DESCRIPTION
**Pull request by spbail**
Made some minor tweaks to some of the docs to test the new checkpoints.
@alexsherstinsky I left "How to configure a New Checkpoint using ``test_yaml_config``" in an incomplete state: I took the basic explanation out and put it into "How to create a Checkpoint", but I think it might be better to keep the more advanced stuff in a separate guide. Do you have any thoughts on how to organize it? Maybe I could just keep the current title and add a link to the "how to create a new checkpoint" doc, so it's clear this is the advanced content?

### CODE REVIEW

**Comment by spbail** [comment]
Ah crap, PR'd against the wrong branch. I'll try again haha.

**Comment by alexsherstinsky** [comment]
> Made some minor tweaks to some of the docs to test the new checkpoints.
> @alexsherstinsky I left "How to configure a New Checkpoint using `test_yaml_config`" in an incomplete state: I took the basic explanation out and put it into "How to create a Checkpoint", but I think it might be better to keep the more advanced stuff in a separate guide. Do you have any thoughts on how to organize it? Maybe I could just keep the current title and add a link to the "how to create a new checkpoint" doc, so it's clear this is the advanced content?

@spbail Not sure what's best here.  The original document was "A -- Z" in terms of going from the basic to advanced examples, following the design spec and also reflected in the notebook committed to the design repository.

**Comment by spbail** [comment]
@alexsherstinsky I cleaned this up some more - I think the split between "how to create" and the advanced "how to configure a new checkpoint" makes sense to me. Let me know what you think.

**Review by alexsherstinsky — APPROVED** [review]
LGTM!

**Pull request merged**
