### PR TITLE
[BUGFIX] Wrap get_view_names in try clause for passing the NotImplemented error

### PR DESCRIPTION
**Pull request by kj-9**
Changes proposed in this pull request:
- wrap get_view_names method in try clause

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by talagluck** [comment]
Thanks for the PR submission, @kj-9! This is super helpful, just a couple of notes:
- I see that you checked the box above for unit tests. Are there any unit tests that would be helpful for checking the new or existing code in this situation?
- It looks like this is currently failing testing due to linting - would you please ensure that the code is linted as per the instructions here: https://docs.greatexpectations.io/en/latest/contributing/style_guide.html#code

Please let me know if you have any questions or need any help here.

**Comment by kj-9** [comment]
Thank you for your reply, @talagluck.

> I see that you checked the box above for unit tests. Are there any unit tests that would be helpful for checking the new or existing code in this situation?

I'm sorry I checked the box by mistake. Do I need to add some tests for this change?
Seems tricky to test, since this bug involves Athena datasource.

> It looks like this is currently failing testing due to linting - would you please ensure that the code is linted as per the instructions here: https://docs.greatexpectations.io/en/latest/contributing/style_guide.html#code

I locally linted my code and found the part need to be changed. I'll push linted code later. Thanks!

**Comment by talagluck** [comment]
Hi @kj-9 - thanks for the update on linting! 

For the unit test, it may be possible to simulate the NotImplementedError without having to worry about an Athena Datasource. Is this something which you would feel comfortable attempting?

**Comment by kj-9** [comment]
> For the unit test, it may be possible to simulate the NotImplementedError without having to worry about an Athena Datasource.

Oh, this sounds great!

If I understand your point correctly, do you mean we could create a mocked `execution_engine` which does not implement `get_view_names` method and use it to test `_introspect_db`?

[Here](https://github.com/great-expectations/great_expectations/blob/635602c3c526b5b477220d410d10209fe689319f/tests/datasource/test_new_datasource_with_sql_data_connector.py#L407) is current tests for `_introspect_db`. There are not mock tests for sql `execution_engine`.
I'm not very sure how to mock and test it for now, it may take some time to add such tests by myself.

If possible, any help would be appreciated!

**Review by talagluck — APPROVED** [review]
Hi @kj-9 ! Thanks for your response! After some review, it looks like adding unit tests in this way would be a little more involved than I had originally thought. Since this functionality was already not fully tested (as per the existing comment), I'm going to approve and merge once all existing tests pass. Thank you so much again for your contribution!

**Comment by kj-9** [comment]
Thank you for approving, @talagluck !
`test_usage_stats_messages` has failed due to the server recieving stats returning 502 status code which should be 201. Some failure may be happening around the server?

P.S. I have read in the document that GE core team planning to expand support for some cloud based datasources in the future. I'm looking forward to it!

**Comment by talagluck** [comment]
Thanks, @kj-9 ! I believe we are all set for now. Thank you again for your contribution, and your feedback!

**Comment by kj-9** [comment]
Thank you too for all your support @talagluck !
I'll close the issue #2975 as well.

**Pull request merged**
