### PR TITLE
[FEATURE] Add airflow plugin. Using the plugin is as simple as adding from airfl…

### LINKED ISSUE #1848: Great Expectations Airflow operator for validation
**Is your feature request related to a problem? Please describe.**
There are examples to run validation/checkpoints in Airflow using a Python or Bash operator, but it would be nice to have a GE Airflow operator for convenience to easily run validations.

**Describe the solution you'd like**
For example, the operator could be called passing in the expectation suite name and batch kwargs perhaps

**Describe alternatives you've considered**
Implement the validation in a PythonOperator

**Additional context**
For reference, this is what we currently do with a PythonOperator:

validation = PythonOperator(
    task_id='validation_task',
    python_callable=validation_method,
    op_kwargs={
        'data_asset_name': 'demo__dir/default/npidata_pfile',
        'expectation_suite_name': 'warning',
        'batch_kwargs': BatchKwargs(
            path='/data/demo/npidata_pfile/npidata_pfile_20050523-20191001_1.csv'
        )
    },
    dag=dag,
)

### PR DESCRIPTION
**Pull request by bouke-nederstigt**
…ow.great_expectations import CheckpointOperator

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Add an Great Expectations airflow plugin
- Plugin contains an operator for executing checkpoints
- This is an early version for feedback. Curious to find out if this is the right direction before adding tests / docs etc.

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
- Closes #1848 
-
-

Thank you for submitting!

### CODE REVIEW

**Comment by NickBenthem** [comment]
I'm going to comment here as I would be copying/pasting your edits for the update files 
(let me know if you want to have a seperate PR into your code) - but this implements the suite expectation operator on top of the checkpoint for more customization:

```
import great_expectations as ge
from airflow import AirflowException
from airflow.models import BaseOperator
from airflow.utils.decorators import apply_defaults



class GreatExpectationsSuiteOperator(BaseOperator):
    ui_color = '#7ed9c8'
    @apply_defaults
    def __init__(
            self,
            expectation_suite_name,
            context_root_dir,
            batch_kwargs,
            expectations_config=None,
            validation_operator="action_list_operator",
            run_id = None,
            *args,
            **kwargs
    ):
        """
        @param expectation_suite_name: the name of the expectation suite for Great Expectations
        @param context_root_dir: the absolute or relative path to the directory holding
        @param batch_kwargs: a dictionary to specify the job batch_kwargs
        @param expectations_config: the absolute or relative path to your config in `great_expectations.yml`.
            By default - grabs the great_expectations.yml in context_root_dir
        @param validation_operator: operator to use - must be defined in your great_expectations.yml
        @param run_id: optional run_id for Great Expectations.
        """
        super(GreatExpectationsSuiteOperator, self).__init__(*args, **kwargs)
        self.expectation_suite_name = expectation_suite_name
        self.context_root_dir = context_root_dir
        self.expectations_config = expectations_config
        self.batch_kwargs = batch_kwargs
        self.run_id = run_id
        self.validation_operator = validation_operator

    def execute(self, context):

        context = ge.DataContext(
            self.context_root_dir,
            self.expectations_config
        )

        suite = context.get_expectation_suite(self.expectation_suite_name)
        batch = context.get_batch(self.batch_kwargs, suite)
        self.log.info('Executing validation.')

        # Run the validation
        results = context.run_validation_operator(
            self.validation_operator,
            assets_to_validate=[batch],
            run_id= self.run_id)

        # Handle result of validation
        if not results["success"]:
            raise AirflowException("Validation of the data is not successful ")

        self.log.info('Validation successful.')
```

**Comment by spbail** [comment]
@bouke-nederstigt Thanks for submitting, I'll rally the team and we'll review!

**Comment by eugmandel** [comment]
We are in a crunch this week, but will get to review this PR next week.

**Comment by HugoManoMano** [comment]
Hey there, sorry if I'm a bit late but using great expectations in Airflow since recently made me realize that two other features could be interesting to add in the operator :
- a class attribute to fail_hard (may be set to true by default), if at least one validation in the suite failed : can be useful if from a business point of view we do not want to block downstream pipeline
- I also think adding a link to the validation doc generated would be killing feature ; https://airflow.apache.org/docs/stable/howto/define_extra_link.html

**Comment by spbail** [comment]
Hi all, we've huddled with a few other users and decided to build a GE Airflow operator against the Airflow repo. @bouke-nederstigt would you mind taking a look at the PR convo that's going on there to see if this meets your use case, or chime in: https://github.com/apache/airflow/pull/11113

**Comment by eugmandel** [comment]
Since there was such a high demand for an officially supported Great Expectations Airflow Operator, here it is: https://greatexpectations.io/blog/airflow-operator/

@bouke-nederstigt  We really appreciate your contribution!

**Pull request closed without merging**
