### PR TITLE
[FEATURE] Add API action

### PR DESCRIPTION
**Pull request by itaise**
Hi,
This is a new validation action (that we are using already in our set up) which sends a POST request with the suite name, asset name, and validation results to a URL which is specified in the action config as an additional parameter - "url". 
It can be useful for anyone wanting to send the validation results to some endpoint.

This is an initial version, as @talagluck requested. 
Can you please review? 
Thanks!

### CODE REVIEW

**Comment by Shinnnyshinshin** [comment]
Hi @itaise this is a great start, and I'm very excited to see this merged. Would you be able to add some tests for the the API action? They can be added along with the Slack and PagerDuty actions in `tests/actions/test_core_actions.py`

**Review by amitbend — APPROVED** [review]
Approved

**Comment by Shinnnyshinshin** [comment]
Hi @itaise, wanting to follow up on this PR. Are you still interested in contributing the API action?

**Comment by itaise** [comment]
Hi, yes, sorry for delay, will add the tests soon :)

**Comment by itaise** [comment]
> Hi @itaise, wanting to follow up on this PR. Are you still interested in contributing the API action?
@Shinnnyshinshin  I added 2 tests, its ready for review

**Comment by Shinnnyshinshin** [comment]
> > Hi @itaise, wanting to follow up on this PR. Are you still interested in contributing the API action?
> > @Shinnnyshinshin  I added 2 tests, its ready for review

Awesome. The tests look great, and I saw that there was a `lint` error. This is the result of some changes on our end, so I can get that fixed for you :)

**Comment by itaise** [comment]
Thanks a lot!

**Review by Shinnnyshinshin — APPROVED** [review]
Looks great to me as well. Excited to see where this goes :)

**Pull request merged**
