### PR TITLE
CTOOMBS - Updated on data_context.py for issue #970. Line 1149: Bool …

### PR DESCRIPTION
**Pull request by PSUlion16**
…check added and Error message slightly modified to make it clear on boolean usage of variable.

This fix will address issue 970 directly where a user can accidentally overwrite an expectation suite.

### CODE REVIEW

**Review by jcampbell — CHANGES_REQUESTED** [review]
Really excited about this! Rather than documenting the behavior of accepting a string  in a confusing way, what if we were to use of one the following strategies instead:
1. raise ValueError if `overwrite_existing` is not already a boolean
2. raise ValueError if `overwrite_existing` is not already a boolean or one of a small number of accepted values ('true', 'True', 'false', 'False', 't', 'f')

I have a preference to the second option, but think both could work.

**Comment by PSUlion16** [comment]
James, I like option one, I was thinking of doing this previously and I'm not sure why I didn't.  I think if we make it clear on the usage (in terms of data types) in the raised error, this should suffice and we wouldnt need to handle other input. I can modify if you agree

**Comment by jcampbell** [comment]
Sounds good to me -- let's go with that!

**Comment by jcampbell** [comment]
@cla-bot check

**Comment by jcampbell** [comment]
@PSUlion16 ping on this!

**Comment by PSUlion16** [comment]
@jcampbell -- I was having some merge issues locally - but I think I got straightened out and I can see my modifications to the context file. Simply added a Value Check to the top of this to address our needs. Perhaps we can think about making a valueCheck GE Exception class for more consistent error messaging in a later iteration?

**Review by jcampbell — APPROVED** [review]

**Comment by jcampbell** [comment]
Thank you! I agree -- using a customized error is almost certainly right. I think a more comprehensive review/systematic proposal for how to structure errors is in order!

**Pull request merged**
