### PR TITLE
[BUGFIX] Resolve Issue 7335

### PR DESCRIPTION
**Pull request by richardohara**
Use of a hard coded file path separator at line 1065 in file tuple_store_backend.py is causing a DataContextError exception when running a checkpoint on a Windows OS machine.

Change proposed in this pull request:
- Replace "/" with "{os.path.sep}"

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code

Thank you for submitting!

### CODE REVIEW

**Review by Shinnnyshinshin — APPROVED** [review]
@richardohara Thank you for these contributions. They are big steps towards better cross-OS compatibility :)

**Comment by richardohara** [comment]
> @richardohara Thank you for these contributions. They are big steps towards better cross-OS compatibility :)

You are welcome @Shinnnyshinshin. I am looking forward to making further contributions once I get more familiar with the code base.

**Review by alexsherstinsky — CHANGES_REQUESTED** [review]
Hello, @richardohara -- thank you so much for providing a fix for this issue; could you please also add a unit test, demonstrating how the fix will work (and then please also update the working branch with the latest)?  Thank you very much in advance.

**Comment by richardohara** [comment]
Yes, @alexsherstinsky. Will do. I am traveling for the next two days and I
will take care of this when I get back.*

**Comment by Shinnnyshinshin** [comment]
Hi @richardohara I wanted to check in. Is there additional work you wanted to put into this PR before requesting a re-review?

**Review by alexsherstinsky — APPROVED** [review]

**Comment by Shinnnyshinshin** [comment]
Hi @richardohara we have decided to merge the PR as-is.  Thank you very much for your contribution

**Pull request merged**
