### PR TITLE
[DOCS] Add how_to_add_comments_to_a_page_in_documentation.rst and images

### PR DESCRIPTION
**Pull request by abegong**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Separates out "how_to_add_comments_to_a_page_in_documentation.rst" from "how_to_write_a_how_to_guide.rst".
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

### CODE REVIEW

**Comment by abegong** [comment]
@kyleaton , the first time I went through the instructions, I found it difficult to follow the branching logic in for adding comments to How-to guides.

To fix that, I've pulled your instructions into their own guide. That lets us add code blocks and pictures to illustrate, without making "how to write a how-to guide" feel big and complicated.

The only substantive change is that this version doesn't ask users to create a new discuss article when changing from a stub to a fully-fledged guide.

How do you feel about these changes?

**Review by kyleaton — APPROVED** [review]
This is excellent thank you!

**Comment by abegong** [comment]
@jcampbell , we've got some kind of issue with black and usage_stats.  Looks like it originates here: https://travis-ci.org/github/great-expectations/great_expectations/jobs/692730339

**Comment by jcampbell** [comment]
I just updated to add the highly-import newline that black wanted. :)

**Pull request merged**
