### PR TITLE
Dockerized tests

### PR DESCRIPTION
**Pull request by abegong**
Builds on #209 to implement containerized testing.

This isn't ready for merge. I'm creating an initial PR to show the pattern.

### CODE REVIEW

**Comment by jpcampb2** [comment]
Recommend we close this as a PR and just keep it as a branch while we're evaluating design options.

**Comment by abegong** [comment]
+1

**Comment by seeM** [comment]
Is the outcome of these design options documented anywhere? What is the alternative to running tests locally?

**Comment by abegong** [comment]
Yikes. This one is pretty ancient history, since it was (1) before we introduced DataContexts and (2) focused only on unit tests for the GE library.

When you say "alternative to running tests locally," do you mean the unit tests for the GE library? Or applying Expectations to data?

**Comment by seeM** [comment]
Running the unit tests for the GE library, locally, while developing.

I'm just interested in the `docker-compose` and `Dockerfile` files here.

Since this PR was closed, and I don't see anything else discussing Docker, I wonder what the current approach is to running GE tests locally. Specifically tests requiring postgres or spark?

I've got it working with Docker. Not sure if that is worth a PR?

EDIT: I can also make an issue to discuss this if that's more relevant.

**Pull request closed without merging**
