### PR TITLE
Issue #413 - Adding support for parse_strings_as_datetimes to SQLAlchemyDataSet

### PR DESCRIPTION
**Pull request by rahulj51**
For #413

### CODE REVIEW

**Review by jcampbell — CHANGES_REQUESTED** [review]
@rahulj51 Thank you--this looks really good; would be happy to merge as-is, but if you're willing I have a couple questions/requests:

- [ ] You've created a nice pattern for specifying the type of columns in the test file; what about extending it by changing it to "col_dtypes" that is a list of the form [{column_name: dtype}] and updating the get_dataset call accordingly. If this seems like too much for this PR, understood; just thought it would be a nice chance to address that while you're in the codebase.
- [ ] Update the other test runner files bring in the changes you made to `test_column_map...` and `test_column_aggregate...` (just trying to keep those identical so there's no later confusion). 
   - `test_column_pair_map_expectations.py`
   - `test_multicolumn_map_expectations.py`
   - `test_other_expectations.py`
- [ ] Add a note in the changelog (and give yourself a shoutout!)

**Comment by rahulj51** [comment]
@jcampbell thanks for reviewing the PR. 
Using `col_dtypes` is a great idea. I saw that this was also discussed earlier in #317 . I will work on it right away. I'll also make the other changes you suggested.

**Review by jcampbell — APPROVED** [review]
Looks great--thank you for adding this feature!

**Comment by rahulj51** [comment]
Thanks @jcampbell . This enables me and my team to use great_expectations in our data pipelines. Happy to contribute more as we continue to adopt great_expectations for our specific use-cases.

**Pull request merged**
