### PR TITLE
[BUGFIX] fix parameter value in mkdir for profiling results renderer

### PR DESCRIPTION
**Pull request by dataguage**
fixing mistake from "exits_ok=True" to "exist_ok-True"

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For nontrivial changes, we will conduct both a design review and a code review. Please tag a core team member for code review, or leave blank and we will find someone for you!

- [x] Design Review (@jcampbell)
- [ ] Code Review

Thank you for submitting!

### CODE REVIEW

**Comment by dataguage** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Review by Aylr — APPROVED** [review]
Great catch. Thanks!

**Review by ayirplm — APPROVED** [review]
LGTM

**Comment by Aylr** [comment]
@kyleaton can you help us verify the CLA is signed on this so we can merge it?

**Comment by kyleaton** [comment]
@Aylr Yes he's signed!

**Comment by jcampbell** [comment]
@cla-bot check

**Review by jcampbell — APPROVED** [review]
Thank you!

**Pull request merged**
