### PR TITLE
Remove profile CLI command parameter docstring

### LINKED ISSUE #1271: profile CLI help text mistakenly includes Python parameter docstrings
For CLI commands (like all the other `great_expectations` ones) the docstrings for the Click command shouldn't include traditional docstring elements like argument specifications.

It looks like `great_expectations datasource profile --help` includes this: (see all the `:param:` entries in the second paragraph)

image

### PR DESCRIPTION
**Pull request by mzjp2**
Resolves #1271 -- looks like this now (see issue for what it used to look like):

image

I apologise for the small PR, but it was bugging me 👀

### CODE REVIEW

**Comment by Aylr** [comment]
@ge-cla-bot check

**Comment by mzjp2** [comment]
Snuck in a little fix for the [0.9.8 changelog ](https://great-expectations.readthedocs.io/en/0.9.9/changelog/changelog.html#id1) -- hope you don't mind 👀

**Comment by Aylr** [comment]
@clabot check

**Review by Aylr — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
