### PR TITLE
[BUGFIX] correct syntax error in set creation

### PR DESCRIPTION
**Pull request by dataguage**
Here while using below code we were getting an error with trace: unhashable type: 'list' for which now I have changed that to set only.
document_model = ProfilingResultsPageRenderer().render(validation_result)

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For nontrivial changes, we will conduct both a design review and a code review. Please tag a core team member for code review, or leave blank and we will find someone for you!

- [ ] Design Review (@jcampbell)
- [ ] Code Review

Thank you for submitting!

### CODE REVIEW

**Comment by dataguage** [comment]
@cla-bot check

**Comment by dataguage** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Review by jcampbell — APPROVED** [review]

**Comment by Aylr** [comment]
Merging. Required builds passed!

**Pull request merged**
