### PR TITLE
[BUGFIX] Change default for prefix

### LINKED ISSUE #1907: ERROR: TypeError: Keys in TupleS3StoreBackend must be instances of <class 'tuple'>, not <class 'great_expectations.data_context.types.resource_identifiers.ValidationResultIdentifier'>
A few users reported this error, but we do not have precise steps to reproduce this - in progress...
TODO: fill in the details

**Describe the bug**
TODO

**To Reproduce**
TODO

**Expected behavior**
Error should not happen

**Environment (please complete the following information):**
 - GE Version: [e.g. 0.10.0]

**Additional context**

### PR DESCRIPTION
**Pull request by anthonyburdi**
Changes proposed in this pull request:
- Change prefix default, closes #1907 (in addition to upgrading to Great Expectations future v0.12.4 or later)

### CODE REVIEW

**Comment by spbail** [comment]
We should give out awards for highest impact PR in least characters.

**Comment by lcorneliussen** [comment]
HA! So workaround is specifying an empty prefix in the yaml?

**Comment by anthonyburdi** [comment]
> HA! So workaround is specifying an empty prefix in the yaml?

Thanks for the suggestion Lars! But unfortunately this doesn't work in my testing of Great Expectations v0.12.0. I would suggest upgrading if possible.

**Comment by lcorneliussen** [comment]
Fix seems to work for me. Can you elaborate on why this happened and led to such an awkward error?

**Comment by lcorneliussen** [comment]
So, wich one fixed it? This one i'm commenting on or #1912?

the latter seems more likely. Or both at the end :)

**Review by eugmandel — APPROVED** [review]

**Comment by anthonyburdi** [comment]
> So, wich one fixed it? This one i'm commenting on or #1912?
> 
> the latter seems more likely. Or both at the end :)

It seems both fixed it!

**Comment by anthonyburdi** [comment]
> Fix seems to work for me. Can you elaborate on why this happened and led to such an awkward error?

Glad to hear it! Here are some additional details: Looks like `boto3.list_objects_v2` only accepts a string for the Prefix parameter: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2
We have a suspicion that our mock library (`moto`) is more permissive and was not throwing an error when we tried to pass `None` here in our tests.

Thank you so much for helping to reproduce this error!

**Pull request merged**
