### PR TITLE
[DOCS]: Updated code example to remove deprecated "File"function

### PR DESCRIPTION
**Pull request by daccorti**
`file( )` function is deprecated with Python 3. It is replaced with the `open ( )` function.

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- replace file function in the code example with the open function so that the example is able to be run by a reader
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have made corresponding changes to the documentation

Thank you for submitting!

### CODE REVIEW

**Comment by talagluck** [comment]
Hi @daccorti - thanks so much for following up with this contribution! Once you get the CLA signed, we can get this approved and merged. Please let us know if you have any questions.

**Comment by daccorti** [comment]
Thanks @talagluck - I am going to quickly review the CLA and then I will respond shortly with confirmation!

**Comment by talagluck** [comment]
@cla-bot check

**Comment by talagluck** [comment]
Hi @daccorti! I wanted to check in, are you having any trouble with the CLA? As soon as you get it signed, we should be ready to approve and merge.

**Comment by daccorti** [comment]
@cla-bot check

**Comment by daccorti** [comment]
@talagluck - Sorry for the delay signed the CLA and pinged the bot

**Review by talagluck — APPROVED** [review]
LGTM - thanks for the contribution, @daccorti!

**Pull request merged**
