### PR TITLE
[DOCS] Added a Prerequisites info box to the how-to guide template

### PR DESCRIPTION
**Pull request by eugmandel**
Changes proposed in this pull request:
- Added a new info box to the how-to guide template (see the screenshot)
- Modified one guide to add the info box.

image

Previous Design Review notes:
- The change was done after a discussion at a prod eng session.
- The changes were reviewed and updated with @abegong 

Thank you for submitting!

### CODE REVIEW

**Review by abegong — APPROVED** [review]
❤️

**Review by abegong — APPROVED** [review]
❤️

**Review by abegong — CHANGES_REQUESTED** [review]
Actually, please put the admonition in the template (how_to_guides__miscellaneous__how_to_template), not "How to write a how-to guide."

**Comment by eugmandel** [comment]
> how_to_guides__miscellaneous__how_to_template

Moved the info box and updated the how-to guide.

**Review by Aylr — APPROVED** [review]
LGTM

**Pull request merged**
