### PR TITLE
[FEATURE] Added support for email notifications

### LINKED ISSUE #2479: Add Email Validation Action
**Is your feature request related to a problem? Please describe.**
I have setup automated tests of the data that I receive from the manual ingestion from my client. They do not use Slack (unfortunately) or any other tool that I could use for notifications available in Great Expectations.
They have emails and mailing lists though, as well as a SMTP server that I can use. Thus, I could theoretically send emails at the end of the validation of the files I receive so they can be noticed of any issue in the ingested files.

**Describe the solution you'd like**
An email notification that would work just like the Slack notification but that sends emails instead.

**Describe alternatives you've considered**
I have setup everything in a custom module that I currently use, but I think this feature could be directly added to great_expectations.

**Additional context**
The email notification could look something like this (a custom renderer may also be used to enhance the email visuals) :
image

### PR DESCRIPTION
**Pull request by Cedric-Magnan**
Changes proposed in this pull request:
- Created an EmailAction (inspired by the SlackNotificationAction code)
- Created an EmailRenderer (inspired by the SlackRenderer code)
- Added docs on how to use this Validation Operator (inspired by the Slack Notification documentation)
- Added simple tests for EmailRenderer (inspired by the test_SlackRenderer code)
- Added simple tests for EmailAction

resolves #2479

### CODE REVIEW

**Review by eugmandel — CHANGES_REQUESTED** [review]
@Cedric-Magnan This is a great contribution! I have one request change - could you please add one more config key for smtp username? You are currently using sender_email_address for that, but some services require username and sender address to be separate. For example, with SendGrid, the username is always "apikey" and the sender address must be specified separately and match the one in the account. Thank you!

**Comment by Cedric-Magnan** [comment]
> @Cedric-Magnan This is a great contribution! I have one request change - could you please add one more config key for smtp username? You are currently using sender_email_address for that, but some services require username and sender address to be separate. For example, with SendGrid, the username is always "apikey" and the sender address must be specified separately and match the one in the account. Thank you!

Well spotted ! I didn't even consider this possibility. I've just applied the requested changes. Don't hesitate to tell me if there is anything else to change.
CI currently fails due to a linting error on develop.
PR #2489 needs to be merged first.

**Comment by eugmandel** [comment]
@Cedric-Magnan Merged #2489, approving...

**Review by eugmandel — APPROVED** [review]
This is a great feature!

**Comment by eugmandel** [comment]
@Cedric-Magnan Sorry, did not notice before approving - could you please fix the error in your test? Will merge once this is comittted.

**Comment by Cedric-Magnan** [comment]
> @Cedric-Magnan Sorry, did not notice before approving - could you please fix the error in your test? Will merge once this is comittted.

Of course, I've just fixed the tests.
I've also tested sending the Email Action through Gmail smtp server with TLS and SSL. Both work, with the possibility to specify an alias for the sender like for example:
John Smith \<john.smith@gmail.com\>

**Comment by eugmandel** [comment]
@Cedric-Magnan Perfect - merging!

**Pull request merged**
