### PR TITLE
[ENHANCEMENT] - Update GCSStoreBackend to Limit IAM Permissions Required

### PR DESCRIPTION
**Pull request by hmandsager**
Changes proposed in this pull request:
- Leverage `bucket` instead of `get_bucket` in order to reduce [IAM Permissions](https://cloud.google.com/storage/docs/access-control/iam-permissions) required. Since the methods in this class only act on the blob objects there's no need for bucket level permissions. 
- Also removed redundant `_move` method.

Some additional documentation for Google Cloud Storage:
- `bucket` does not make an API call ([link](https://googleapis.dev/python/storage/latest/client.html#google.cloud.storage.client.Client.bucket))
- `get_bucket` makes an API call ([link](https://googleapis.dev/python/storage/latest/client.html#google.cloud.storage.client.Client.get_bucket))

### CODE REVIEW

**Comment by hmandsager** [comment]
@cla-bot check

**Comment by hmandsager** [comment]
@cla-bot check

**Comment by hmandsager** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by eugmandel** [comment]
@hmandsager Thank you for submitting the PR! A reviewer will pick it up after triage. Sorry it is taking a bit longer now - we have so many awesome community PRs lately!

**Comment by almiavicas** [comment]
The way I am using GCS is to get a bucket that I already have in my GCP. The `bucket` method instantiates a bucket right? I do not want this behavior in my pipeline.

**Comment by talagluck** [comment]
Thanks so much for your contribution, @hmandsager! And apologies for the delay in response - we are starting to ramp up our DevRel team, and so response times will be faster moving forward.

After some internal discussion, and based on @almiavicas comment, we've decided that the safest way to make this fix would be by creating a flag and using that to determine whether to use `bucket` or `get_bucket`. In order to keep the change non-breaking, we would keep `get_bucket` as the default, but this would enable the `bucket` functionality for anyone who wants it.

Does that make sense? Please let me know if you have any questions or need any guidance with the implementation.

**Comment by hmandsager** [comment]
@talagluck appreciate you putting this on your radar! I don't think that @almiavicas has the correct understanding here. Both `bucket` and `get_bucket` return a `google.cloud.storage.bucket.Bucket` object. With `bucket` there is no API call to fetch metadata around the bucket and therefore no bucket level permissions required. Also, `bucket` doesn't create a new bucket. It simply instantiates a bucket object within your code that points to a project/bucket in GCP and then can be leveraged to pull data from blob. With `get_bucket` you make an API call which requires the elevated permissions. It would be OK to add a flag but because GE doesn't use any of the bucket metadata it would require service accounts to have higher permissions than necessary which is bad practice IMO.

**Comment by talagluck** [comment]
Hi @hmandsager ! Thanks so much for the follow-up and the explanation. What you're saying makes a lot of sense, though I'm hesitant about merging in this feature without the flag given our current lack of integration tests with GCP. A couple of thoughts/suggestions:
- Are there any other tests you could think of adding here to make this more robust and confirm parity in our case between `bucket` and `get_bucket`?
- I agree that it's not good practice to need to call this from multiple methods from within GCSStoreBackend. What would you think of instead calling `get_bucket` once from the constructor, and then adding it on to the instance as an attribute? We could re-name the currently `self.bucket` to `self.bucket_name`, and then this would be `self.bucket`. Then we could just reference `self.bucket` in each of the methods.

**Comment by almiavicas** [comment]
@hmandsager Thank you for your explanation :+1:

**Review by talagluck — APPROVED** [review]
Hi @hmandsager ! After some internal discussion, we have decided to merge this as-is. Thank you again for your contribution and for your patience!

**Pull request merged**
