### PR TITLE
Set percentage range to 0-100 consistently

### LINKED ISSUE #657: Inconsistent Percent Formats
I would expect that any summary measure ending in `_percent` use the same scale (either [0-1] or [0-100]). For example, If you run an expectation you will see "result.unexpected_percent" is a float assumed to be [0-1]
```
{'success': False,
 'result': {'element_count': 16,
  'missing_count': 0,
  'missing_percent': 0.0,
  'unexpected_count': 16,
  'unexpected_percent': 1.0,
  'partial_unexpected_list': []}}
```

If you run a validation you will see "statistics.success_percent" is a float assumed to be [0-100]
```
'statistics': {'evaluated_expectations': 17,
  'successful_expectations': 17,
  'unsuccessful_expectations': 0,
  'success_percent': 100.0},
```

If the value needs to stay a number and not a formatted string, then I would prefer the second format [0-100] because `'unexpected_percent': 1.0` is supposed to indicate 100% but my mind reads that as 1%. Ideally, these types of values could be formatted to include a percent sign for clarity, but I understand if the value needs to remain a number and not a string.

### PR DESCRIPTION
**Pull request by elsander**
This PR updates reporting so that all percentage-based numbers range between 0-100. Previously, some values (e.g. `missing_percent`) ranged between 0-1, and others (e.g. `success_percent`) ranged between 0-100.

In order to make terminology as consistent as possible, I changed documentation referencing a "percentage" to "fraction" if the value ranged 0-1.

Closes #657.

### CODE REVIEW

**Review by jcampbell — APPROVED** [review]
Looks great! Will you check with @kyleeaton re the CLA?

**Comment by elsander** [comment]
Yep, I followed up with him. I'm just waiting on an ok from legal on my end, since I'm doing this work on company time.

**Comment by jcampbell** [comment]
Outstanding -- really excited to get this fix in!

**Comment by elsander** [comment]
Hmm... I just signed the CLA, and I pushed a tiny PEP8 change (removed two "imported but unused" lines) to trigger a rebuild. I'm not sure why the CLA check is still failing. I'll follow up with Kyle.

**Comment by jcampbell** [comment]
@elsander : I confirmed the CLA is signed and updated the bot; it should now go through!

**Comment by jcampbell** [comment]
@cla-bot check

**Pull request merged**
