### PR TITLE
Feature/Add SNS As An Action [WIP]

### PR DESCRIPTION
**Pull request by michael-j-thomas**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by austiezr** [comment]
Hey @michael-j-thomas ! Super exciting to see this contribution. Would you be able to provide some more context around the state of this PR? Is this still a WIP and is there any support we could provide at this point?

**Comment by michael-j-thomas** [comment]
@austiezr - Apologies! _this looks quite messy doesn't it :)_. I will update the PR, but - fundamentally - we leverage G.E at my company - Fanduel - and was looking to expand the scope to fan out validation results so individual services could handle run's differently. I will put more details in the PR. Meanwhile, I updated the PR to [WIP] if that works.

**Comment by michael-j-thomas** [comment]
Closing for now. Will return when I have more setup.

**Comment by austiezr** [comment]
@michael-j-thomas Thanks for the context around this! Looking forward to next steps; feel free to reach out for support!

**Pull request closed without merging**
