### PR TITLE
[MAINTENANCE] Add force_reuse_spark_context to DatasourceConfigSchema

### PR DESCRIPTION
**Pull request by pasmavie**
With PR [2733](https://github.com/great-expectations/great_expectations/pull/2733) a parameter was added to `SparkDFDatasource`, to make GE's context reuse an existing Spark Context.

This was extremely useful.

However, when using a dynamic Data Context configuration (e.g. in EMR) like
```
data_context_config = DataContextConfig(
    config_version=2,
    plugins_directory=None,
    config_variables_file_path=None,
    datasources={
        "my_data_source": {
            "class_name": "SparkDFDatasource",
            "spark_config": dict(spark.sparkContext.getConf().getAll()),
            "force_reuse_spark_context": True,
            "module_name": "great_expectations.datasource",
            "batch_kwargs_generators": {},
        }
    },
    ...
```

I've found that the `spark_config` and `force_reuse_spark_context` parameters weren't actually passed to `geat_expectations.core.util.get_or_create_spark_application()`.

In fact, the parameters are lost when the `DataContextConfig` object [is dumped into a dictionary](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/util.py#L462), because the [`DatasourceConfigSchema`](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/types/base.py#L630) (elem of the `DataContextConfigSchema`) doesn't list these parameters.

Changes proposed in this pull request:
- Add `spark_config` and `force_reuse_spark_context` to the `DatasourceConfigSchema`

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Comment by gipaetusb** [comment]
@cla-bot

**Comment by pasmavie** [comment]
@cla-bot check

**Comment by talagluck** [comment]
Hi @gipaetusb, thank you so much for the contribution - this is awesome! Just a few things: 
- It looks like we have a CLA record for the username `gipaetusb`, but there were a few commits made as `gio` or `gio@gio` and we are missing a CLA for that username. Are you able to fix this? Please let me know if you have any questions.
- It looks like a number of unit tests are failing as a result, and they will need to be updated, but I would expect the changes will be pretty small.
- Do you think this PR would benefit from a unit test for the additional functionality?
Please let me know if you have any questions or need additional help. Thanks again!

**Comment by pasmavie** [comment]
@cla-bot check

**Comment by pasmavie** [comment]
Hi @talagluck, thanka for taking a look:
 
- I've amended the commits so that the username is gipaetusb for all. I hope it's good now.
- Regarding the failing unit tests, I don't have time to take a look now but I can do in the future :)
- I'll also add a unit test for this feat

**Comment by talagluck** [comment]
Hi @gipaetusb - thanks for the follow-up! It looks like the CLA verification is still failing, and I still see the user `gio` when I look at the commit history. Any ideas?

Sounds good about the tests - I'll check in in in a week or so to see how things are going. Thanks again!

**Comment by talagluck** [comment]
Hi @gipaetusb ! I wanted to check in here. It looks like we are still having CLA issues. I also wanted to check in to see if you had time to fix the failing tests, or if you needed some help?

**Comment by pasmavie** [comment]
Hi @talagluck thank you for the follow up.
I'm pretty busy lately so I didn't try to fix the CLA nor the unit test. Dedicated 30min this morning but amending the old commit and rebasing this branch with all the changes that happened after has become too cumbersome.

Much easier to open a new, cleaner PR right? Here you go: https://github.com/great-expectations/great_expectations/pull/3126

If someone can help with the unit tests, that would be great :) !

**Comment by talagluck** [comment]
Thanks for the follow-up, @gipaetusb ! Someone from our team will jump in next week to review and work on the unit tests.

**Pull request closed without merging**
