### PR TITLE
[BUGFIX] column_values_unique expectation breaks with pybigquery

### PR DESCRIPTION
**Pull request by almiavicas**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Make a try/catch when checking for unsure dialect attribute in third-party modules.
- This is related to issue #2978 

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
- The previous design expects that every third-party module declares an attribute called `dialect`. This is breaking the expectation with pybigquery. `pybigquery.sqlalchemy_bigquery` module does not provide the required variable.

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by talagluck** [comment]
Thanks so much for your contribution @almiavicas! Our team will review this over the next few days and be in touch. In the meantime, would you please make sure that you've signed the CLA? Please let me know if you have any questions or issues.

**Comment by almiavicas** [comment]
@talagluck I just signed the CLA :smile:

**Comment by talagluck** [comment]
Thanks, @almiavicas! Could you describe a bit more about how this addresses the issue? It looks as though this is wrapping an `if` statement for mysql - how does this address the bug with BigQuery?

Also, it looks as though this may be failing on linting. Would you mind running a linter locally [as described here](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html#code) and pushing the changes? Thanks!

**Comment by talagluck** [comment]
Hi @almiavicas - thanks again for your contribution! It looks like this is still failing the lint checks, and there is still some confusion around how this addresses BigQuery. We're going to close this for now, but please feel free to re-open if it is still relevant and you are able to make the necessary updates.

**Pull request closed without merging**
