### PR TITLE
Bugfix/561

### LINKED ISSUE #561: Rendering crashes for `expect_column_values_to_be_in_type_list` `type_list=None`
DescriptiveOverviewSectionRenderer._get_column_types crashes when one of the EVRs is:

```
{'success': True, 'result': {'observed_value': 'DATE'}, 'exception_info': {'raised_exception': False, 'exception_message': None, 'exception_traceback': None}, 'expectation_config': {'expectation_type': 'expect_column_values_to_be_in_type_list', 'kwargs': {'column': 'release_date', 'type_list': None, 'result_format': 'SUMMARY'}, 'meta': {'BasicDatasetProfiler': {'confidence': 'very low'}}}}
```

### PR DESCRIPTION
**Pull request by abegong**
Resolves #561

### CODE REVIEW

**Comment by abegong** [comment]
Note: to test Tal's improvements, I re-enabled `test_smoke_all_expectations_using_test_definitions` and added the `smoketest` mark.

I also added an explicit test to our fixtures to verify that vacuously true (aka placeholder) Expectations of type `positive_test_placeholder_expectation` return true.

IMO, this is a good pattern for testing these types of styled string template renderers. It won't cover every potential failure mode, but it'll catch a lot of the common ones. Beyond that, building on top of our existing test fixtures will keep the test suites easy to implement and maintain.

In a separate PR, we should add fixtures for all the other placeholder Expectations, too.

**Comment by abegong** [comment]
@jcampbell 

This merge conflict actually looks pretty tame. I'll try to resolve tonight so that we can merge first thing tomorrow.

Unless you want to take it...?

I'll default to resolving it unless I hear otherwise.

**Comment by jpcampb2** [comment]
+1

**Review by jcampbell — APPROVED** [review]
Excellent!

**Pull request merged**
