### PR TITLE
Apache Hive integration

### PR DESCRIPTION
**Pull request by msempere**
Following PR is a _work in progress_ PR to make GE work with Apache Hive.

The changes introduced are the following:
 - change the temporary table creation to be `ge_tmp_` followed by letters (no numbers or underscore characters any more)
 - custom `_get_dialect_regex_fn` for `Hive`
 - import Hive dialect from `pyhive`

/cc @abegong @jcampbell

### CODE REVIEW

**Review by jcampbell — DISMISSED** [review]
Looks great to me. I have not done an independent integration test, but this matches patterns well.

Not necessary, but: I'd accept a change as well to just use something other than uuid in general for temporary table naming since different sql engines will have different quoting needs based on capitalization/special character conventions.

Also: I thought there was an issue related to the creation of a temporary table itself where it might be possible to avoid actually copying data during table creation time by using a view-like approach. Did you investigate/rule that out?

**Comment by msempere** [comment]
@jcampbell 

> Not necessary, but: I'd accept a change as well to just use something other than uuid in general for temporary table naming since different sql engines will have different quoting needs based on capitalization/special character conventions.

Do you mean allowing the user to specify the temporary table name? In this case, Hive requires the quotes around the table name, that other engines do not need. Maybe we could improve that or I could change my PR to make it more flexible.

> Also: I thought there was an issue related to the creation of a temporary table itself where it might be possible to avoid actually copying data during table creation time by using a view-like approach. Did you investigate/rule that out?

Indeed, that was raised as part of https://github.com/great-expectations/great_expectations/issues/569 but we haven't reached any outcome from that conversation. 


Apart from all that, how do you usually test all different validations with the different sources?

**Comment by jcampbell** [comment]
> Do you mean allowing the user to specify the temporary table name? In this case, Hive requires the quotes around the table name, that other engines do not need. Maybe we could improve that or I could change my PR to make it more flexible.

No, I just meant that we could choose a different mechanism for generating names (e.g. hex digits) that is all lowercase letters to avoid any complication from capitalization, numbers, or punctuation.

> Indeed, that was raised as part of #569 but we haven't reached any outcome from that conversation.

Got it; agreed we don't need that to block moving forward on this PR.

> Apart from all that, how do you usually test all different validations with the different sources?

We only do standing integration tests right now against postgres in travis; we do not have a standing setup that allows ongoing integration testing with other platforms (like Hive or Redshift). I'm certainly open to ideas to have that work, but otherwise we've allowed in PRs like this on the basis of the user's testing, since it does not affect functionality outside the Hive use case.

**Comment by msempere** [comment]
> No, I just meant that we could choose a different mechanism for generating names (e.g. hex digits) that is all lowercase letters to avoid any complication from capitalization, numbers, or punctuation.

Ah, I see what you mean now. Yes, I think that's a good idea, maybe getting rid of the dashes or underscores totally to avoid having to add quotes around the table name on some engines.

```python
table_name = str(uuid.uuid4()).replace("-", "")
```

Which engines exactly need the quotes around the temporary generated name?

Was also considering if those temporary tables could have a common prefix or suffix to differentiate from the others for better handling.
Like:
```sql
SHOW TABLES IN db LIKE 'ge_*';
DROP them all;
```

**Comment by jcampbell** [comment]
@msempere : exactly. I believe  the change was introduced for redshift and/or postgres (which do not respect capitalization/some punctuation without quotation marks).

 I also really like the idea of adding the ge_ prefix (actually even ge_temp_). Maybe something like:

```
table_name = "ge_tmp_" + ''.join([random.choice(string.ascii_letters + string.digits) for n in range(8)])
```

(That's essentially what's used in our internal test suite for generating test table names)

**Comment by msempere** [comment]
@jcampbell nice! I'm going to perform that change as part of this PR, and will try to test as many validations as possible using Hive. Will update the issue description with all that.

I can also validate the new table names using Posgres, but would need help for Redshift.

**Comment by jcampbell** [comment]
Perfect. I can do a manual test on redshift; let me know when you'd like another review!

**Comment by msempere** [comment]
I'm running tests on all validations and at the moment I'm getting the following error when using `expect_column_values_to_be_unique`:

```
Unsupported SubQuery Expression Invalid subquery. Subquery in SELECT could only be top-level expression

[SQL: SELECT count(*) AS `element_count`, sum(CASE WHEN (`id` IN (NULL) OR `id` IS NULL) THEN %(param_1)s ELSE %(param_2)s END) AS `null_count`, sum(CASE WHEN (`id` IN (SELECT `id` 
FROM `msempere`.`ge_test_users` GROUP BY `id` 
HAVING count(`id`) > %(count_1)s) AND CASE WHEN (`id` IS NULL) THEN %(param_3)s ELSE %(param_4)s END) THEN %(param_5)s ELSE %(param_6)s END) AS `unexpected_count` 
FROM `msempere`.`ge_test_users`]
[parameters: {u'count_1': 1, u'param_5': 1, u'param_4': True, u'param_6': 0, u'param_1': 1, u'param_3': False, u'param_2': 0}]
```

That represents the following query:

```sql
SELECT count(*) AS `element_count`,
       sum(CASE
               WHEN (`id` IN (NULL)
                     OR `id` IS NULL) THEN 1
               ELSE 0
           END) AS `null_count`,
       sum(CASE
               WHEN (`id` IN
                       (SELECT `id`
                        FROM `msempere`.`ge_test_users`
                        GROUP BY `id`
                        HAVING count(`id`) > 1)
                     AND CASE
                             WHEN (`id` IS NULL) THEN FALSE
                             ELSE TRUE
                         END) THEN 1
               ELSE 0
           END) AS `unexpected_count`
FROM `msempere`.`ge_test_users`
```

Currently investigating it.

**Update**:
Running that query manually succeeds 🤔 
~Are we performing a `SELECT` on top of that previous query @jcampbell ?~

**Comment by jcampbell** [comment]
That's definitely odd. Which backend + driver is this happening with?

**Comment by msempere** [comment]
> That's definitely odd. Which backend + driver is this happening with?

@jcampbell this happens when running the following code using SQLAlchemy (PyHive) and Hive driver:

```python
df = context.get_batch('msempere.ge_test_users', expectation_suite_name='my_suite')
df.expect_column_values_to_be_unique('id')
```

Failing on:
```
great_expectations/data_asset/data_asset.pyc in wrapper(self, *args, **kwargs)
    227 
    228                         else:
--> 229                             raise err
    230 
    231                 else:
```

Raising the error I pasted on https://github.com/great-expectations/great_expectations/pull/604#issuecomment-523186135

**Pull request closed without merging**
