### PR TITLE
[FEATURE] Add --assume-yes/--yes/-y option to cli docs build command

### PR DESCRIPTION
**Pull request by feluelle**
Add an option to automatically skip the dialog that would show up when building docs.
> Would you like to proceed? [Y/n]:

This is of advantage in case you want to automate building of docs where you do not have a stdin.

### CODE REVIEW

**Comment by feluelle** [comment]
@cla-bot check

**Review by jcampbell — CHANGES_REQUESTED** [review]
Thank you for this PR! (And sorry I missed it earlier for a response).

Rather than `--prompt/--no-prompt`, will you set the flag to be ``-y/--yes/--assume-yes``, following the `apt` and `yum` approach? That's the only small change request from me (other than harmonizing the merge conflict!)

**Comment by feluelle** [comment]
@jcampbell no problem :)

Your suggestion sounds good to me - will change it 😊

Thanks for Reviewing 👍

**Comment by feluelle** [comment]
@jcampbell that should do it 👍  Happy to hear what you think :)

**Comment by jcampbell** [comment]
@feluelle just a ping on this -- I think it's a great feature, and we just got a similar request in slack!

**Comment by Dandandan** [comment]
@jcampbell I guess this should be good to go if the branch is updated against master? The prompt is changed to --y/--yes/--assume-yes

**Review by jcampbell — APPROVED** [review]

**Review by Dandandan — APPROVED** [review]

**Comment by jcampbell** [comment]
Thanks @Dandandan and @feluelle  -> I hadn't seen the update, and merged!

**Comment by Dandandan** [comment]
Cool, really happy with the new feature!

**Pull request merged**
