### PR TITLE
[MAINTENANCE] Specify none for maximum column width (replaces -1). Fixes #3355.

### LINKED ISSUE #3355: Pandas FutureWarning for specifying the number of columns in Jupyter
**Describe the bug**

Jupyter notebook raises a FutureWarning when using -1 for the max_colwidth display setting.

>FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new suite that uses pandas
2. `great_expectations suite edit suitename`
3. Run the first cell in the notebook
4. Observe the FutureWarning

**Expected behavior**
No FutureWarning should be raised.

**Environment:**
 - Great Expectations Version: 0.13.32

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by miike**
Changes proposed in this pull request:
- Fixes FutureWarning using Pandas

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.

Resolves #3355

### CODE REVIEW

**Comment by talagluck** [comment]
Hi @miike - thank you very much for this contribution! It looks like a few tests are failing. Would you mind taking a look and seeing if you're able to update them? Please let me know if have any questions or need any help.

**Comment by talagluck** [comment]
Hi @miike! I wanted to check in here - would you mind taking a look at the failing tests and seeing if you can resolve? Once those are all fixed up, we can get this merge. Please let me know if you need any help with this.

**Comment by miike** [comment]
> Hi @miike! I wanted to check in here - would you mind taking a look at the failing tests and seeing if you can resolve? Once those are all fixed up, we can get this merge. Please let me know if you need any help with this.

@talagluck as far as I can tell these test failures don't look related to my change and instead looks like something incorrect with the build tests / timeouts.

>requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='qa.stats.greatexpectations.io', port=443): Read timed out. (read timeout=2)

>E   tzlocal.utils.ZoneInfoNotFoundError: 'Multiple conflicting time zone configurations found:\n/etc/timezone: Etc/UTC\n/usr/share/zoneinfo/UCT: UCT\nFix the configuration, or set the time zone in a TZ environment variable.\n'

**Comment by talagluck** [comment]
Hi @miike - thanks for checking here. I think that might have been a red herring since I had just updated the branch. We've since fixed that, and I've updated again, and it looks like tests are still failing. Do tests pass when you run them locally?

**Comment by miike** [comment]
Thanks - it looks like this fails on older versions of Pandas <= 0.25.0 so we can just leave as is for the moment.

**Comment by talagluck** [comment]
Thanks for following up, @miike! What do you think of checking for the Pandas version and only applying this to newer versions?

**Comment by miike** [comment]
> Thanks for following up, @miike! What do you think of checking for the Pandas version and only applying this to newer versions?

That's definitely doable but because this is the entry point for a large number of users who are going to be using GE for the first time I'd prefer to minimise any extra boilerplate in that first cell. Ideally all of the display options in the cell could be abstracted to a Jupyter profile but adding code just to support a version of Pandas that is > 2 years old feels very temporary.

**Comment by talagluck** [comment]
Hi @miike - you are raising some great concerns! However, I don't believe that this code is actually in the cell. It runs prior to actually rendering the notebook, rather than rendering to the cell and being run by the user. As to supporting older versions, we have some enterprise clients who may not be able to update for some time.

That said, we are currently working on standardizing the way that we handle differences in dependency versions across the codebase, so I'll leave this closed for now. Thanks so much again for your contribution, and for helping put this on our radar!

**Pull request closed without merging**
