### PR TITLE
strict inequalities

### LINKED ISSUE #542: strict inequalities for expect_column_values_to_be_between
Sometimes I want to be able to test that values are in the interior of the range I specify. Can we add this, perhaps using a `strictly_left` and a `strictly_right` argument?

(I see there's a `get_column_count_in_range` method floating around in `PandasDataset` that seems to be related?)

### PR DESCRIPTION
**Pull request by RoyalTS**
This PR adds `strictly_min` and `strictly_max` arguments to all interval expectations and harmonizes variable naming. For expectations whose object might be float-valued it also adds a `strictly_tol` argument that governs the tolerance of the test.

Fixes #542

### CODE REVIEW

**Review by jcampbell — COMMENTED** [review]
@RoyalTS : Thanks. This will be really useful. Two questions:

1. I haven't found any real standard for the name choice of the strictly_min vs. min_strictly vs. any other option; do you have a particular API you're mimicking in the change to `strictly_min`? My english grammar self wonders if it should be `strict_min` instead.

2. the tolerance-related parameters don't appear to be used consistently.

**Comment by RoyalTS** [comment]
> 1. I haven't found any real standard for the name choice of the strictly_min vs. min_strictly vs. any other option; do you have a particular API you're mimicking in the change to `strictly_min`? My english grammar self wonders if it should be `strict_min` instead.

Happy to go with whatever you think is best. Just let me know.

> 2. the tolerance-related parameters don't appear to be used consistently.

The tolerance only makes sense for things that are potentially float-valued. Are there any such cases where no tolerance parameter exists?

**Comment by jcampbell** [comment]
Got it. OK for the name: let's go with `strict_min` and `strict_max`

For tolerance, I think the following changes are needed:
 - `expect_column_value_lengths_to_be_between` should *not* support it (values must be int or None); so remove from the implementations (it's not in the parent class)
 - `expect_column_mean_to_be_between` appears to have tolerance as a parameter, but not to check it
 - `expect_column_sum_to_be_between` appears to have tolerance as a parameter, but not to check it
 - `expect_column_min_to_be_between` appears to have tolerance as a parameter, but not to check it (and should have a special case for datetime support)
 - `expect_column_max_to_be_between` appears to have tolerance as a parameter, but not to check it (and should have a special case for datetime support)

**Comment by jcampbell** [comment]
Also, for tolerance, I think it makes more sense to rename it just `tolerance` and make it default to zero and apply even when strict is False (since the usual case for using tolerance is fuzzing an equality check vice an inequality check)

**Comment by jcampbell** [comment]
@RoyalTS : ping on this in case // I'd love to get it in by tomorrow so it can go in the next release!

**Comment by RoyalTS** [comment]
> Got it. OK for the name: let's go with `strict_min` and `strict_max`
> 
> For tolerance, I think the following changes are needed:
> 
> * `expect_column_value_lengths_to_be_between` should _not_ support it (values must be int or None); so remove from the implementations (it's not in the parent class)
> * `expect_column_mean_to_be_between` appears to have tolerance as a parameter, but not to check it
> * `expect_column_sum_to_be_between` appears to have tolerance as a parameter, but not to check it
> * `expect_column_min_to_be_between` appears to have tolerance as a parameter, but not to check it (and should have a special case for datetime support)
> * `expect_column_max_to_be_between` appears to have tolerance as a parameter, but not to check it (and should have a special case for datetime support)

All addressed, I think.

> Also, for tolerance, I think it makes more sense to rename it just `tolerance` and make it default to zero and apply even when strict is False (since the usual case for using tolerance is fuzzing an equality check vice an inequality check)

Got no time to implement this rather major change right now. Not even sure I agree with this. Want to take this as it is or wait for me to change?

**Comment by jcampbell** [comment]
I think we should merge the ability to add strict types, but I'd like to just comment out the tolerance parameters for now until we resolve just how it should work. I'm happy to do that on this PR as long as you don't mind. Does that work for you?

**Comment by RoyalTS** [comment]
Go ahead!

**Comment by jcampbell** [comment]
Excellent!

**Pull request merged**
