### PR TITLE
[ENHANCEMENT] Support offline data-docs

### PR DESCRIPTION
**Pull request by arunvelsriram**
I took a stab at issue #994 for making data docs offline so that it can be used in Internet restricted environments.

The idea is to package the external static assets as part of the data docs instead of relying on CDNs. To install external packages I have added a `npm` configuration. The static assets from these packages are merged using webpack. Am using this webpack plugin [webpack-merge-and-include-globally](https://github.com/markshapiro/webpack-merge-and-include-globally) to merge the assets and make JS variables available to the global scope.

Steps to build the assets:

```
cd great_expectations/render/view
npm install
```

The external JS and CSS assets are bundled and stored in `great_expectations/render/view/static/scripts/vendor.js` and `great_expectations/render/view/static/styles/vendor.css` respectively.

### CODE REVIEW

**Comment by eugmandel** [comment]
@arunvelsriram Thank you for creating this PR - we will review and respond.

**Comment by backtrackbaba** [comment]
Hi @eugmandel,  Any update on the PR?

**Comment by arunvelsriram** [comment]
@eugmandel any thoughts on this PR?

**Comment by mkopec87** [comment]
This would be a very useful feature for me as well

**Comment by hovanessb** [comment]
Is this still being worked on?

**Comment by austiezr** [comment]
Hey folks! This isn't functionality we're going to address at this time. 🙇

**Pull request closed without merging**
