### PR TITLE
Feature/enhanced validation support

### PR DESCRIPTION
**Pull request by jcampbell**

### CODE REVIEW

**Review by abegong — COMMENTED** [review]
Hm. I'm not sure about all the implications of this direction. I get that FileDataAsset needs to be conceptually separate from Tabular DataAssets.

But do we want to specify PandasDataAsset itself? Would a parent class for both PandasDA and SqlAlchemyDA work better...?

I feel like we're relitigating the question about whether Expectations are compute-engine-agnostic or not...

**Comment by jcampbell** [comment]
I think we're on the same page and this may be a misread of the PR, but I'm open to other thoughts of course.

On the core issue: validation used to *always* use PandasDataset unless a custom dataset module and dataset class were provided; even then, it assumed a CSV. This allows the file to not be a CSV, but still uses PandasDataset (or a custom-provided module) to validate any CSVs. It *does* preserve the compatibility across Dataset types: as long as it ends with ...Dataset, it's considered compatible.

One option to clarify that might be to keep only "Dataset" or "FileDataAsset" as the data_asset_type; The downside to that is that classes providing new `data_asset_type`s would need to override `_initialize_expectations`, but that seems reasonable.

The other benefit of this change is that it helps simplify the use of CustomDataAssets in the same go, by allowing some extension of the data_asset_type that clarifies which extra expectation logic is needed to evaluate that expectation config, since previously that has been entirely implicit.

All that said, I still think a good design goal is that we won't reject any config...we'll try to run it, potentially catching exceptions along the way.

**Comment by jcampbell** [comment]
(I just pushed a commit that makes the desired behavior clearer, I think...now "data_asset_type" will be "Dataset" instead of "PandasDataset" or "SqlAlchemyDataset" --> Dataset becomes the type (as it was before).

**Comment by jcampbell** [comment]
Linking issues: see #345

**Comment by abegong** [comment]
This makes sense. I'm still uneasy about some unanswered questions, but they shouldn't block the release.

I'm going to put them in the thread for #345 for discussion

**Review by abegong — APPROVED** [review]

**Comment by jcampbell** [comment]
For the record: me too on the unease. I just wanted to have a clean way to immediately support cli-based validation against the new filedataasset types.

**Pull request merged**
