### PR TITLE
[DOCS] Add lakeFS as a data versioning tool

### PR DESCRIPTION
**Pull request by rmoff**
See title :)

### CODE REVIEW

**Comment by rmoff** [comment]
@cla-bot check

**Review by kenwade4 — APPROVED** [review]
Thanks for the contribution @rmoff!

**Comment by rmoff** [comment]
@kenwade4 I don't see this change live on the site yet - when should it be?

**Comment by rmoff** [comment]
Looking at https://github.com/great-expectations/great_expectations/blob/main/docs/intro.md I can see the change merged in, but on https://docs.greatexpectations.io/docs/#what-does-great-expectations-not-do it's not showing. @kenwade4  @alexsherstinsky am I missing something? thanks!

**Comment by kenwade4** [comment]
@rmoff I didn't notice that you made the PR into the main branch (which doesn't exist). Can you make a new PR with the same change, only using develop as the target branch?

**Comment by rmoff** [comment]
Thanks - created https://github.com/great-expectations/great_expectations/pull/7642

**Pull request merged**
