### PR TITLE
[FEATURE] add python3.9 to python versions

### PR DESCRIPTION
**Pull request by dswalter**
Changes proposed in this pull request:
- [FEATURE] Add python3.9 to supported versions in setup.py
- [BUGFIX] remove deprecated encoding='utf-8' argument from the one test that failed.

Previous Design Review notes:

- no design review has been performed.

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [n/a?] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

### Cause for uncertainty. 

It looks like there are currently issues with the snowflake connector in python3.9 at the moment.

### CODE REVIEW

**Comment by dswalter** [comment]
@cla-bot check

**Comment by jdimatteo** [comment]
Thanks for doing this @dswalter, and I hope this gets merged soon!

**Comment by cdkini** [comment]
@dswalter thanks for your contribution! 

And @jdimatteo good to see you again! Your contribution is merged so I believe the Snowflake connector issue that was specific to 3.9 is remedied.

While I very much agree that additional coverage is of great value, I think we also need to take into account the cost incurred by running an additional round of tests in our CI/CD pipeline. Our Azure configuration is something we've put on our radar to improve. 

I'd like to confer with the rest of the core engineering team to determine appropriate steps forward if you don't mind. Thanks for your patience!

**Review by cdkini — APPROVED** [review]
We discussed 3.9 internally and came to the conclusion that it should be enabled. Thanks for taking a look!

I believe the Snowflake connector issue was holding us back from enabling it before but that should be remedied now. I'll keep a vigilant eye on this part of the pipeline to ensure everything runs smoothly!

**Comment by cdkini** [comment]
@cla-bot check

**Comment by cdkini** [comment]
Although I think you may need to sign the CLA again @dswalter not sure what's going on there.

**Comment by dswalter** [comment]
@cla-bot check

**Pull request merged**
