### PR TITLE
[MAINTENANCE] Refactor test structure for "Connecting to your data" cloud provider integration tests

### PR DESCRIPTION
**Pull request by cdkini**
Changes proposed in this pull request:
- Refactor the file structure of tests in `tests/integration/docusaurus/connecting_to_your_data/cloud`
- I've split up tests by `Pandas` and `Spark`. For GCS and Azure, which we currently working on, I've created test stubs. For AWS, I've just altered the structure but not yet split things up into `Inferred` vs `Configured`.

---

### OLD:
Screen Shot 2021-08-18 at 2 41 14 PM

---

### NEW:
Screen Shot 2021-08-18 at 2 40 24 PM

---

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by cdkini** [comment]
Should I also alter the structure of the S3 directory? 

Edit: I'm going to make it consistent and add a ticket to Jira to note that we need to write tests for the other S3 connector. This can be connected to the ticket around re-enabling the S3 tests.

**Comment by Shinnnyshinshin** [comment]
Thank you so much for this @cdkini , it's so clearly laid out. 

One concern I have with a "hard split" between the inferred and configured data connector scripts is that the scripts also contain an example for `runtime_data_connector`.

The `runtime_data_connector` is part of our "golden path" and a way that a lot of users will interact with GE, so it deserves to be highlighted, but I'm also resistant to splitting it out into its own file. (ie `azure/runtime_yaml_example.py`, `azure/configured_yaml_example.py`, `azure/inferred_yaml_example.py`) because that just seems like a lot of unnecessary overhead. 

I'd be happy to talk more about this if you'd like. Please let me know

**Comment by cdkini** [comment]
Screen Shot 2021-08-18 at 4 46 10 PM
@fjork3 @Shinnnyshinshin this is the final tree structure 🌲

**Review by Shinnnyshinshin — APPROVED** [review]
LGTM. Thank you for the discussion earlier @cdkini and @fjork3

**Review by fjork3 — APPROVED** [review]
LGTM! Thanks for the discussion, liking where this sets us up on future connectors.

**Pull request merged**
