### PR TITLE
[BUGFIX] Add `introspection_directives` to Data Connector Config Schema

### PR DESCRIPTION
**Pull request by nikhiltjoy**
Changes proposed in this pull request:
- Changes to Data Connector Config Schema to prevent Schema Scans

This [discussion](https://github.com/great-expectations/great_expectations/discussions/5370) also talks about this.

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by talagluck** [comment]
Hi @nikhiltjoy! Thank you very much for submitting this fix. Could you explain a bit more about how this works? Additionally, is there a test you could add that to confirm the functionality? Otherwise this looks great.

**Comment by talagluck** [comment]
Hi @nikhiltjoy - checking in. Is there anything else we can do to help get this over the line? Thanks!

**Comment by Shinnnyshinshin** [comment]
hi @nikhiltjoy wanting to check in again. Is there anything we can do to help on our end?

**Comment by Shinnnyshinshin** [comment]
Hi @nikhiltjoy thank you so much for your contribution to GX. We are going to close this PR for now as there has not been activity on it for some time. If you are still interested in this contribution, please feel free to re-open the PR :) Thank you again.

**Pull request closed without merging**
