### PR TITLE
[FEATURE] Add new expectation expect_sum_of_columns_to_be_equal (pandas)

### PR DESCRIPTION
**Pull request by chipmyersjr**
[Please](url) annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Add new expectation expect_sum_of_columns_to_be_equal for pandas backend. issue #1452 
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

### CODE REVIEW

**Review by Shinnnyshinshin — COMMENTED** [review]
Added more comments below

**Review by Shinnnyshinshin — CHANGES_REQUESTED** [review]
Great work @chipmyersjr  :) Thanks so much for putting this together.

I think the PR will be ready to merge with 2 minor changes. 

1.  Docstring describing the function.  This will allow the function to be looked up in the API reference for GE.  For an example of how this can be formatted, 

2. Adding the reference to the `docs/reference/glossary_of_expectations.rst` file. This allows the Expectation to be looked up along with all the other standard ones that come along with GE. 

Thanks again for your work with this... coders like yourself make GE possible :)

**Review by Shinnnyshinshin — APPROVED** [review]

**Comment by chipmyersjr** [comment]
Thanks for the review @Shinnnyshinshin !

**Review by Shinnnyshinshin — CHANGES_REQUESTED** [review]
First thank you @chipmersjr  for such a quick response to my review from yesterday. I received some feedback from a fellow teammate on my review, and I realized that I missed a few things.. so sorry that I wasn't able to include this in my first review. 

1. To keep the naming of Expectations consistent, would it be possible to change `expect_sum_of_columns_to_be_equal` to `expect_multicolumn_sum_to_equal`? This is one thing that Superconductive is trying to be strict with when it comes to Expectations that will be shipped with GE.

2. would it be possible to include an implementation of the same Expectation for a `sparkdf_dataset`? The class already has the same decorators that you used for pandas, so it hopefully won't be too complicated. 

3. Would it be possible to add an entry to the table in: `docs/reference/core_concepts/expectations/implemented_expectations.rst`, this is one of things that I missed in my review.

Again, thank you very much for your work.

**Comment by Shinnnyshinshin** [comment]
> Thanks for the review @Shinnnyshinshin !

So sorry, I just added some additional feedback I received from a teammate today... could you have a look?

**Comment by chipmyersjr** [comment]
@Shinnnyshinshin no worries! I'll look into these changes soon.

**Comment by chipmyersjr** [comment]
@Shinnnyshinshin hope it's ok i was having a lot of trouble pushing new commits to this branch so i made a new pr.

https://github.com/great-expectations/great_expectations/pull/1664

**Pull request closed without merging**
