### PR TITLE
[FEATURE] Add performance pipeline for CI

### PR DESCRIPTION
**Pull request by jdimatteo**
This PR builds off of https://github.com/great-expectations/great_expectations/pull/3280. Please only review the azure-pipeline*.yml changes in this PR. I suggest merging this PR after https://github.com/great-expectations/great_expectations/pull/3280 is merged.

Changes proposed in this pull request:
- Add CI pipeline for performance tests added in https://github.com/great-expectations/great_expectations/pull/3280.

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by talagluck** [comment]
Thanks so much for this contribution, @jdimatteo ! We will review and discuss internally, and come back with some feedback later this week.

**Review by Shinnnyshinshin — COMMENTED** [review]
Thank you very much for this @jdimatteo, I can confirm that this pipeline works. Will merge after #3280 is updated

**Review by Shinnnyshinshin — APPROVED** [review]
LGTM :) Thanks @jdimatteo

**Comment by Shinnnyshinshin** [comment]
closing because the changes have been added to #3280

**Pull request closed without merging**
