### PR TITLE
Feature/ant 20/ant 22/alexsherstinsky/instrument runtime data connector for usage statistics 2021 11 23 10 rebane deep properties filter 2021 11 30 12

### PR DESCRIPTION
**Pull request by alexsherstinsky**
### Scope
Rename `deep_filter_properties_dict()` into `deep_filter_properties_iterable()` as the latter name better fits the (broader) capabilities of this utility method.

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- JIRA: JIRA: ANT-20/ANT-22/ANT-58
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Review by Shinnnyshinshin — APPROVED** [review]
Love it 🙇🏼

**Review by NathanFarmer — APPROVED** [review]
LGTM

**Review by anthonyburdi — APPROVED** [review]
Nice :)

**Review by anthonyburdi — CHANGES_REQUESTED** [review]
Sorry, hit approve too quickly. Can you add 2 short test cases one for each of the list & set versions? (Or point me to them if they already exist, and then apologies for holding this up).

**Review by anthonyburdi — APPROVED** [review]
My mistake - it's covered in existing test cases. Thanks for clarifying @alexsherstinsky !

**Pull request merged**
