### PR TITLE
[FEATURE] Feature/render validation metadata

### PR DESCRIPTION
**Pull request by olechiw**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Add the ability to specify `properties_to_render` in expectation metadata
- Have the specified properties rendered in columns on the validation results page
- i.e.:
```meta
meta = { 
    "properties_to_render": {
         "Custom Column Header": "custom.value" 
    },
    "custom": {
        "value": "1"
    }
}
```
image

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by jcampbell** [comment]
I really like this suggestion!

I'd recommend that you change the structure of the information in meta in two ways that make it fit in with the way the rest of the rendering workflow happens.

1. I think moving the description of the "properties_to_render" key into the "notes" section makes sense, so that we can have a consistent approach to that (a la what happens via the existing markdown notes formatting: https://docs.greatexpectations.io/en/latest/guides/tutorials/explore_expectations_in_a_notebook.html?highlight=notes#adding-notes-and-metadata).
  [note: that would also require that code processing notes can also process lists, since I imagine there could be a variety of kinds of notes that are attached to expectations.]

  adding a renderer name in "format" would allow the `ValidationResultsTableContentBlockRenderer` to ask for the right code to render directly.

2. I'd like to keep as much structure at the top-level of meta as possible, so I'd prefer to have the attributes used to render in an "attributes" dictionary (or even moved directly into the relevant note itself).
Excited!


```json
{
  "meta": {
    "notes": [{
      "index": 0,
      "format": "renderer.diagnostic.meta_properties",
      "content": {
          "My Property": "property.subproperty",
          "my other prop": "otherprop"
      }
    }],
    "attributes": {
        "property": {
          "subproperty": "myvalue"
        },
        "otherprop": "othervalue"
    }
  }
}
```

**Comment by olechiw** [comment]
If we wanted to have the notes specified at the expectation suite level but the values at the individual expectation level would that work? @jcampbell

**Comment by olechiw** [comment]
In Addition -

This work will not be useful to us if we don't also address this [issue](https://github.com/great-expectations/great_expectations/issues/2692)

**Comment by olechiw** [comment]
My internship with Morningstar is ending so I will not be spearheading this work anymore

**Pull request closed without merging**
