### PR TITLE
[BUGFIX] Handle `None` and `list` `MetricValues` upon `DataAssistant` metric resolution error

### PR DESCRIPTION
**Pull request by NathanFarmer**
Changes proposed in this pull request:
- Handle `None` and `list` `MetricValues` upon `DataAssistant` metric resolution error

### Definition of Done
- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Comment by Shinnnyshinshin** [comment]
Thank you so much for this @NathanFarmer. I tried some UAT on my end, and found a similar error for the `congestion_surcharge` column. Would you be able to confirm? 

```bash
 'num_failures': 3, 'exception_info': {{'exception_traceback': 'Traceback (most recent call last):\n  File "/Users/work/Development/great_expectations/great_expectations/execution_engine/execution_engine.py", line 393, in resolve_metrics\n    resolved_metrics[metric_to_resolve.id] = metric_fn(\n  File "/Users/work/Development/great_expectations/great_expectations/expectations/metrics/metric_provider.py", line 34, in inner_func\n    return metric_fn(*args, **kwargs)\n  File "/Users/work/Development/great_expectations/great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py", line 55, in _sqlalchemy\n    return _get_column_partition_using_metrics(\n  File "/Users/work/Development/great_expectations/great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py", line 155, in _get_column_partition_using_metrics\n    bins = _determine_bins_using_proper_units(\n  File "/Users/work/Development/great_expectations/great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py", line 237, in _determine_bins_using_proper_units\n    bins = np.linspace(start=float(min_), stop=float(max_), num=n_bins + 1).tolist()\nTypeError: float() argument must be a string or a number, not \'NoneType\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/work/Development/great_expectations/great_expectations/validator/validator.py", line 1329, in resolve_validation_graph\n    self._resolve_metrics(\n  File "/Users/work/Development/great_expectations/great_expectations/validator/validator.py", line 2254, in _resolve_metrics\n    return execution_engine.resolve_metrics(\n  File "/Users/work/Development/great_expectations/great_expectations/execution_engine/execution_engine.py", line 397, in resolve_metrics\n    raise ge_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: float() argument must be a string or a number, not \'NoneType\'\n', 'exception_message': "float() argument must be a string or a number, not 'NoneType'", 'raised_exception': True}}}}
occurred while resolving metrics.
column.partition was not found in the resolved Metrics for ParameterBuilder.
```

**Review by Shinnnyshinshin — CHANGES_REQUESTED** [review]
requesting confirmation on a comment I left :) Thank you

**Comment by alexsherstinsky** [comment]
> Thank you so much for this @NathanFarmer. I tried some UAT on my end, and found a similar error for the `congestion_surcharge` column. Would you be able to confirm?
> 
> ```shell
>  'num_failures': 3, 'exception_info': {{'exception_traceback': 'Traceback (most recent call last):\n  File "/Users/work/Development/great_expectations/great_expectations/execution_engine/execution_engine.py", line 393, in resolve_metrics\n    resolved_metrics[metric_to_resolve.id] = metric_fn(\n  File "/Users/work/Development/great_expectations/great_expectations/expectations/metrics/metric_provider.py", line 34, in inner_func\n    return metric_fn(*args, **kwargs)\n  File "/Users/work/Development/great_expectations/great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py", line 55, in _sqlalchemy\n    return _get_column_partition_using_metrics(\n  File "/Users/work/Development/great_expectations/great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py", line 155, in _get_column_partition_using_metrics\n    bins = _determine_bins_using_proper_units(\n  File "/Users/work/Development/great_expectations/great_expectations/expectations/metrics/column_aggregate_metrics/column_partition.py", line 237, in _determine_bins_using_proper_units\n    bins = np.linspace(start=float(min_), stop=float(max_), num=n_bins + 1).tolist()\nTypeError: float() argument must be a string or a number, not \'NoneType\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/work/Development/great_expectations/great_expectations/validator/validator.py", line 1329, in resolve_validation_graph\n    self._resolve_metrics(\n  File "/Users/work/Development/great_expectations/great_expectations/validator/validator.py", line 2254, in _resolve_metrics\n    return execution_engine.resolve_metrics(\n  File "/Users/work/Development/great_expectations/great_expectations/execution_engine/execution_engine.py", line 397, in resolve_metrics\n    raise ge_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: float() argument must be a string or a number, not \'NoneType\'\n', 'exception_message': "float() argument must be a string or a number, not 'NoneType'", 'raised_exception': True}}}}
> occurred while resolving metrics.
> column.partition was not found in the resolved Metrics for ParameterBuilder.
> ```

@Shinnnyshinshin and @NathanFarmer : If #5937 is successful, then the metrics error should not longer be happening.  Thanks.

**Review by alexsherstinsky — CHANGES_REQUESTED** [review]
@NathanFarmer Let us wait for #5937 first -- and then see if this one should be done on top of that (or instead of that).  Thanks! /cc @Shinnnyshinshin is checking it.

**Comment by NathanFarmer** [comment]
This issue has been addressed by #5937

**Pull request closed without merging**
