### PR TITLE
[DOCS] Integrate great-expectation with ydata-synthetic

### PR DESCRIPTION
**Pull request by arunnthevapalan**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Add a reference architecture for the integration of great expectations with ydata-synthetic
- Add relevant images for the tutorial

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
- Fresh PR - doesn't close any issues

### Definition of Done
Please delete options that are not relevant.

- [✓] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [✓ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [✓ ] I have commented my code, particularly in hard-to-understand areas
- [✓ ] I have made corresponding changes to the documentation

Thank you for submitting!

### CODE REVIEW

**Review by austiezr — APPROVED** [review]
I've made some minor updates re: our style guide; otherwise LGTM! Excited to have this come in!

@arunnthevapalan we will need you to sign our CLA before this is able to move forward 🚀

**Comment by arunnthevapalan** [comment]
@austiezr the CLA has been signed now! Let me know if you need anything else from my side. :)

**Comment by austiezr** [comment]
@cla-bot check

**Comment by austiezr** [comment]
@cla-bot check

**Review by donaldheppner — APPROVED** [review]

**Comment by kyleaton** [comment]
@cla-bot check

**Pull request merged**
