### PR TITLE
[DOCS] Correct wrong datetime template syntax

### PR DESCRIPTION
**Pull request by dbeswick-bupa**
Changes proposed in this pull request:
Hello, just a minor change here. The use of "%M" indicates Minutes rather than that current month; if this is tried GE ultimately throws an exception running the checkpoint as it may try to form a date using a minute like "41" as the date portion.

### Definition of Done
Not relevant

### CODE REVIEW

**Comment by NathanFarmer** [comment]
Thank you for opening this PR @dbeswick-bupa! If you wouldn't mind signing the CLA, we will have someone from the team review this soon!

**Comment by dbeswick-bupa** [comment]
Thanks Nathan! Just figuring out who needs to approve what here; will let you know.

**Comment by NathanFarmer** [comment]
@dbeswick-bupa You should be able to sign the CLA [per these instructions](https://github.com/great-expectations/great_expectations/pull/3400#issuecomment-920490338). Then you will want to add an entry to `docs_rtd/changelog.rst` under the header `develop` describing the PR. Once you do that I will merge the changes into the `develop` branch.

**Comment by NathanFarmer** [comment]
Hi @dbeswick-bupa, have you made progress on this? If you don't anticipate being able to move forward anytime soon we can close this PR temporarily.

**Comment by dbeswick-bupa** [comment]
Hello Nathan, thanks for your patience. Believe it or not I am working actively on it, tracking down the necessary people who have the necessary signoffs. I know it's a bit funny because it's such a small change; if it's causing you any inconvenience, then please close it and I can re-open it or make a new one when I have something new to report. Thanks!

**Comment by austiezr** [comment]
Hey @dbeswick-bupa! We are going to go ahead and close this out for now; thanks so much for raising this and for your work on it.

**Comment by dbeswick-bupa** [comment]
Fair enough! Thanks

**Pull request closed without merging**
