### PR TITLE
[DOCS] off-by-one error in linking to static images in the Walkthrough

### PR DESCRIPTION
**Pull request by NimaVaziri**
This fixes a few broken static image references which resulted in the images/gifs not being displayed in a few steps of the Walkthrough.

## Before fix
Screen Shot 2020-11-04 at 10 42 32 PM
Screen Shot 2020-11-04 at 10 42 43 PM
Screen Shot 2020-11-04 at 10 42 51 PM

## After fix
Screen Shot 2020-11-04 at 10 45 56 PM
Screen Shot 2020-11-04 at 10 46 06 PM
Screen Shot 2020-11-04 at 10 46 19 PM

### CODE REVIEW

**Review by eugmandel — APPROVED** [review]
Thank you, @NimaVaziri !

**Comment by eugmandel** [comment]
@NimaVaziri Thank you for the fix! Could you please make sure that you sign the CLA so that we can merge your PR? Thank you!

**Comment by NimaVaziri** [comment]
@eugmandel thanks for approving! I'm getting confirmation on which license I should sign. As soon as I know, I'll post another comment so the bot can update the PR's status.

**Comment by NimaVaziri** [comment]
@cla-bot check

**Pull request merged**
