### PR TITLE
vectorize regex expectations

### PR DESCRIPTION
**Pull request by RoyalTS**
one more set of vectorized expectations

### CODE REVIEW

**Comment by jcampbell** [comment]
We should decide how we want to address this pandas behavior change more fully...currently, by defaulting to the legacy sort behavior, we end up with lots of warnings when running against newer versions. I'm actually open to just requiring a newer version of pandas and updating throughout.

**Comment by RoyalTS** [comment]
What pandas version to require seems a bit out of scope for this PR. Want to tell me what behavior the code in the PR should respect and you can deal with the more general issue in a separate issue?

**Comment by jcampbell** [comment]
The PR is failing because `sort` wasn't introduced for `concat` until pandas version 0.23.

If you just drop that from the PR, your build will succeed on all versions of pandas currently supported by GE.

**Comment by RoyalTS** [comment]
Got it. So done!

**Review by jcampbell — APPROVED** [review]
Thank you!!

**Pull request merged**
