### PR TITLE
Feature/rapid custom expectations

### PR DESCRIPTION
**Pull request by abegong**
Implements #78, with tests

### CODE REVIEW

**Comment by jpcampb2** [comment]
Looks good. Two initial comments:

1. Could we test for the new functions' parameters to match the kind of expectation that they are? For example, I think that the current tests should fail the test functions because (a) none of them includes the required `meta` parameter, and (b) the aggregate function currently accepts `mostly` but should not. (And that makes me realize how weird it might be that we have a "secret" `meta_notes` parameter)

2. Documentation: Docstrings for the new functions, and addition of description to the docs.

**Comment by abegong** [comment]
1. I see where you're going, but I'm not sure how to implement this. Can we open it as a separate issue after merging this PR?

2. Will do

**Comment by abegong** [comment]
On reflection, would it make sense to incorporate (1) as part of the decorators themselves?

Raise errors if expectation functions don't have the proper parameters?

**Comment by jpcampb2** [comment]
Perhaps, but it seems strange to me to do that every time we run or validate an expectation--since the premise is that the data is what's changed vs. the expectation itself.

I think doing the check here in the "rapid prototyping" environment is right. Once it is promoted to being implemented in a custom expectation class, there's no longer a need to essentially type-check the expectation each time.

What about adding a list of required parameters for `@expectation`, `@column_map_expectation` and so forth, and then checking that those are all present in these tests.

(And concretely for this PR: will you add meta / remove mostly so that we've got consistency with the current api?)

**Comment by abegong** [comment]
Just fixed meta and mostly.

Please ignore the notebook I committed---it belongs on another branch, but reverting and rebasing feels like more trouble than it's worth.

Can we close this out?

On incorporating checks as part of the decorator: I agree that we should only run checks when creating expectations---not every time we run them.

We can do that by including the checks inside the decorator function, but *outside* the wrapper.

**Comment by jpcampb2** [comment]
As discussed, we'll add logic for checking expectations' conformance to defined parameters to the decorators in the future.

**Review by jpcampb2 — APPROVED** [review]

**Pull request merged**
