### PR TITLE
[FEATURE] Add support for nested columns in PySpark expectations

### PR DESCRIPTION
**Pull request by bramelfrink**
Hello, 

We are currently using Great Expectations for Parquet data and running the expectations with PySpark. We noticed that there is currently no support for nested columns. This PR aims to resolve this.

DataFrames like the following should now be supported:
```
|-- name: string (nullable = true)
|-- age: integer (nullable = true)
|-- address: struct (nullable = false)
|    |-- street: string (nullable = true)
|    |-- city: string (nullable = true)
|    |-- house_number: integer (nullable = true)
|-- name_duplicate: string (nullable = true)
|-- non.nested: string (nullable = true)
```

Non-nested columns with dot notation (like `non.nested`) are also supported.

Changes proposed in this pull request:
- Adding support for nested columns in PySpark expectations. 
- Support non-nested columns that do have dot notation

### CODE REVIEW

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by kyleaton** [comment]
@ge-cla-bot check

**Comment by kyleaton** [comment]
@cla-bot check

**Comment by jcampbell** [comment]
Thank you for this PR! I'm super excited about it. I'm wondering whether there might be a way to avoid having a flag for the column names, such as by allowing column names with backticks in them as a way to avoid having to specify the desire for nonnested variants?

What do you observe today when you use standard dot notation for nested column names?

**Comment by bramelfrink** [comment]
Hello @jcampbell, thank you for showing interest :)

With the current state of Great Expectations, I observe the following:

Given a DataFrame with a schema like this
```
root
 |-- weight: double (nullable = true)
 |-- animal_type: string (nullable = true)
 |-- animal_interpretation: struct (nullable = true)
 |    |-- is_large_animal: boolean (nullable = true)
 |    |-- is_mammal: boolean (nullable = true)
```

Running
`batch.expect_column_values_to_be_of_type("animal_interpretation.is_mammal", "BooleanType")`

Results in
```
ValueError: Unrecognized column: animal_interpretation.is_mammal
```

The reason behind this is this:
```
# great_expectations/dataset/sparkdf_dataset.py
...
759         try:
760             col_data = [f for f in self.spark_df.schema.fields if f.name == column][0]
761             col_type = type(col_data.dataType)
...
```

Line `760` goes over the field names of the DataFrame, but this does not include the nested field names. Similar issues happen in other expectations.

Regarding avoiding the flags: that seems to be possible. I updated my PR to reflect that.

**Review by jcampbell — APPROVED** [review]
Excellent -- thank you!

**Comment by bramelfrink** [comment]
@jcampbell the docs also keep failing. Is there any action that I need to take on that?

**Comment by jcampbell** [comment]
I'm guessing it's a simple build issue -- we discovered a bizarre incompatibility with pandas 1.1 and autoapi in our docs builds, but that should be fixed. Somehow github appears not to have rebuilt after my last commit though.

**Comment by jcampbell** [comment]
Ok, I just manually did the merge with develop and will let the full build move through; that should fix the docs build issue.

**Comment by bramelfrink** [comment]
I moved my `pyspark` imports into my test functions to prevent `ModuleNotFoundError: No module named 'pyspark'
`. I'm not really happy with this fix. 

In the pipeline configuration, I see that a `--no-spark` flag is set in some cases. Is it possible to skip my entire test file when this flag is is set?

**Comment by jcampbell** [comment]
@bramelfrink --> I was looking at the same thing and wanted to also update the underlying problem that was preventing your `type_list` expectation from working, so I've also added a bugfix to the changelog for this PR.

**Comment by jcampbell** [comment]
I believe we could update the test to check that flag, but even that would require the import being either relocated or moved inside a try/except block at the top of the file (which is what we do in most other places in the codebase).

**Comment by jcampbell** [comment]
I'm about to create a new release this morning, so would like to merge this PR once tests pass with the current moved-import fix.

**Comment by jcampbell** [comment]
Interesting. It appears that the fact that the column name "__target_col" is reused is causing problems when evaluating multiple expectations back-to-back.

If we use a unique column name, the problem appears to resolve.

**Comment by bramelfrink** [comment]
That is odd. Is the DataFrame cached somehow? If so, maybe we can unpersist it?

**Comment by jcampbell** [comment]
It is cached -- but I think we do have an explicit call to unpersist as well.

Would you be able to take a closer look at the test failures? Again, I was able to address the issue by adding a unique random string to each "__target_col" as an experiment to verify the issue, but a more elegant solution must be out there...perhaps doing something as simple as a replace. I just pushed a commit with that --> what do you think of that approach?

**Pull request merged**
