### PR TITLE
Fix/issue313 and Test Migration double whammy

### PR DESCRIPTION
**Pull request by ccnobbli**
#313 `expect_column_values_to_be_[in_type_list][of_type]` was quite buggy with the extra `target_datasource` parameter that was somewhat obfuscated and did not have desired behavior. 

This addresses the bug found by @smontanaro, where "float" type data was not being mapped to it's correct `target_datasource`. I did this by completely removing the `target_datasource` from the expectations and comparing it to all of the possible types a "primitive" type can take, such as `int` and `np.int_` when you want to check for type `int`. This may be simplistic, but I think it's a good approach for now, if even just a stop-gap solution because:

- It does just what the expectation says: checks if each of the values in a column are a particular type
- This separates functionality from potential expectations for parseability and data storage type

Thoughts?

### CODE REVIEW

**Comment by abegong** [comment]
I like where this is going!  The test migration is much needed.

That said, I'm not confident that removing `target_datasource` is going to work out...

How would this work in a SQL context?

**Comment by ccnobbli** [comment]
Maybe I'm thinking about this in the wrong way, but the SQL implementation of this expectation would just look for SQL types, because that's where the data is coming from (A SQL source), not from anywhere else. Same for Spark. It sounds simple enough, which makes me doubt whether I'm missing a bigger picture here.

**Comment by abegong** [comment]
The issue is portability. If I have some dataset in a csv, then I load it into a SQL table, then I access it using Spark, how do my expectations know which context I'm in?

If we drop `datasource`, then it makes it harder for expectations to move across contexts with the data.

Also, is it possible for a single pandas column to contain multiple types?

**Comment by ccnobbli** [comment]
Ok, I can see how that is a valid concern. I'll want to see a concrete example though to fully conceptualize that :D

And yes to your last question:
```
df = pd.DataFrame({
    "a": [5, "1", True],
})
type(df.a[0])
```
> <class 'int'>

`type(df.a[1])
`
> <class 'str'>

`type(df.a[2])
`
> <class 'bool'>

**Comment by abegong** [comment]
Oh, lovely. pandas is so weird.

Would we lose anything if we relied on `dtype`s, and separated out `expect_column_values_to_be_parseable_as_int`, etc. into separate expectations?

**Comment by smontanaro** [comment]
> Oh, lovely. pandas is so weird.
>

Actually not so weird in this situation. I think if you print the column
you'll be rewarded with

dtype=object

at the bottom. ;-)

I don't know quite how this is all supposed to work. Since this is all
happening in Python, it seems to me that the only directly observable types
would be the base Python or numpy types.

For example, you wouldn't really have any true SQL objects in-hand. I think
the best you can do is answer the question, "If I handed this thing to SQL,
would it correctly interpret it as type blah?" So, that might be true for
"2018-06-14T00:00:00" if you're curious if it will be interpreted as a SQL
datetime object. Even something that seemingly obvious gets a bit
squirrelly if you tack on a time zone offset. Even worse, "SQL" isn't just
one thing. SQL Server might barf on something MySQL or Oracle are perfectly
fine with.

**Comment by abegong** [comment]
@smontanaro, on SQL:

In addition to `PandasDataset`, Great Expectations supports a `SQLAlchemyDataset`, which evaluates Expectations natively within SQL using SqlAlchemy. We're also introducing a third execution context: Spark dataframes.

The syntax for Expectations needs to be the same across executions contexts---hence the conversation about portability.

**Comment by ccnobbli** [comment]
@abegong @jpcampb2 Alright, this is ready for y'all to look at - I think coverage decreased because I ended up taking out more code than I put in - otherwise the expectations themselves have 100% coverage.

**Review by jpcampb2 — CHANGES_REQUESTED** [review]
This looks good. @ccnobbli is it possible to apply the following simple patch since I don't think you need both string_types and text_type?

```
@@ -13,7 +13,7 @@ import numpy as np
 import pandas as pd
 from dateutil.parser import parse
 from scipy import stats
-from six import string_types, integer_types, text_type
+from six import string_types, integer_types
 
 from .base import Dataset
 from .util import DocInherit, recursively_convert_to_json_serializable, \
@@ -416,7 +416,7 @@ class PandasDataset(MetaPandasDataset, pd.DataFrame):
             "float": [float, np.float_],
             "double": [float, np.longdouble],
             "bytes": [bytes, np.bytes_],
-            "string": [str, np.string_, text_type] + list(string_types)
+            "string": [str, np.string_] + list(string_types)
         }
 
         target_type = type_map[type_]
@@ -437,7 +437,7 @@ class PandasDataset(MetaPandasDataset, pd.DataFrame):
             "float": [float, np.float_],
             "double": [float, np.longdouble],
             "bytes": [bytes, np.bytes_],
-            "string": [str, np.string_, text_type] + list(string_types)
+            "string": [str, np.string_] + list(string_types)
         }
 
         # Build one type list with each specified type list from type_map
```

**Comment by ccnobbli** [comment]
@jpcampb2 I agree, having both string_types and text_types felt redundant. For whatever reason, text_types works while string_types does not. I went ahead and removed string_types instead.

**Review by jpcampb2 — APPROVED** [review]

**Pull request merged**
