### PR TITLE
Fixed typo in notebook and related tests (expectatons > expectations)

### PR DESCRIPTION
**Pull request by spbail**
Just a search and replace.

### CODE REVIEW

**Comment by spbail** [comment]
Re: linter errors, I basically only added 1 character per line, so won't fix the issues for now.

**Comment by roblim** [comment]
Looks like Travis build is failing.

**Review by Aylr — DISMISSED** [review]
lgtm

**Comment by Aylr** [comment]
Ok. It looks like the most likely cause of these unrelated failures is the 2 new releases of click in the last 24 hours. Fixing.

**Pull request merged**
