### PR TITLE
Fix docstring on expectation

### PR DESCRIPTION
**Pull request by andyjessen**
List of column names can be in any order. It also does not need to match exactly when exact_match keyword argument set to False. This commit modifies docstring documentation.

- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code

### CODE REVIEW

**Comment by rdodev** [comment]
Hey @andyjessen thanks for PR.


@cdkini is this a case where the docstring is wrong, or is there a bug the makes the docstring inaccurate?

**Comment by andyjessen** [comment]
Hi @rdodev  - 

My sense is that the docstring has errors. See example below.  I changed the order of the columns and omitted two ("SexCode", "Unnamed: 0"). This still returns a success. 

Example:
`
titanic_df.expect_table_columns_to_match_set(['PClass','Name','Age','Sex','Survived'], exact_match=False)
`
Returns:
```
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": [
      "Age",
      "Name",
      "PClass",
      "Sex",
      "SexCode",
      "Survived",
      "Unnamed: 0"
    ],
    "details": {
      "mismatched": {
        "unexpected": [
          "SexCode",
          "Unnamed: 0"
        ]
      }
    }
  },
  "meta": {},
  "success": true
}
```

**Comment by rdodev** [comment]
@andyjessen there's clearly an issue. What I'm trying to find out with the team is whether the docstring is inaccurate or whether there was a regression introduced somewhere along the line such that it no longer works as described.

@alexsherstinsky any insight here?

**Comment by alexsherstinsky** [comment]
> @andyjessen there's clearly an issue. What I'm trying to find out with the team is whether the docstring is inaccurate or whether there was a regression introduced somewhere along the line such that it no longer works as described.
> 
> @alexsherstinsky any insight here?

@rdodev I am not sure whether the current state is due to a long-standing error or due to a regression; having said that, I feel that the contributor's point is valid and we should approve this pull request.  Thank you so much, @andyjessen and @rdodev -- any follow-up questions are welcome!

**Review by rdodev — APPROVED** [review]

**Comment by rdodev** [comment]
Thanks @alexsherstinsky

Thanks for patience and contribution @andyjessen. I have approved this PR.

**Comment by rdodev** [comment]
@cla-bot check

**Pull request merged**
