### PR TITLE
[DOCS] Clean up Docusaurus refs after changes made to integration tests

### PR DESCRIPTION
**Pull request by cdkini**
Changes proposed in this pull request:
- Docusaurus linking requires exact line numbers; changes made to the linked file will impact our docs.
- The changes here restore the docs back to their correct state.

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by cdkini** [comment]
@cla-bot check

**Review by alexsherstinsky — APPROVED** [review]
LGTM -- thank you, @cdkini !!!

**Review by Shinnnyshinshin — APPROVED** [review]
approved as well :) Thank you @cdkini

**Comment by cdkini** [comment]
@cla-bot check

**Pull request merged**
