### PR TITLE
[FEATURE] Add new usage stats event for CLI init

### PR DESCRIPTION
**Pull request by eugmandel**
Changes proposed in this pull request:
- Added a new usage stats event for the case when a data context is created through CLI.

Reasoning:
Knowing that a data context was created by running CLI init will help us understand the top of the activation funnel.

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For nontrivial changes, we will conduct both a design review and a code review. Please tag a core team member for code review, or leave blank and we will find someone for you!

- [ ] Design Review (@jcampbell)
- [x] Code Review

Thank you for submitting!

### CODE REVIEW

**Review by jcampbell — CHANGES_REQUESTED** [review]
Three requests:

1. Rename this message to just be `cli.init` in keeping with the rest of the naming convention for messages
2. Send the `success=False` message in the event of a failure
3. Add a test for cli sending the message (using mocked stats) to up our coverage of expected usages stats.

**Review by Aylr — CHANGES_REQUESTED** [review]
this is a really nice addition! I would love to see at least one test cover the usage event. If you want to pair we can do this together in less than 5 minutes!

**Comment by eugmandel** [comment]
> Three requests:
> 
> 1. Rename this message to just be `cli.init` in keeping with the rest of the naming convention for messages
> 2. Send the `success=False` message in the event of a failure
> 3. Add a test for cli sending the message (using mocked stats) to up our coverage of expected usages stats.

1. Renamed to "cli.init.create" based on our conversation.
2. Not data context id will be available in the case of a failure, so we can't send this event. We should address this, but probably as a separate issue.
3. Test added - thank you @Aylr !

**Review by jcampbell — APPROVED** [review]
🎉 !

**Pull request merged**
