### PR TITLE
Naming conventions

### PR DESCRIPTION
**Pull request by abegong**
This replaces `result_obj` with `result` everywhere in the codebase.

I did `result_object` first, but it felt horribly redundant.

Also, I'd like to replace `DataSet` with `Dataset`. @jpcampb2 , I'm going to go ahead unless you stop me.

As long as we're breaking the API, let's get in all the breaks that we want.

### CODE REVIEW

**Review by jpcampb2 — APPROVED** [review]
Oh yeah. I of course have to go on record as having been strongly for all of these. :)

**Comment by jpcampb2** [comment]
@abegong Also, agree on the change of DataSet to Dataset throughout.

These changes will trigger some changes in the PR I just made for the data context API. Mind making the parallel changes in that branch as well?

**Comment by abegong** [comment]
Yes, I can do that.

**Comment by abegong** [comment]
@jpcampb2 I messed something up in the final merge, but I can't figure out what it is.

Everything breaks when running `pytest`. The error being returned is an `ImportError`, but I can't find anything wrong with the imports.

I spent a couple hours on this last night and made no progress.

Would you mind taking a look?

**Comment by jpcampb2** [comment]
OK, I think this is squared away.

I checked out all changes except the merge commit of develop, and instead rebased all of them onto develop. I then also became drunk with the power of git rebase, and added the changes to the data context api, and then squashed them into the two key changes: result_obj -> result and DataSet -> Dataset. I also added the change to the new datacontext file names.

(I also pushed naming-conventions-orig as the original branch you had with no changes just so we don't lose anything on review).OK, I think this is squared away.

I checked out all changes except the merge commit of develop, and instead rebased all of them onto develop. I then also became drunk with the power of git rebase, and added the changes to the data context api, and then squashed them into the two key changes: result_obj -> result and DataSet -> Dataset. I also added the change to the new datacontext file names.

(I also pushed naming-conventions-orig as the original branch you had with no changes just so we don't lose anything on review).

**Comment by abegong** [comment]
@jpcampb2 on rebase:
giphy

**Comment by abegong** [comment]
You're going to have to approve this, since it's technically my PR.
(Although at this point, I must cede spiritual ownership to you.)

**Comment by jpcampb2** [comment]
Merged! (And, note it looks like we might be getting the right coverage info now...fingers crossed).

**Pull request merged**
