### PR TITLE
Fix for Issue 139

### PR DESCRIPTION
**Pull request by dlwhite5**
Used https://stackoverflow.com/questions/22155951/how-to-subclass-pandas-dataframe as a guide. Also created test (test_ge_pandas_subsetting).

### CODE REVIEW

**Comment by jpcampb2** [comment]
@dlwhite5 I think this PR came from the develop branch instead of your new issue branch.

**Comment by dlwhite5** [comment]
Good point. Need to work on this again as the behaviour is not quite right.
Whilst the object type is correct, it loses the parent's attributes.

**Comment by abegong** [comment]
I'm confused by this PR. It doesn't change any files.

The source branch is `LAS-NCSU:develop` and the destination branch is `great-expectations:develop`.

Is it possible this was meant to merge from a different source branch?

**Comment by dlwhite5** [comment]
Yep.

However, the committed code only solves part of the problem. The returned
type after subsetting is correct, but the inheritance/propagation of the
expectations is not.

**Comment by jpcampb2** [comment]
I'm going to close this PR while it's being revised to match the ongoing discussion in issues. We can reopen when it's ready for review.

**Pull request closed without merging**
