### PR TITLE
[BUGFIX] Data Docs eval params bug

### PR DESCRIPTION
**Pull request by roblim**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Escape $ properly if eval params present in string template

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Thank you for submitting!

### CODE REVIEW

**Comment by jcampbell** [comment]
Design review: ✅

**Review by eugmandel — COMMENTED** [review]
@roblim Do we have a test that covers this case?

**Comment by roblim** [comment]
> @roblim Do we have a test that covers this case?

Not yet. I'll add later today.

**Comment by roblim** [comment]
Closing in favor of https://github.com/great-expectations/great_expectations/pull/1431 (I accidentally started using a different local branch)

**Pull request closed without merging**
