### PR TITLE
[FEATURE] enable mostly for expect_compound_columns_to_be_unique

### PR DESCRIPTION
**Pull request by kimfrie**
xref: https://github.com/great-expectations/great_expectations/issues/6532

I saw that there has been previously worked on adding mostly to `expect_compound_columns_to_be_unique`.
It was not implemented for SQL.

Also I got a keyError when passing in mostly param before I made the changes. 
image

Changes proposed in this pull request:
- expect_compound_columns_to_be_unique to accept mostly param for SQL 
- Bugfix for mostly_pct KeyError ()

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by kimfrie** [comment]
@cla-bot check

**Comment by Shinnnyshinshin** [comment]
hi @kimfrie it looks mostly 😁 good to me. Would you be able to run the PR through a linter? [More information can be found here](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style/#linting)

**Comment by kimfrie** [comment]
@Shinnnyshinshin 
Thanks for pointing me to the docs. I applied the linter 👍

**Review by Shinnnyshinshin — APPROVED** [review]
Looks great ✅ Thank you @kimfrie

**Pull request merged**
