### PR TITLE
Fix details naming (#380)

### PR DESCRIPTION
**Pull request by jpcampb2**

### CODE REVIEW

**Review by abegong — COMMENTED** [review]
Wait, I thought we were going to remove one of these rows...? Why keep two?

**Comment by jpcampb2** [comment]
I was conflicted...I thought leaving it in the "column_aggregate_expectations" and calling out there the specific behavior of when details would be included was usefully more complete that including it only on the first row...but I'm open to other ways to convey that nuance too. Preferences?

**Comment by jpcampb2** [comment]
I'm still inclined for the double-inclusion...ping on this.

**Review by abegong — APPROVED** [review]
:+1:

**Pull request merged**
