### PR TITLE
Feature/profiling

### PR DESCRIPTION
**Pull request by abegong**
This branch starts to implement the profiling spec we discussed today.

It's NOT ready for full review yet.

For the moment, it'd be good to get a sanity check on the way I'm doing classes, specifically `profile.base.DataSetProfiler` and its two subclasses, `PseudoPandasProfiler` and `ColumnsExistProfiler`.

* Are the core methods right?
* Does this inheritance pattern work?

The internal logic, including the objects returned by the profilers is still an early prototype.

### CODE REVIEW

**Comment by abegong** [comment]
On reflection, here's how I think we should go forward:
1. Finish a very minimal version of profiling and merge it back to `feature/data_context`.
2. Start a separate branch to handle the CLI file refactor.
3. Make necessary improvements to the CLI.
4. Further refine profiling by fleshing out the list of profiled expectations, adding safeguards, and stress-testing against a broad array of datasets.

There's a fair amount of work in (4).

To prep for demos on Thursday, I suggest we divert to rendering after (3), then come back to (4) a few days later. That'll leave us with brittle demo-ware for a few days, but with a clear path to pay down technical debt quickly.

Good?

**Comment by abegong** [comment]
Here's a short demo video:

https://www.loom.com/share/ef7fc36dd84e4e7f9b016ea948900964

For the record, the whole profiling task came in at:
```
real	1m0.062s
user	0m53.423s
sys	0m1.520s
```

**Comment by abegong** [comment]
AFAICT, this is ready for review.

The workhorse abstractions are the `context.profile_datasource` method and `profile.base.DataSetProfiler` class. If those look good, the rest is implementation details.

There are several issues that I'm not attempting to resolve now:
* logging isn't working as expected, so I'm using prints.
* We need better error checking in context.profile_datasource. Copious FIXMEs mark the spot.
* Most of the profiler safeguards we've discussed are actually concerns of the generator. Leaving those for future implementation.
* BasicDatasetProfiler is still weak sauce. It needs more and better expectation logic and hasn't been stress tested against lots of incoming datasets yet.
* We want to add a profiling section to `great_expectations init`. I'm saving that for the next PR.
* The validation_results meta fields probably need embellishment. At the moment, I'm trusting the context to handle this, so no specific information from the profiler gets stored.

**Comment by jcampbell** [comment]
This PR appears to have been built on a broken branch, so I am going to close it, I opened #497 with only the desired commits, and just put a review in that one.

**Pull request closed without merging**
