### PR TITLE
[HACKATHON] Add Expect Column Value to Be Valid ICD-10 Category or Subcategory

### PR DESCRIPTION
**Pull request by andyjessen**
This commit adds an experimental expectation. Expectation determines whether a column value matches a valid ICD-10 category or subcategory. Other values (ICD-10 block, ICD-10 chapter, other) will result in failed expectation.

### Definition of Done

- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

### CODE REVIEW

**Review by austiezr — CHANGES_REQUESTED** [review]
Hey @andyjessen ! Great to see this submission. A couple of small items:

- We'll want to fix the filename to `expect_column_values...` as opposed to `expect_column_value...`
- Take a look at our [linting](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style#linting) doc; we're getting some flags thrown around `black` and `isort`

**Comment by andyjessen** [comment]
Hi @austiezr  - I followed the manual steps within the linting doc. I am getting the following ImportError exception upon commit.

> ImportError: cannot import name '_unicodefun' from 'click'

A quick google search leads me to this page:  https://github.com/psf/black/issues/2964

Do I need to pin the Click version?

**Comment by austiezr** [comment]
You should be able to resolve this by pinning `black==22.3.0` as per [this PR](https://github.com/great-expectations/great_expectations/pull/4577). This resolution was just introduced last week as a part of the v0.14.3 release.

**Comment by andyjessen** [comment]
Hi @austiezr - I merged the upstream commit with the change to requirements-dev-contrib.txt file. I reran the checks manually within the pre_commit_dev environment. Besides black, each ran without warning or any message. The black one noted "All done! ✨ 🍰 ✨" I tried to commit again and got the same message. I uninstalled the pre-commit and committed the linting changes.

Does this work?

**Review by austiezr — APPROVED** [review]
LGMT! Thanks @andyjessen ! 🚀

**Pull request merged**
