### PR TITLE
[BUGFIX] convert abs path to rel path

### LINKED ISSUE #1971: path in checkpoint metadata is not relative path
**Describe the bug**
when I push checkpoints to a remote repo, the metadata says it's path doesnt exist. I have inspected the file, and I found the path is not relative path. It literally shows the path in my local machine.

**To Reproduce**
1. great_expectations init (create with new suite scaffold)
2. great_expectations checkpoint new new.checkpoint suite.name
3. vim great_expectations/checkpoints/new.checkpoint.yaml
4. see the path variable

**Expected behavior**
the path should not be absolute path but relative one. 

**Environment (please complete the following information):**
 - OS: Linux and Great Expectation GitHub Action
 - GE Version: 0.12.3

### PR DESCRIPTION
**Pull request by deep-diver**
Changes proposed in this pull request:
- convert absolute file path to relative file path when creating a new checkpoint via `great_expectations checkpoint new`
- After selecting data from filesystem for a suite, when creating a new checkpoint the `path` shown in the checkpoint metadata is an absolute path. 
- this causes a problem when running great_expectation on GitHub Action or other cloud services for data CI test.

Previous Design Review notes:
- This PR should fix #1971

### CODE REVIEW

**Comment by deep-diver** [comment]
@cla-bot check

**Comment by deep-diver** [comment]
@cla-bot check

**Comment by eugmandel** [comment]
@deep-diver It looks like switching between abs and rel path causes some tests to fail, since the expected values have changed.

**Comment by deep-diver** [comment]
@eugmandel hm.. I have tested it works fine in `pip install -e .` environment. Do you think it would be fine if I pass the all the `pytest`?

**Review by spbail — COMMENTED** [review]
Thank you for the submission! We discussed internally and decided that we would prefer to not change the current workflow for existing users that might be relying on the current path structure. However, that's informed in part by upcoming work in the CLI that will improve this workflow. We will take the CI use case into account for that. If you'd like to help with the design, please ping @eugmandel in the GE Slack! Thank you!

**Pull request closed without merging**
