### PR TITLE
Feature/remove expectation

### PR DESCRIPTION
**Pull request by abegong**
Implements #68

### CODE REVIEW

**Comment by jpcampb2** [comment]
Love the disciplined approach here! I'm confused about the inclusion of the `discard_*_kwargs` parameters to the `remove_expectation` function: it seems confusing to me to have parameters that, unlike the others which match against an expectation to remove, seem to affect the behavior of what remove_expectations itself does.

In looking through the comment you made on refactoring out from the `get_expectation_config` function, I wondered if that motivated the inclusion, but that made me wonder about the logic there: do we really want to modify the actual expectation config there, or do we, there, want to be working with a copy that is returned?

**Comment by abegong** [comment]
Ah. The `discard_*_kwargs` parameters don't affect which expectations are removed. They only affect how expectations are displayed when they're returned.

To your second point: `get_expectation_config` doesn't affect the underlying config at all. The returned config is a copy of `_expectations_config`, not the original object.

I think that's the way we want it to be. It works nicely for now, and is more compatible with a future where `_expectations_config` is a full history of exploration.

**Comment by abegong** [comment]
As discussed:

* Add a `find_expectations` function, that includes all the `discard_*_kwargs` arguments.
* Remove `discard_*_kwargs` arguments from `remove_expectations`
* Keep `dry_run` in `remove_expectations`. It's a thin wrapper around `find_expectations` that always uses the default values for `discard_*` args.
* If `dry_run`!= True, `remove_expectations` doesn't return anything.

**Comment by abegong** [comment]
Ready for review.

**Review by jpcampb2 — APPROVED** [review]
Really nice!

**Pull request merged**
