### PR TITLE
[DOCS] remove broken link

### PR DESCRIPTION
**Pull request by gsajko**
removed broken link

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- removed broken link 

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

### CODE REVIEW

**Review by Aylr — CHANGES_REQUESTED** [review]
Great catch on this @gsajko ! If you don't mind would you please add a line to the `docs/changelog.rst` file with the title of the PR so we can give you some public attribution? If that's not something you are interested in, let me know and we'll merge this nice fix!

**Comment by gsajko** [comment]
@Aylr  I did that (not sure if correctly, I'm noob at git), and also removed that broken link from spark and SQL notebooks as well.

**Review by Aylr — APPROVED** [review]
Congrats on your first contribution! We truly appreciate these nice fixes. Thank you!

**Comment by Aylr** [comment]
> @Aylr I did that (not sure if correctly, I'm noob at git), and also removed that broken link from spark and SQL notebooks as well.

Thanks for going above and beyond with the other notebooks!

**Comment by Aylr** [comment]
FYI @gsajko I'm going to look at the test failures which I'm pretty sure have nothing to do with your work. I'll let you know what I find later today.

**Comment by Aylr** [comment]
@gsajko Good news! The test failures **have nothing to do with your changes**! I am working on a fix that I will submit against `develop` which will unbreak all up to date PRs including yours once it is complete. For now you don't need to take any action and I will notify you when your PR is merged (likely within a few days)!

Thanks for your patience on this.

**Comment by Aylr** [comment]
@gsajko Merged! Thanks for your patience and congrats on your first PR! 🎉

**Pull request merged**
