### PR TITLE
enhance ge.read_json test Closes #205

### LINKED ISSUE #205: `ge.read_json` function needs more robust tests.
Right now, we're just testing whether an exception is raised.

### PR DESCRIPTION
**Pull request by chipmyersjr**
Was interested in helping out with this project and wanted to take on https://github.com/great-expectations/great_expectations/issues/205 to get my feet wet.

Changes proposed in this pull request:
- Previously test for ge.read_json just executed method without any asserts and would only fail if method threw an exception.  This changes brings the test in line with tests for related method by adding assertions that check some of the data returned and column headers to make sure data was actually loaded and that the method returns an instance of the PandasDataset class.
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For nontrivial changes, we will conduct both a design review and a code review. Please tag a core team member for code review, or leave blank and we will find someone for you!

- [ ] Design Review (@jcampbell)
- [ ] Code Review

Thank you for submitting!

### CODE REVIEW

**Comment by chipmyersjr** [comment]
@cla-bot check

**Comment by chipmyersjr** [comment]
closed see travis build did not succeed

**Comment by abegong** [comment]
@chipmyersjr Are you having trouble with the CLA bot?

**Comment by chipmyersjr** [comment]
@abegong Yes, sorry I hadn't added comment here yet... I had forgotten to configure git with my handle and then when trying to fix that I accidentally  got this branch in a weird state.

I opened a new PR where all checks are passing...

https://github.com/great-expectations/great_expectations/pull/1345

**Pull request closed without merging**
