### PR TITLE
[FEATURE] Add package, contributors and metrics filter in Algolia script for expectation

### PR DESCRIPTION
**Pull request by kod-er**
Add a filter for the field "package" in the expectation upload algolia script.

### CODE REVIEW

**Comment by kyleaton** [comment]
@cla-bot check

**Review by Shinnnyshinshin — APPROVED** [review]
Thank you very much for adding this @kod-er. Approved ✅

**Review by Shinnnyshinshin — CHANGES_REQUESTED** [review]
Update : PR is approved, but wanting to hold off on merging until we address the root cause of the gallery issues. I'll place the Request Changes tag on here for now :)

**Review by Shinnnyshinshin — APPROVED** [review]
LGTM

**Review by kenwade4 — APPROVED** [review]

**Pull request merged**
