### PR TITLE
[FEATURE] Allow Data Docs to be rendered in night mode

### LINKED ISSUE #3814: Having a dark mode for DefaultJinjaIndexPageView or ValidationResultsPageRenderer
**Is your feature request related to a problem? Please describe.**
More for a styling feature. 

**Describe the solution you'd like**
When using 
```python
# new_dataset is a great expectations PandasDataset
validation_result = new_dataset.validate(only_return_failures=True)
document_model = ValidationResultsPageRenderer().render(validation_result)
report = DefaultJinjaPageView().render(document_model)
HTML(report)
```

then the page appears white (which is fine). However all the rest of my environment is black / gray and it would be really nice to have a dark mode for those renderings.  

**Describe alternatives you've considered**
Keep it white and loose my eyes. 
Tweak the styling myself but I have no idea where to change it. 

**Additional context**
Using it in VsCode Jupyter built-in notebooks totally mess up with theming. 

Thanks in advance, 
Have a great day

### PR DESCRIPTION
**Pull request by OrtalG**
Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- add css that allows data docs to be rendered in dark mode based user request. The user might indicate this preference through an operating system setting (e.g. light or dark mode) or a user agent setting.
- Resolves #3814 
-

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

### CODE REVIEW

**Comment by austiezr** [comment]
Very cool! Love this. I'll leave code review to someone more fit for purpose, but some notes from playing with it for a while:

- Home page defaults to night mode and isn't inheriting on my system
    - night mode logo isn't being used on night mode home page
- Inspecting a validation result, everything looks great and inherits correctly!
- Inspecting a suite, inherits correctly, but night mode logo isn't being used

**Comment by OrtalG** [comment]
@austiezr ready for re-review

**Review by austiezr — APPROVED** [review]
🎉 🌙  Working like a dream for me!

**Comment by marianore-beepboop** [comment]
It would be great if a toggle could be added to change between Light/Night mode. I have my PC on dark mode (as every logic person) but I really prefer watching the GE Docs page on Light mode.

**Pull request merged**
