### PR TITLE
Feature/expectation suite edit method

### PR DESCRIPTION
**Pull request by abegong**
Adds `ExpectationConfiguration.update_kwargs` and `ExpectationSuite.update_expectation` methods. (In a perfect world, I would have implemented these separately, but I didn't realize the need for `ExpectationConfiguration.update_kwargs` until I started.)

Note: after reviewing our existing methods, I'm standardizing on `update_*`, not `edit_*` as the name for these crUd methods. We already use `update` in several places. The only place we use `edit_` is in the jupyter CLI command `edit expectation suite`, which is substantively different from CRUD methods.

### CODE REVIEW

**Comment by jcampbell** [comment]
Could you provide some examples to motivate the creation of an update operation for an expectation? Because expectations do not have ids, the historical mechanism to update them is to re-run the expectation with the new or changed kwargs, so I need some more context on what this is doing.

**Comment by abegong** [comment]
Short version: ExpectationSuites don't have a concept of re-running, since they can't be run at all without a DataAsset.

I encountered this while working on a profiling demo---will look for the demo to share a specific example.

**Comment by abegong** [comment]
And I agree that ids would make this easier. Are we planning to implement those soon?

**Comment by jcampbell** [comment]
Given that the profiling API is still very much in flux and at this point primarily designed to support suite generation, I think based on what you're describing I would suggest the following workflow:

```
suite = ...my_profiler_way_of_building_suite...
batch = PandasDataset(expectation_suite=suite)
batch.expect_all_the_things()
```

**Comment by jcampbell** [comment]
With respect to ids -- I was noting why *not* to worry about update. There is no plan to create ids now.

**Review by jcampbell — CHANGES_REQUESTED** [review]
Thanks for a great conversation about this. I think we need to ensure that we support the key use case of wanting to update kwargs in an existing expectation suite. I'd like to counter propose the following API:

```
def update_expectation_configuration(expectation_configuration: ExpectationConfiguration, update_kwargs: dict, method="merge"):
"""Update the kwargs of existing expectation in this suite matching the configuration of `expectation_configuration` with update_kwargs, using 'method'.

Method may be one of "merge" or "replace". If method is replace, then the update_kwargs will be used to declare a new expectation, and an error will be raised if the new kwargs do not result in a valid expectation configuration. If method is "merge" then the existing kwargs will be merged with the update_kwargs.
```

For example, consider the following expectation configuration:
```
expectation_type: expect_column_values_to_be_in_set
kwargs:
  column: "a"
  value_set: ["foo", "bar"]
```
Then (pseudocode):
```
suite.update_expectation_configuration(
{expectation_type: expect_column_values_to_be_in_set
kwargs:
  column: "a"
  value_set: ["foo", "bar"]
},
{value_set: ["baz"]}
)
```
results in 
```
expectation_type: expect_column_values_to_be_in_set
kwargs:
  column: "a"
  value_set: ["foo", "bar", "baz"]
```

One key benefit of this approach  is that the "matching" of the expectation configuration in this case should be delegated to the expectation configuration "is equivalent to" method.

**Comment by jcampbell** [comment]
edit -- the delegation of comparing ExpectationConfiguration objects should not go to `isEquivalentTo` but to a new method called `appliesToSameData` (or similar if you'd like a different proposal). The reason is that this new method will allow us to (1) ensure we're only matching on the "relevant" kwargs (as defined by that expectation), and (2) match based on conditions as appropriate (see #1217)

**Comment by abegong** [comment]
To clarify: does `expectation_configuration` have to match exactly?

I don't understand the intended logic. Does it need to be an exact match on the `expectation_type` and all  kwargs?

**Comment by jcampbell** [comment]
No, expectation is not looking for an exact match; it is looking for true in response to `appliesToSameData`. For example, a table expectation will return true without reference to kwargs; a column_map or column_aggregate expectation will return true based on expectation_type, column, and condition; a column_pair_expectation will return true based on expectation_type, columnA and columnB, and condition; in general, the expectation_type (and so expectation) gets to decide what counts as the "same data".

**Comment by abegong** [comment]
oh, got it. Yes, that totally makes sense.

I'm now thinking on the main logic implemented in #1298 as a rough-cut version of `appliesToSameData`.

Gotta work on that name, though...

**Comment by jcampbell** [comment]
Yes and yes!

**Comment by abegong** [comment]
Closing in favor of #1298

**Pull request closed without merging**
