### PR TITLE
Improve partitions in line with #34 and #89

### PR DESCRIPTION
**Pull request by jpcampb2**
Two issues still with where I think this PR is:

1. The default behavior of expect_kl_divergence (to merge partition segments with zero weight before calculating relative entropy) seems worth flagging when I was reading back through the code. This PR gives a chance to discuss.

2. We ought to confirm via this PR that this matches the intent of our earlier discussion wrt the intuition about data just outside the bounds of the initial data used to formulate the partition.

### CODE REVIEW

**Review by abegong — DISMISSED** [review]
I'm not sure I understand the first issue. Worth discussing on Friday?

The second issue looks resolved to me. Explicitly adding -inf and inf seems like the right thing to do.

Do JSON objects containing -inf and inf serialize? Do they load properly?

**Comment by jpcampb2** [comment]
Confirming that JSON serialization using the strings '-Infinity' and 'Infinity' works, yes, by virtue of our using the python std json library's default `allow_nan=True`  (see https://docs.python.org/2/library/json.html).

To be clear though, that does mean we're not strictly conforming to the JSON spec for our expectations object.

Still looking forward to the discussion on the right behavior of the kl_divergence test wrt the 0-weight sub-partitions.

**Comment by jpcampb2** [comment]
@abegong please go ahead and take a look again at this PR. It's ready for some new eyes, and I think matches the set of discussions we've had.

**Comment by abegong** [comment]
Looking into it now. Why did test coverage drop so much?

**Comment by abegong** [comment]
Okay, I think I get it. I'm going to get lunch and then run some examples.

**Comment by jcampbell** [comment]
Just confirming, I don't think test coverage actually dropped. I'm not sure why that message popped up, but I think coverage is actually slightly up.

**Comment by abegong** [comment]
This all looks really good. I've verified at least the main KL pathway from scratch in notebooks.

I think we should merge this. I have a few API + documentation changes to propose, but they're small, and will make more sense on top of a working base.

Very cool stuff!

**Pull request merged**
