### PR TITLE
Custom SQL for creating SA datasets (#249)

### PR DESCRIPTION
**Pull request by bouke-nederstigt**
First attempt at solving #249 . I think this is the most basic approach. Just enables developers to create sqlalchemy datasets by submitting raw sql.  

I'll see if I can add some tests later, but wanted to know if there are comments already?

### CODE REVIEW

**Review by abegong — COMMENTED** [review]
This is very cool. Excited to start experimenting with this new workflow...

A couple questions:
* Can you include an example of how custom SQL is intended to be used? A unit test of two would be a great way to set this up.
* What SQL dialect is the `CREATE TEMPORARY TABLE` query in? Any thoughts on how to make this generalize across dialects?

For broader discussion (non-blocking):
* What's the panda's analogue to this approach? We've wanted some kind of preprocessing API for a while.

**Comment by bouke-nederstigt** [comment]
To answer your questions.
- I've added a unit test showing how the custom sql is used. For simplicity sake I didn't include a join, but the basic concept is the same.
- I slightly adjusted the original query. I think it now conforms to standard SQL, so I guess it should be supported by most engines supporting temp tables. It now definitely works in Sqlite and MySQL. I checked the docs for Postgres and Oracle and I'm pretty sure those are ok too. Only not too sure about Microsoft SQL server.  
I did a bit of research on how to implement this on a slightly higher level in SQLAlchemy, but from what I could find it doesn't seem like a great way to go. All the possibilities seem pretty verbose, and unless models need to be introspected from the created table most people end up writing raw sql anyway.

Only trouble right now is with the failing test. I'm having a hard time figuring out why they're failing on Travis. Locally there are no issues, so I'm probably just overlooking something small. If you have any idea please let me know.

**Comment by abegong** [comment]
Aha! The problem is a minor conflict with the latest commits on the `develop` branch: `initialize_expectations` is now `_initialize_expectations`.

```
=================================== FAILURES ===================================
____________________ test_sqlalchemydataset_with_custom_sql ____________________
    def test_sqlalchemydataset_with_custom_sql():
        engine = sa.create_engine('sqlite://')
    
        data = pd.DataFrame({
            "name": ["Frank", "Steve", "Jane", "Frank", "Michael"],
            "age": [16, 21, 38, 22, 10],
            "pet": ["fish", "python", "cat", "python", "frog"]
        })
    
        data.to_sql(name='test_sql_data', con=engine, index=False)
    
        custom_sql = "SELECT name, pet FROM test_sql_data WHERE age > 12"
        custom_sql_dataset = SqlAlchemyDataset('test_sql_data', engine=engine, custom_sql=custom_sql)
    
>       custom_sql_dataset.initialize_expectations()
E       AttributeError: 'SqlAlchemyDataset' object has no attribute 'initialize_expectations'
tests/sqlalchemy_dataset/test_sqlalchemydataset.py:102: AttributeError
```

**Comment by jpcampb2** [comment]
Thanks, @bouke-nederstigt! This looks like a great addition.

**Comment by abegong** [comment]
One request: since we're not 100% sure about the portability of the SQL syntax, can you include a docstring warning on the function?

"WARNING: this feature is new in v0.4. It hasn't been tested in all SQL dialects, and may change based on community feedback."

...or something similar.

Thanks!

**Comment by bouke-nederstigt** [comment]
Ah thx, just forgot to pull upstream! Should be good to go now :)

**Comment by abegong** [comment]
Looks great!

**Pull request merged**
