### PR TITLE
[DOCS] Missing image link to bigquery logo

### PR DESCRIPTION
**Pull request by nelsonauner**
- [x] Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Update missing image link in your central README

### CODE REVIEW

**Review by eugmandel — CHANGES_REQUESTED** [review]
Thank you for spotting the broken logo, @nelsonauner! 

A small request - I see that you are linking to your GitHub gist: https://raw.githubusercontent.com/gist/nelsonauner. Could you please replace it with a more "official" URL?

**Comment by nelsonauner** [comment]
@eugmandel 

 Great point, but therein lies an interesting problem. The old link was to an image on wikipedia, presumably on https://en.wikipedia.org/wiki/BigQuery. This image has since been removed. 

Google's official big query page https://cloud.google.com/bigquery does not have any specific logo

The only official reference I can find to a logo is logging in to big query:
image


However, that logo is simply defined as an svg within the site: 

image


And that SVG is just defined within the source. 

```html
<svg fill="none" fill-rule="evenodd" height="100%" viewBox="0 0 32 32" width="100%" fit="" preserveAspectRatio="xMidYMid meet" focusable="false">
<path d="M8.627 14.358v3.69c.58.998 1.4 1.834 2.382 2.435v-6.125H8.62z" fill="#424242"></path>
<path d="M13.044 10.972v10.54c.493.073.998.12 1.516.12.473 0 .934-.042 1.386-.104V10.972h-2.902z" fill="#616161"></path><path d="M18.294 15.81v4.604a6.954 6.954 0 0 0 2.384-2.556v-2.05h-2.384zm5.74 6.233l-1.99 1.992a.592.592 0 0 0 0 .836L27 29.83c.23.23.606.23.836 0l1.992-1.99a.594.594 0 0 0 0-.837l-4.957-4.956a.593.593 0 0 0-.83 0" fill="#424242"></path>
<path d="M14.615 2C7.648 2 2 7.648 2 14.615 2 21.582 7.648 27.23 14.615 27.23c6.966 0 12.614-5.648 12.614-12.615C27.23 7.648 21.58 2 14.61 2m0 21.96a9.346 9.346 0 0 1-9.346-9.345 9.347 9.347 0 1 1 9.346 9.346" fill="#757575">
</path>
</svg>
```


I think there are threeoptions: 

1. Use this SVG, since it is from an official source
2. Use a logo from someone else's site (google "Big Query Logo"). I think most of these logos are deprecated
3. Use the main google cloud logo (I think this is the direction google is going, unlike AWS)


Please let me know which of these three you want, and I will comply.

**Comment by eugmandel** [comment]
Thank you for answering! Yes, it is surprising that Google does not have hosted official logos for BigQuery. I am going to approve the PR now, since it definitely improves on having a broken image link and see if we need to host it ourselves later.

**Review by eugmandel — APPROVED** [review]
Thank you!

**Pull request merged**
