### PR TITLE
Possible solution to issue 150.

### PR DESCRIPTION
**Pull request by dlwhite5**

### CODE REVIEW

**Comment by abegong** [comment]
This looks really good.

I agree that including indexes in returned rows is the right idea.

Can we add a warning? Something like "Warning: this feature is new in Great Expectations v0.4 and may change in the future. If you have feedback, please share it under issue #150 on github."

**Comment by dlwhite5** [comment]
Were you thinking a print warning or a warnings.warn warning?

**Comment by abegong** [comment]
Oh, I was just thinking of comments in the code and documentation.

**Comment by dlwhite5** [comment]
Glad I asked. I thought you meant to put it in the executed code. Yes, I'll add the comments.

**Comment by jpcampb2** [comment]
I think we have a strong commitment to ensuring compatibility across new Datasets in 0.4, which this PR would break.

Rather than having this live in base as an option on validate, I think this should be processed as part of the result_format flag in the expectation decorator (so that it is also handled correctly in validate by default). Further, I think it will need to call down to subclasses's implementation of get_affected_rows in some way to avoid using a pandas-specific feature (loc) to grab the rows.

I do think that an interim solution in which we return an informative error message when someone tries to request affected_rows from a dataset that does not implement that functionality makes sense.

**Comment by jpcampb2** [comment]
Ping @dlwhite5 -- should we keep this PR open waiting your updates to address the above?

**Pull request closed without merging**
