### PR TITLE
[BUGFIX] Fix Renderer Configuration for expectation expect_column_values_to_not_be_in_set #6963

### PR DESCRIPTION
**Pull request by jmcorreia**
Fix Renderer Configuration for expectation expect_column_values_to_not_be_in_set.

Problem: 
- The docs are not being rendered for the expectation in question

Changes proposed in this pull request:
- fix typo from configuraiton to configuration

### CODE REVIEW

**Review by anthonyburdi — APPROVED** [review]
Great catch!! 🙇 Thank you.

**Comment by anthonyburdi** [comment]
@jmcorreia - all looks good, but would you mind signing the CLA using these instructions? https://github.com/great-expectations/great_expectations/pull/6990#issuecomment-1408929892

image
image

**Comment by jmcorreia** [comment]
@cla-bot check

**Comment by jmcorreia** [comment]
Hi @anthonyburdi, done. And merge develop into the branch again. Latest checks failed with connectivity issues, I guess, and I don't really know how to retrigger them.

**Pull request merged**
