### PR TITLE
[DOCS] Fix documentation links generated within template

### PR DESCRIPTION
**Pull request by thejasraju**
Changes proposed in this pull request:
- The documentation links for data context points to invalid URL. 
Invalid URL: https://docs.greatexpectations.io/en/latest/how_to_guides/spare_parts/data_context_reference.html#configuration 
Valid URL: https://docs.greatexpectations.io/en/latest/reference/spare_parts/data_context_reference.html#configuration 

- The documentation links for adding new data source also points to invalid URL.
Invalid URL: https://docs.greatexpectations.io/en/latest/reference/core_concepts/datasource_reference.html 
Valid URL: https://docs.greatexpectations.io/en/latest/reference/core_concepts/datasource.html

The proposed changes fix these invalid links.

### CODE REVIEW

**Comment by thejasraju** [comment]
@cla-bot check

**Comment by eugmandel** [comment]
@thejasraju Thank you for spotting the broken docs links!

**Review by eugmandel — APPROVED** [review]

**Comment by eugmandel** [comment]
@thejasraju Approved the PR! Could you please make sure to sign the CLA (Contributor License Agreement), so that I can merge? Thank you!

**Comment by thejasraju** [comment]
Thanks for the review @eugmandel , I signed the Superconductive: Individual Contributor License Agreement v1.0 earlier and commented, didn't seem to have worked so I submitted a new response in the form. 
Trying again:  @cla-bot check

**Comment by thejasraju** [comment]
I think it should work now, apologies for the back and forth: @cla-bot check

**Pull request merged**
