### PR TITLE
Feature/issue285

### PR DESCRIPTION
**Pull request by dlwhite5**
Added command-line option/argument to print GE version and exit

### CODE REVIEW

**Comment by jpcampb2** [comment]
This PR appears to have inadvertently brought in some old changes and has resulting conflicts. Could you create a new PR with just the change relevant for this issue?

**Comment by dlwhite5** [comment]
Not sure how to fix this.

Here's what I did to get to this state:

1. git checkout develop
2. git merge upstream/develop
3. git push
4. git checkout feature/issue285
5. git clean -n
6. git clean -f
7. pycharm (Made edits here to add version option.)
8. git commit ...
9. git push --set-upstream origin feature/issue285

What should I have done?

**Comment by jpcampb2** [comment]
I suspect the forked version of develop you're working from has commits that were never merged in, so you want to make sure to make your change on top of the current upstream/develop branch. Replace steps 1-4 with:

```
git fetch upstream
git checkout -b feature/issue285-redo upstream/develop
```

**Comment by dlwhite5** [comment]
Thanks. I'll try that.

**Comment by ccnobbli** [comment]
Hey @dlwhite5, I cherry-picked the relevant code from your commits. The extra merge conflict stuff was taken out!

**Comment by ncsu-las** [comment]
Cool @ccnobbli!

**Comment by jpcampb2** [comment]
Rather than letting this linger, I went ahead and merged this together with develop, and fixed the outstanding issue on the import statement along the way.

**Comment by ccnobbli** [comment]
Thanks!

**Comment by ncsu-las** [comment]
Ditto!

**Pull request merged**
