### PR TITLE
Set expectations

### PR DESCRIPTION
**Pull request by RoyalTS**
This implements #447. I hope the way I refactored some things is to your liking.

### CODE REVIEW

**Comment by RoyalTS** [comment]
The python 2.7 tests are failing, I see. What's the easiest way of setting up that test environment locally so I can fix this?

**Comment by jcampbell** [comment]
@RoyalTS  -- the easiest way of getting a local 2.7 environment is to use `tox` (and there is a tox.ini file in the repo that is closely aligned to the travis.yml file).

That said, we're about to stop 2.7 support in the next release of GE.

**Comment by jcampbell** [comment]
These look great overall, but I'm concerned about making the `parse_strings_as_datetimes` a bit more opaque using the decorator, and also codifying the ambiguity (see #462); could you adjust to have this layer on top of the more conservative logic in that PR?

**Comment by RoyalTS** [comment]
Ripped out the refactoring, fixed the failing tests (oh Python 2.7...). Good to go as far as I'm concerned.

As for the refactoring, do you still want it as a separate PR?

**Review by jcampbell — APPROVED** [review]
Thank you--this looks great.

**Pull request merged**
